"""
This type stub file was generated by pyright.
"""

from win.defbase_errordef import *
from win.errhandlingapi import *
from win.libloaderapi import *
from win.commctrl import *
from .core.handle import *
from .core.event import *
from .core.absutils import *
from win.com.comdefbase import HRESULT

def init_common_controls(): # -> None:
    ...

dwmapi = ...
WINDOWCOMPOSITIONATTRIB = INT
class WINDOWCOMPOSITIONATTRIBDATA(CStructure):
    _fields_ = ...
    Attrib: int
    pvData: int
    cbData: int


LPWINDOWCOMPOSITIONATTRIBDATA = ...
@user32.foreign(BOOL, HWND, LPWINDOWCOMPOSITIONATTRIBDATA)
def SetWindowCompositionAttribute(hwnd: int, pwcad: IPointer[WINDOWCOMPOSITIONATTRIBDATA]) -> int:
    ...

@dwmapi.foreign(HRESULT, HWND, DWORD, LPCVOID, DWORD)
def DwmSetWindowAttribute(hwnd: int, dwAttribute: int, pvAtribute: int, cbAttribute: int): # -> None:
    ...

DWMWA_USE_IMMERSIVE_DARK_MODE = ...
DWMWA_USE_HOSTBACKDROPBRUSH = ...
DWMWA_SYSTEMBACKDROP_TYPE = ...
DWMSBT_AUTO = ...
DWMSBT_NONE = ...
DWMSBT_MAINWINDOW = ...
DWMSBT_TRANSIENTWINDOW = ...
DWMSBT_TABBEDWINDOW = ...
WCA_TRANSITIONS_FORCEDISABLED = ...
WCA_ALLOW_NCPAINT = ...
WCA_CAPTION_BUTTON_BOUNDS = ...
WCA_NONCLIENT_RTL_LAYOUT = ...
WCA_EXTENDED_FRAME_BOUNDS = ...
WCA_DISALLOW_PEEK = ...
WCA_CLOAK = ...
WCA_CLOAKED = ...
WCA_ACCENT_POLICY = ...
WCA_EXCLUDED_FROM_DDA = ...
WCA_USEDARKMODECOLORS = ...
ACCENT_DISABLED = ...
ACCENT_ENABLE_GRADIENT = ...
ACCENT_ENABLE_TRANSPARENTGRADIENT = ...
ACCENT_ENABLE_BLURBEHIND = ...
ACCENT_ENABLE_SLOWMOVE = ...
ACCENT_STATE = INT
@user32.foreign(BOOL, HWND, PDWORD)
def GetWindowBand(hwnd: int, pdwBand: IPointer[DWORD]) -> int:
    ...

_to_unicode_keyboard_state = ...
def to_unicode(vk: int, scan_code: int) -> tuple[str, int]:
    ...

ZBID_DEFAULT = ...
ZBID_DESKTOP = ...
ZBID_UIACCESS = ...
ZBID_IMMERSIVE_IHM = ...
ZBID_IMMERSIVE_NOTIFICATION = ...
ZBID_IMMERSIVE_APPCHROME = ...
ZBID_IMMERSIVE_MOGO = ...
ZBID_IMMERSIVE_EDGY = ...
ZBID_IMMERSIVE_INACTIVEMOBODY = ...
ZBID_IMMERSIVE_INACTIVEDOCK = ...
ZBID_IMMERSIVE_ACTIVEMOBODY = ...
ZBID_IMMERSIVE_ACTIVEDOCK = ...
ZBID_IMMERSIVE_BACKGROUND = ...
ZBID_IMMERSIVE_SEARCH = ...
ZBID_GENUINE_WINDOWS = ...
ZBID_IMMERSIVE_RESTRICTED = ...
ZBID_SYSTEM_TOOLS = ...
ZBID_LOCK = ...
ZBID_ABOVELOCK_UX = ...
@kernel32.foreign(UINT, ATOM, LPWSTR, INT)
def GlobalGetAtomNameW(nAtom: int | ATOM, lpBuffer: WT_LPWSTR, nSize: int) -> int:
    ...

@kernel32.foreign(UINT, ATOM, LPWSTR, INT)
def GetAtomNameW(nAtom: int | ATOM, lpBuffer: WT_LPWSTR, nSize: int) -> int:
    ...

@kernel32.foreign(ATOM, LPCWSTR)
def GlobalFindAtomW(lpString: WT_LPWSTR) -> int:
    ...

@kernel32.foreign(ATOM, LPCWSTR)
def FindAtomW(lpString: WT_LPWSTR) -> int:
    ...

@kernel32.foreign(ATOM, ATOM)
def GlobalDeleteAtom(nAtom: int | ATOM) -> int:
    ...

@kernel32.foreign(ATOM, ATOM)
def DeleteAtom(nAtom: int | ATOM) -> int:
    ...

@kernel32.foreign(ATOM, LPCWSTR)
def AddAtomW(lpString: WT_LPWSTR) -> int:
    ...

@kernel32.foreign(ATOM, LPCWSTR)
def GlobalAddAtomW(lpString: WT_LPWSTR) -> int:
    ...

class Atom(ATOM, ControllableValue):
    def __init__(self, value: str | WT_ADDRLIKE = ...) -> None:
        ...
    
    @property
    def name(self) -> str:
        ...
    
    @classmethod
    def local(cls, name: str) -> Atom:
        ...
    


SUBCLASSPROC = ...
@comctl32.foreign(BOOL, HWND, SUBCLASSPROC, UINT_PTR, DWORD_PTR)
def SetWindowSubclass(hWnd: int, pfnSubclass: FARPROC, uIdSubclass: int, dwRefData: int) -> int:
    ...

@comctl32.foreign(BOOL, HWND, SUBCLASSPROC, UINT_PTR)
def RemoveWindowSubclass(hWnd: int, pfnSubclass: FARPROC, uIdSubclass: int) -> int:
    ...

@comctl32.foreign(LRESULT, HWND, UINT, WPARAM, LPARAM)
def DefSubclassProc(hWnd: int, uMsg: int, wParam: int, lParam: int) -> int:
    ...

class ACCENTPOLICY(CStructure):
    _fields_ = ...
    AccentState: int
    AccentFlags: int
    GradientColor: int
    AnimationId: int


class Menu(Handle):
    """
    Main window menu.
    """
    def close(self): # -> None:
        ...
    
    @classmethod
    def create(cls): # -> Self:
        ...
    
    def append(self, item: int, lp, flags: int): # -> None:
        """
        Append the item to menu.
        """
        ...
    
    def modify(self, position: int, item: int, lp, flags: int): # -> None:
        """
        Modify the menu.
        """
        ...
    
    def get_state(self, identifier: int, flags: int = ...) -> int:
        """
        Get state of the menu item.
        """
        ...
    
    def check(self, identifier: int, check: bool = ..., flags: int = ...) -> int:
        """
        Check or uncheck the menu item.
        """
        ...
    


class PopupMenu(Menu):
    """
    Popup menu class.
    """
    @classmethod
    def create(cls): # -> Self:
        ...
    
    def track(self, x: int, y: int, hWnd: int | HANDLE, flags: int = ...): # -> None:
        """
        Track the popup menu in given coordinates of window.
        """
        ...
    


GCLP_MENUNAME = ...
GCLP_HBRBACKGROUND = ...
GCLP_HCURSOR = ...
GCLP_HICON = ...
GCLP_HMODULE = ...
GCLP_CBWNDEXTRA = ...
GCLP_CBCLSEXTRA = ...
GCLP_WNDPROC = ...
GCLP_STYLE = ...
GCW_ATOM = ...
GCLP_HICONSM = ...
WSMT_SEND = ...
WSMT_POST = ...
class Window(HWND, Abs.Object):
    """
    Class, wrapping functionality of Win32 Window.
    """
    class Styles:
        window: Window
        def __init__(self, window: Window) -> None:
            ...
        
        def add(self, *styles: int): # -> None:
            """
            Add specific style (or styles).
            """
            ...
        
        def remove(self, *styles: int): # -> None:
            """
            Remove specific style (or styles).
            """
            ...
        
        def add_ex(self, *styles: int): # -> None:
            """
            Add specific extended style (or styles).
            """
            ...
        
        def remove_ex(self, *styles: int): # -> None:
            """
            Remove specific extended style (or styles).
            """
            ...
        
        def has(self, *styles: int) -> bool:
            """
            Check specific style (or styles) setted up.
            """
            ...
        
        def has_ex(self, *styles: int) -> bool:
            """
            Check specific extended style (or styles) setted up.
            """
            ...
        
    
    
    _foreign_cache: dict[int, Window] = ...
    def __hash__(self) -> int:
        ...
    
    def __eq__(self, window: int | HANDLE) -> bool:
        ...
    
    @classmethod
    def foreign(cls, hwnd: int) -> Window:
        """
        Create `Window` object from foreign HWND.
        """
        ...
    
    styles: Styles
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    _timers: dict[int, FARPROC]
    class_name: str | None
    def Window_on_nc_destroy(self): # -> None:
        ...
    
    def Window_on_create(self): # -> Literal[True]:
        ...
    
    @property
    def style(self) -> int:
        ...
    
    @style.setter
    def style(self, style: int): # -> None:
        ...
    
    @property
    def extended_style(self) -> int:
        ...
    
    @extended_style.setter
    def extended_style(self, extended_style: int): # -> None:
        ...
    
    @property
    def icon(self) -> Icon:
        ...
    
    @icon.setter
    def icon(self, icon: int | HANDLE): # -> None:
        ...
    
    @property
    def cursor(self) -> Icon:
        ...
    
    @cursor.setter
    def cursor(self, cursor: int | HANDLE): # -> None:
        ...
    
    def get_class_word(self, index: int) -> int:
        """
        Get class word value at specified index.
        """
        ...
    
    def set_class_word(self, index: int, value: WT_ADDRLIKE) -> int:
        """
        Set class word value at specified index.
        """
        ...
    
    def get_class_long(self, index: int) -> int:
        """
        Get class long value at specified index.
        """
        ...
    
    def set_class_long(self, index: int, value: WT_ADDRLIKE) -> int:
        """
        Set class long value at specified index.
        """
        ...
    
    def get_class_long_ptr(self, index: int) -> int:
        """
        Get class long pointer value at specified index.
        """
        ...
    
    def set_class_long_ptr(self, index: int, value: WT_ADDRLIKE) -> int:
        """
        Set class long pointer value at specified index.
        """
        ...
    
    def enable(self, enable: bool = ...): # -> None:
        """
        Enable the window.
        """
        ...
    
    def disable(self): # -> None:
        """
        Disable the window.
        """
        ...
    
    def register(self) -> int:
        """
        Register the window class.
        """
        ...
    
    def create(self, width: int = ..., height: int = ..., x: int = ..., y: int = ..., window_name: str = ..., parent: int | HWND = ..., identifier: int | HMENU = ..., parameter: int | WT_ADDRLIKE = ...): # -> None:
        """
        Create the window.
        """
        ...
    
    def on_paint(self, dc: PaintDC) -> bool:
        ...
    
    def on_size(self, flags: int, width: int, height: int) -> bool:
        ...
    
    def on_erase_background(self, dc: DC) -> bool:
        ...
    
    def on_focus_changed(self, previous: Window): # -> None:
        ...
    
    def on_focus_lost(self, focused: Window): # -> None:
        ...
    
    def on_set_cursor(self, hwnd: int, ht: int, message: int) -> bool:
        ...
    
    def on_nc_paint(self, dc: DC, region: Region): # -> Self:
        ...
    
    def on_nc_hittest(self, x: int, y: int) -> int:
        ...
    
    def on_nc_calcsize(self, rect: RECT, rectangles: list = ..., position: WINDOWPOS = ...) -> int:
        ...
    
    def on_sizing(self, edge: int, rect: Rect) -> bool:
        ...
    
    def window_proc(self, hwnd: int, msg: int, wParam: int, lParam: int) -> int:
        ...
    
    def window_subclass_thunk_proc(self, hwnd: int, msg: int, wParam: int, lParam: int, subclassId: int, dwUnused: int): # -> int:
        ...
    
    def subclass(self): # -> None:
        ...
    
    def unsubclass(self): # -> None:
        ...
    
    def window_subclass_proc(self, hwnd: int, msg: int, wParam: int, lParam: int) -> int | None:
        ...
    
    def default_window_proc(self, hwnd: int, msg: int, wParam: int, lParam: int) -> int:
        ...
    
    def focus(self): # -> None:
        """
        Focus the current window.
        """
        ...
    
    @property
    def focused(self) -> bool:
        ...
    
    def capture(self): # -> None:
        """
        Set the current window as mouse capture.
        """
        ...
    
    @property
    def capturing(self) -> bool:
        ...
    
    @capturing.setter
    def capturing(self, capturing: bool): # -> None:
        ...
    
    def timer(self, function: Callable, elapse: int, event_id: int = ...) -> int:
        ...
    
    def delay(self, function: Callable, elapse: int, event_id: int = ...) -> int:
        ...
    
    def kill_timer(self, event_id: int): # -> None:
        """
        Kill the timer by given Event ID.
        """
        ...
    
    def close(self): # -> None:
        """
        Close the window.
        """
        ...
    
    def destroy(self): # -> None:
        """
        Destroy the window.
        """
        ...
    
    def hide(self): # -> None:
        """
        Hide the window.
        """
        ...
    
    def show(self, nCmdShow: int = ...): # -> None:
        """
        Show the window.
        """
        ...
    
    def set_font(self, font: int | HANDLE, redraw: bool = ...): # -> None:
        """
        Set the window font.
        """
        ...
    
    @property
    def font(self) -> Font | None:
        ...
    
    @font.setter
    def font(self, font: int | HANDLE): # -> None:
        ...
    
    def is_child(self, hWnd: int | HANDLE) -> bool:
        """
        Check another window is a child of window.
        """
        ...
    
    def is_child_of(self, hWnd: int | HANDLE) -> bool:
        """
        Check is window child of another window.
        """
        ...
    
    def send_message(self, smt: int, message: int, wParam: WT_ADDRLIKE | str = ..., lParam: WT_ADDRLIKE | str = ...): # -> Literal[0] | None:
        """
        Overrideable send message with Send/Post negotiation and pending support.
        """
        ...
    
    def send(self, message: int, wParam: int = ..., lParam: int = ...) -> int:
        """
        Send the message to window.
        """
        ...
    
    def post(self, message: int, wParam: int = ..., lParam: int = ...): # -> None:
        """
        Post the message to window (asynchronous send).
        """
        ...
    
    def map(self, window: int | HWND, points: Iterable[GraphicUtils.Point]) -> tuple[POINT, ...]:
        """
        Map the given points of window to an another window.
        """
        ...
    
    def post_indirect(self, msg: MSG): # -> Literal[0] | None:
        """
        Indirectly post MSG structure to the window (asynchronous send).
        """
        ...
    
    def send_indirect(self, msg: MSG) -> int:
        """
        Indirectly send MSG structure to the window.
        """
        ...
    
    def unpend_all_messages(self) -> tuple[int, int]:
        """
        Unpend all send all pended messages.
        """
        ...
    
    def pend_message(self, smt: int, message: int, wParam: int = ..., lParam: int = ...): # -> None:
        """
        Pend the message into pending queue.
        """
        ...
    
    @property
    def menu(self) -> Menu | None:
        ...
    
    @menu.setter
    def menu(self, menu: int | HANDLE): # -> None:
        ...
    
    @property
    def name(self) -> str:
        ...
    
    @name.setter
    def name(self, name: str): # -> None:
        ...
    
    @property
    def parent(self) -> Window:
        ...
    
    @parent.setter
    def parent(self, parent: int | HWND): # -> None:
        ...
    
    @property
    def rect(self) -> Rect:
        ...
    
    def set_position(self, x: int = ..., y: int = ..., width: int = ..., height: int = ..., flags: int = ..., insert_after: int | HWND = ...): # -> None:
        """
        Set the window position.
        """
        ...
    
    @classmethod
    def foreground(self) -> Window:
        """
        Get the foreground window.
        """
        ...
    
    @classmethod
    def desktop(self) -> Window:
        """
        Get the desktop window.
        """
        ...
    
    def set_foreground(self): # -> None:
        """
        Set the current window as foreground.
        """
        ...
    
    def to_client(self, screen: POINT): # -> None:
        """
        Convert screen point to client point.
        """
        ...
    
    def to_screen(self, client: POINT): # -> None:
        """
        Convert client point to screen point.
        """
        ...
    
    @property
    def client_rect(self) -> Rect:
        ...
    
    @client_rect.setter
    def client_rect(self, client_rect: RECT): # -> None:
        ...
    
    @property
    def valid(self): # -> None:
        ...
    
    @property
    def width(self) -> int:
        ...
    
    @width.setter
    def width(self, width: int): # -> None:
        ...
    
    @property
    def height(self) -> int:
        ...
    
    @height.setter
    def height(self, height: int): # -> None:
        ...
    
    @property
    def size(self) -> tuple[int, int]:
        ...
    
    @size.setter
    def size(self, size: tuple[int, int]): # -> None:
        ...
    
    @property
    def x(self) -> int:
        ...
    
    @x.setter
    def x(self, x: int): # -> None:
        ...
    
    @property
    def y(self) -> int:
        ...
    
    @y.setter
    def y(self, y: int): # -> None:
        ...
    
    @property
    def position(self) -> tuple[int, int]:
        ...
    
    @position.setter
    def position(self, position: GraphicUtils.Point): # -> None:
        ...
    
    def invalidate(self, region: RECT | Region = ..., erase: bool = ...): # -> None:
        """
        Invalidate the given rectangle/region (or NULL) of window.
        """
        ...
    
    def update(self): # -> None:
        """
        Update the window view.
        """
        ...
    
    def set_dwm_attribute(self, attribute: int, value: CData): # -> None:
        """
        Set the DWM attribute of window.
        """
        ...
    
    def set_composition_attribute(self, attribute: int, value: CData): # -> None:
        """
        Set the composition attribute of window.
        """
        ...
    
    def get_long(self, index: int) -> int:
        """
        Get window long value.
        """
        ...
    
    def set_long(self, index: int, value: int): # -> None:
        """
        Set window long value.
        """
        ...
    
    def get_long_ptr(self, index: int) -> int:
        """
        Get window long pointer value.
        """
        ...
    
    def set_long_ptr(self, index: int, value: int): # -> None:
        """
        Set window long pointer value.
        """
        ...
    
    def redraw(self, flags: int, region: RECT | Region = ...): # -> None:
        """
        Redraw the window.
        """
        ...
    
    def validate(self, region: RECT | Region = ...): # -> None:
        """
        Validate the given rectangle/region (or NULL) of window.
        """
        ...
    
    @classmethod
    def from_dc(cls, dc: DC) -> Window:
        """
        Get the window from DC.
        """
        ...
    
    def draw_caption(self, dc: DC, rect: RECT, flags: int): # -> None:
        """
        Draw the caption of window.
        """
        ...
    
    @classmethod
    def from_point(cls, point: POINT, physical: bool = ...) -> Window:
        """
        Get the window from point (DPI-adjusted or physical).
        """
        ...
    
    def set_layered_attributes(self, color: Color.IColorAlpha | int, alpha: bool, flags: int): # -> None:
        """
        Set the opacity and transparency color key of a layered window.
        """
        ...
    
    def update_layered(self, flags: int, color: Color.IColorAlpha | int, dest_dc: DC = ..., dest_point: GraphicUtils.Point = ..., size: GraphicUtils.Size = ..., src_dc: DC = ..., src_point: GraphicUtils.Point = ..., blend: BLENDFUNCTION = ...): # -> None:
        """
        Update the position, size, shape, content, and translucency of a layered window.
        """
        ...
    
    def tile_windows(self, how: int, windows: Iterable[Window], rect: RECT = ...): # -> None:
        """
        Tile specified child windows.
        """
        ...
    
    def tile(self, how: int, rect: RECT = ...): # -> None:
        """
        Tile current window.
        """
        ...
    
    def get_prop(self, prop: str | int) -> int:
        """
        Get the property value in window property list.
        """
        ...
    
    def set_prop(self, prop: str | int, data: int): # -> None:
        """
        Set the property value in window property list.
        """
        ...
    
    def draw_theme_parent_bk(self, dc: int | HANDLE, rect: RECT = ...): # -> None:
        """
        Draw the part of a parent control that is covered by a partially-transparent or alpha-blended child control.
        """
        ...
    
    @property
    def band(self) -> int:
        ...
    
    @classmethod
    def find(cls, name: str = ..., class_name: str = ..., parent: int | HANDLE = ..., after: int | HANDLE = ...) -> Window:
        """
        Find window.
        """
        ...
    
    def enum_props(self, callback: Callable[[str, int], bool], parameter: int = ...) -> bool:
        """
        Enumerate properties of a window.
        """
        ...
    
    def get(self, command: int) -> Window:
        """
        Get window by command, which is related with instance window.
        """
        ...
    
    @classmethod
    def enum_windows(cls, callback: Callable[[Window, int], bool], parameter: int = ...) -> bool:
        """
        Enumerate all top-level windows.
        """
        ...
    
    def top(self) -> Window:
        """
        Get top window.
        """
        ...
    
    def enum_child_windows(self, callback: Callable[[Window, int], bool], parameter: WT_ADDRLIKE = ...): # -> None:
        """
        Enumerate child windows of window.
        """
        ...
    
    @property
    def children(self) -> list[Window]:
        ...
    
    @property
    def descendants(self) -> list[Window]:
        ...
    
    def item(self, identifier: int) -> int:
        """
        Get item in window/dialog by identifier.
        """
        ...
    
    @property
    def identifier(self) -> int:
        ...
    


class MDIMenu(Menu):
    """
    Menu instance for MDI frames.
    """
    window: Window
    def initialize_from_foreign(self, window: int | HANDLE): # -> None:
        ...
    
    @classmethod
    def create(cls, window: int | HWND): # -> Self:
        ...
    
    def refresh(self): # -> None:
        """
        Refresh MDI Menu.
        """
        ...
    


class MDIWindow(Window):
    """
    Window instance for MDI Frames.
    """
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def create(self, width: int = ..., height: int = ..., x: int = ..., y: int = ..., window_name: str = ..., parent: int | HWND = ..., identifier: int | HMENU = ...): # -> None:
        ...
    
    def default_window_proc(self, hwnd: int, msg: int, wParam: int, lParam: int) -> int:
        ...
    


MDI_CHILDID_BASE = ...
class MDIClientWindow(Window):
    """
    Window for MDI Client class.
    """
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def create(self, width: int = ..., height: int = ..., x: int = ..., y: int = ..., window_name: str = ..., parent: int | HWND = ..., menu: int | HMENU = ...): # -> None:
        ...
    
    def cascade(self, behavior: int = ...): # -> None:
        """
        Cascade all MDI children by specified behavior.
        """
        ...
    
    def tile(self, tiling: int): # -> None:
        """
        Tile all MDI children by specified tiling.
        """
        ...
    
    def arrange(self): # -> None:
        """
        Arrange all MDI children.
        """
        ...
    
    @property
    def active(self) -> MDIChildWindow:
        ...
    
    @property
    def menu(self) -> MDIMenu:
        ...
    
    @menu.setter
    def menu(self, menu: int | HANDLE): # -> None:
        ...
    
    def set_window_menu(self, window_menu: int | HANDLE): # -> None:
        """
        Set MDI frame window menu.
        """
        ...
    
    window_menu = ...
    def window_subclass_proc(self, hwnd: int, msg: int, wParam: int, lParam: int) -> int | None:
        ...
    
    def mdi_message_procedure(self, hwnd: int, msg: int, wParam: int, lParam: int) -> int | None:
        ...
    


class MDIChildWindow(Window):
    def __init__(self, *args, **kwargs) -> None:
        ...
    
    def create(self, width: int = ..., height: int = ..., x: int = ..., y: int = ..., window_name: str = ..., parent: int | HWND = ...): # -> None:
        ...
    
    def close(self): # -> None:
        ...
    
    def destroy(self): # -> None:
        ...
    
    def maximize(self): # -> None:
        """
        Maximize the MDI child window.
        """
        ...
    
    def restore(self): # -> None:
        """
        Restore the MDI child window.
        """
        ...
    
    def default_window_proc(self, hwnd: int, msg: int, wParam: int, lParam: int) -> int:
        ...
    


class Application:
    """
    Main application class. 
    """
    INSTANCE: Application = ...
    modeless_dialogs: list[int | HWND]
    windows: int
    def __new__(cls): # -> Application:
        ...
    
    def __init__(self) -> None:
        ...
    
    def notify(self): # -> None:
        """
        Notify the application about windows count changed.
        """
        ...
    
    def launch(self, window: int | HANDLE = ...): # -> None:
        """
        Launch the application event cycle.
        """
        ...
    
    def hook(self, hwnd: int | HANDLE, procedure: Callable[[MSG], None], message: int = ...): # -> None:
        ...
    


class IdentifiersT:
    """
    Class specifically for generating new item identifiers by instance get-item access.
    
    E.g. Identifiers['Name'] => 0x800
    """
    _identifiers: dict[str, int]
    def __init__(self) -> None:
        ...
    
    def __getitem__(self, identifier: str) -> int:
        ...
    


Identifiers = ...
class MessagesT:
    """
    Class specifically for generating new window messages by instance get-item access.
    
    E.g. Messages['Name'] => 0x4AB
    """
    _messages: dict[str, int]
    def __init__(self) -> None:
        ...
    
    def __getitem__(self, message: str) -> int:
        ...
    


Messages = ...
class AutoIncrementMap:
    _map: dict[str, int]
    def __init__(self, start: int) -> None:
        ...
    
    def __getitem__(self, name: str) -> int:
        ...
    
    def get(self) -> int:
        ...
    


SubclassIdentifiers = ...
class Control(Window):
    """
    Class, representing the control (window, hosted and owned by another window).
    """
    _id_last: ClassVar[int] = ...
    def __init__(self, parent: int | HWND, identifier: int | HMENU) -> None:
        ...
    
    _identifier: int | HMENU
    _parent: int | HWND
    @staticmethod
    def id() -> int:
        """
        Generate the new control ID.
        """
        ...
    
    @property
    def visible(self): # -> int:
        ...
    
    @visible.setter
    def visible(self, visible: bool): # -> None:
        ...
    
    def create(self, width: int, height: int, x: int = ..., y: int = ..., window_name: str = ..., relative: int | HWND = ...): # -> None:
        """
        Create the control.
        """
        ...
    


class GLWindow(Window):
    """
    GL (1.1) Window.
    """
    pfd: PIXELFORMATDESCRIPTOR
    gl_context: GLContext
    def __init__(self) -> None:
        ...
    
    def disable_after_message_render(self): # -> None:
        """
        Disable the after-message render, which is bound to application event cycle.
        """
        ...
    
    def GL_after_message(self): # -> None:
        ...
    
    def GL_close(self): # -> Literal[True]:
        ...
    
    def initialize_gl(self): # -> None:
        """
        Initialize the OpenGL context on window.
        """
        ...
    
    def create(self, width: int = ..., height: int = ..., x: int = ..., y: int = ..., window_name: str = ..., parent=...): # -> None:
        """
        Create the OpenGL window.
        """
        ...
    


PFNWGLCREATECONTEXTATTRIBSARB = ...
WGL_CONTEXT_MAJOR_VERSION_ARB = ...
WGL_CONTEXT_MINOR_VERSION_ARB = ...
WGL_CONTEXT_PROFILE_MASK_ARB = ...
WGL_CONTEXT_CORE_PROFILE_BIT_ARB = ...
WGL_CONTEXT_COMPATIBILITY_PROFILE_BIT_ARB = ...
WGL_CONTEXT_FLAGS_ARB = ...
WGL_CONTEXT_DEBUG_BIT_ARB = ...
WGL_CONTEXT_FORWARD_COMPATIBLE_BIT_ARB = ...
WGL_CONTEXT_LAYER_PLANE_ARB = ...
class ExtendedGLWindow(GLWindow):
    """
    Extended GL Window with modern OpenGL support.
    """
    wglCreateContextAttribsARB: Callable[[int, int, PINT], int]
    attributes: dict[int, int]
    def __init__(self) -> None:
        ...
    
    def create(self, width: int = ..., height: int = ..., x: int = ..., y: int = ..., window_name: str = ..., parent=...): # -> None:
        ...
    
    def version(self, major: int | str, minor: int = ...): # -> None:
        """
        Set the OpenGL version of window. 
        """
        ...
    


