"""
/**************************************************************************\
*
* Copyright (c) 1998-2001, Microsoft Corp.  All Rights Reserved.
*
* Module Name:
*
*   Gdiplus.h
*
* Abstract:
*
*   GDI+ public header file
*
\**************************************************************************/
"""

from types import ModuleType
from typing import Type

from . import cpreproc

if cpreproc.pragma_once("_GDIPLUS_H"):
    from .minwindef import *
    from .defbase import *

    # REGION *** Desktop Family ***

    class IDirectDrawSurface7(CStructure):
        pass

    # Define the Current GDIPlus Version
    if cpreproc.ifndef("GDIPVER"):
        cpreproc.define("GDIPVER", 0x0100)
        
    from . import gdiplusmem as _gdpmem
    from . import gdiplusbase as _gdpbase
    
    from . import gdiplusenums as _gdpenums
    from . import gdiplustypes as _gdptypes
    from . import gdiplusinit  as _gdpinit
    from . import gdipluspixelformats as _gdppf
    from . import gdipluscolor as _gdpcolor
    from . import gdiplusmetaheader as _gdpmh
    from . import gdiplusimaging as _gdpimg
    from . import gdipluscolormatrix as _gdpcmat
    
    class Gdiplus:
        class DllExports: 
            # gdiplusmem.py
            def GdipAlloc(size: int) -> PVOID: ...
            def GdipFree(ptr: PVOID): ...

        module_to_namespace(_gdpmem, DllExports)
        
        # gdiplusbase.py
        GdiplusBase: Type[_gdpbase.GdiplusBase]
        # gdiplusenums.py
        FlatnessDefault: float
        GraphicsState: Type[_gdpenums.GraphicsState]
        GraphicsContainer: Type[_gdpenums.GraphicsContainer]
        FillMode: Type[_gdpenums.FillMode]
        FillModeAlternate: int
        FillModeWinding: int
        QualityMode: Type[_gdpenums.QualityMode]
        QualityModeInvalid: int
        QualityModeDefault: int
        QualityModeLow: int
        QualityModeHigh: int
        CompositingMode: Type[_gdpenums.CompositingMode]
        CompositingModeSourceOver: int
        CompositingModeSourceCopy: int
        CompositingQuality: Type[_gdpenums.CompositingQuality]
        CompositingQualityInvalid: int
        CompositingQualityDefault: int
        CompositingQualityHighSpeed: int
        CompositingQualityHighQuality: int
        CompositingQualityGammaCorrected: int
        CompositingQualityAssumeLinear: int
        Unit: Type[_gdpenums.Unit]
        UnitWorld: int
        UnitDisplay: int
        UnitPixel: int
        UnitPoint: int
        UnitInch: int
        UnitDocument: int
        UnitMillimeter: int
        MetafileFrameUnit: Type[_gdpenums.MetafileFrameUnit]
        MetafileFrameUnitPixel: int
        MetafileFrameUnitPoint: int
        MetafileFrameUnitInch: int
        MetafileFrameUnitDocument: int
        MetafileFrameUnitMillimeter: int
        MetafileFrameUnitGdi: int
        CoordinateSpace: Type[_gdpenums.CoordinateSpace]
        CoordinateSpaceWorld: int
        CoordinateSpacePage: int
        CoordinateSpaceDevice: int
        WrapMode: Type[_gdpenums.WrapMode]
        WrapModeTile: int
        WrapModeTileFlipX: int
        WrapModeTileFlipY: int
        WrapModeTileFlipXY: int
        WrapModeClamp: int
        HatchStyle: Type[_gdpenums.HatchStyle]
        HatchStyleHorizontal: int
        HatchStyleVertical: int
        HatchStyleForwardDiagonal: int
        HatchStyleBackwardDiagonal: int
        HatchStyleCross: int
        HatchStyleDiagonalCross: int
        HatchStyle05Percent: int
        HatchStyle10Percent: int
        HatchStyle20Percent: int
        HatchStyle25Percent: int
        HatchStyle30Percent: int
        HatchStyle40Percent: int
        HatchStyle50Percent: int
        HatchStyle60Percent: int
        HatchStyle70Percent: int
        HatchStyle75Percent: int
        HatchStyle80Percent: int
        HatchStyle90Percent: int
        HatchStyleLightDownwardDiagonal: int
        HatchStyleLightUpwardDiagonal: int
        HatchStyleDarkDownwardDiagonal: int
        HatchStyleDarkUpwardDiagonal: int
        HatchStyleWideDownwardDiagonal: int
        HatchStyleWideUpwardDiagonal: int
        HatchStyleLightVertical: int
        HatchStyleLightHorizontal: int
        HatchStyleNarrowVertical: int
        HatchStyleNarrowHorizontal: int
        HatchStyleDarkVertical: int
        HatchStyleDarkHorizontal: int
        HatchStyleDashedDownwardDiagonal: int
        HatchStyleDashedUpwardDiagonal: int
        HatchStyleDashedHorizontal: int
        HatchStyleDashedVertical: int
        HatchStyleSmallConfetti: int
        HatchStyleLargeConfetti: int
        HatchStyleZigZag: int
        HatchStyleWave: int
        HatchStyleDiagonalBrick: int
        HatchStyleHorizontalBrick: int
        HatchStyleWeave: int
        HatchStylePlaid: int
        HatchStyleDivot: int
        HatchStyleDottedGrid: int
        HatchStyleDottedDiamond: int
        HatchStyleShingle: int
        HatchStyleTrellis: int
        HatchStyleSphere: int
        HatchStyleSmallGrid: int
        HatchStyleSmallCheckerBoard: int
        HatchStyleLargeCheckerBoard: int
        HatchStyleOutlinedDiamond: int
        HatchStyleSolidDiamond: int
        HatchStyleTotal: int
        HatchStyleLargeGrid: int
        HatchStyleMin: int
        HatchStyleMax: int
        DashStyle: Type[_gdpenums.DashStyle]
        DashStyleSolid: int
        DashStyleDash: int
        DashStyleDot: int
        DashStyleDashDot: int
        DashStyleDashDotDot: int
        DashStyleCustom: int
        DashCap: Type[_gdpenums.DashCap]
        DashCapFlat: int
        DashCapRound: int
        DashCapTriangle: int
        LineCap: Type[_gdpenums.LineCap]
        LineCapFlat: int
        LineCapSquare: int
        LineCapRound: int
        LineCapTriangle: int
        LineCapNoAnchor: int
        LineCapSquareAnchor: int
        LineCapRoundAnchor: int
        LineCapDiamondAnchor: int
        LineCapArrowAnchor: int
        LineCapCustom: int
        LineCapAnchorMask: int
        CustomLineCapType: Type[_gdpenums.CustomLineCapType]
        CustomLineCapTypeDefault: int
        CustomLineCapTypeAdjustableArrow: int
        LineJoin: Type[_gdpenums.LineJoin]
        LineJoinMiter: int
        LineJoinBevel: int
        LineJoinRound: int
        LineJoinMiterClipped: int
        PathPointType: Type[_gdpenums.PathPointType]
        PathPointTypeStart: int
        PathPointTypeLine: int
        PathPointTypeBezier: int
        PathPointTypePathTypeMask: int
        PathPointTypeDashMode: int
        PathPointTypePathMarker: int
        PathPointTypeCloseSubpath: int
        PathPointTypeBezier3: int
        WarpMode: Type[_gdpenums.WarpMode]
        WarpModePerspective: int
        WarpModeBilinear: int
        LinearGradientMode: Type[_gdpenums.LinearGradientMode]
        LinearGradientModeHorizontal: int
        LinearGradientModeVertical: int
        LinearGradientModeForwardDiagonal: int
        LinearGradientModeBackwardDiagonal: int
        CombineMode: Type[_gdpenums.CombineMode]
        CombineModeReplace: int
        CombineModeIntersect: int
        CombineModeUnion: int
        CombineModeXor: int
        CombineModeExclude: int
        CombineModeComplement: int
        ImageType: Type[_gdpenums.ImageType]
        ImageTypeUnknown: int
        ImageTypeBitmap: int
        ImageTypeMetafile: int
        InterpolationMode: Type[_gdpenums.InterpolationMode]
        InterpolationModeInvalid: int
        InterpolationModeDefault: int
        InterpolationModeLowQuality: int
        InterpolationModeHighQuality: int
        InterpolationModeBilinear: int
        InterpolationModeBicubic: int
        InterpolationModeNearestNeighbor: int
        InterpolationModeHighQualityBilinear: int
        InterpolationModeHighQualityBicubic: int
        PenAlignment: Type[_gdpenums.PenAlignment]
        PenAlignmentCenter: int
        PenAlignmentInset: int
        BrushType: Type[_gdpenums.BrushType]
        BrushTypeSolidColor: int
        BrushTypeHatchFill: int
        BrushTypeTextureFill: int
        BrushTypePathGradient: int
        BrushTypeLinearGradient: int
        PenType: Type[_gdpenums.PenType]
        PenTypeSolidColor: int
        PenTypeHatchFill: int
        PenTypeTextureFill: int
        PenTypePathGradient: int
        PenTypeLinearGradient: int
        PenTypeUnknown: int
        MatrixOrder: Type[_gdpenums.MatrixOrder]
        MatrixOrderPrepend: int
        MatrixOrderAppend: int
        GenericFontFamily: Type[_gdpenums.GenericFontFamily]
        GenericFontFamilySerif: int
        GenericFontFamilySansSerif: int
        GenericFontFamilyMonospace: int
        FontStyle: Type[_gdpenums.FontStyle]
        FontStyleRegular: int
        FontStyleBold: int
        FontStyleItalic: int
        FontStyleBoldItalic: int
        FontStyleUnderline: int
        FontStyleStrikeout: int
        SmoothingMode: Type[_gdpenums.SmoothingMode]
        SmoothingModeInvalid: int
        SmoothingModeDefault: int
        SmoothingModeHighSpeed: int
        SmoothingModeHighQuality: int
        SmoothingModeNone: int
        SmoothingModeAntiAlias: int
        SmoothingModeAntiAlias8x4: int
        SmoothingModeAntiAlias8x8: int
        PixelOffsetMode: Type[_gdpenums.PixelOffsetMode]
        PixelOffsetModeInvalid: int
        PixelOffsetModeDefault: int
        PixelOffsetModeHighSpeed: int
        PixelOffsetModeHighQuality: int
        PixelOffsetModeNone: int
        PixelOffsetModeHalf: int
        TextRenderingHint: Type[_gdpenums.TextRenderingHint]
        TextRenderingHintSystemDefault: int
        TextRenderingHintSingleBitPerPixelGridFit: int
        TextRenderingHintSingleBitPerPixel: int
        TextRenderingHintAntiAliasGridFit: int
        TextRenderingHintAntiAlias: int
        TextRenderingHintClearTypeGridFit: int
        MetafileType: Type[_gdpenums.MetafileType]
        MetafileTypeInvalid: int
        MetafileTypeWmf: int
        MetafileTypeWmfPlaceable: int
        MetafileTypeEmf: int
        MetafileTypeEmfPlusOnly: int
        MetafileTypeEmfPlusDual: int
        EmfType: Type[_gdpenums.EmfType]
        EmfTypeEmfOnly: int
        EmfTypeEmfPlusOnly: int
        EmfTypeEmfPlusDual: int
        ObjectType: Type[_gdpenums.ObjectType]
        ObjectTypeInvalid: int
        ObjectTypeBrush: int
        ObjectTypePen: int
        ObjectTypePath: int
        ObjectTypeRegion: int
        ObjectTypeImage: int
        ObjectTypeFont: int
        ObjectTypeStringFormat: int
        ObjectTypeImageAttributes: int
        ObjectTypeCustomLineCap: int
        ObjectTypeGraphics: int
        ObjectTypeMax: int
        def ObjectTypeIsValid(type: int) -> bool: ...
        GDIP_EMFPLUS_RECORD_BASE: int
        GDIP_WMF_RECORD_BASE: int
        def GDIP_WMF_RECORD_TO_EMFPLUS(n: int) -> int: ...
        def GDIP_EMFPLUS_RECORD_TO_WMF(n: int) -> int: ...
        def GDIP_IS_WMF_RECORDTYPE(n: int) -> bool: ...
        EmfPlusRecordType: Type[_gdpenums.EmfPlusRecordType]
        WmfRecordTypeSetBkColor: int
        WmfRecordTypeSetBkMode: int
        WmfRecordTypeSetMapMode: int
        WmfRecordTypeSetROP2: int
        WmfRecordTypeSetRelAbs: int
        WmfRecordTypeSetPolyFillMode: int
        WmfRecordTypeSetStretchBltMode: int
        WmfRecordTypeSetTextCharExtra: int
        WmfRecordTypeSetTextColor: int
        WmfRecordTypeSetTextJustification: int
        WmfRecordTypeSetWindowOrg: int
        WmfRecordTypeSetWindowExt: int
        WmfRecordTypeSetViewportOrg: int
        WmfRecordTypeSetViewportExt: int
        WmfRecordTypeOffsetWindowOrg: int
        WmfRecordTypeScaleWindowExt: int
        WmfRecordTypeOffsetViewportOrg: int
        WmfRecordTypeScaleViewportExt: int
        WmfRecordTypeLineTo: int
        WmfRecordTypeMoveTo: int
        WmfRecordTypeExcludeClipRect: int
        WmfRecordTypeIntersectClipRect: int
        WmfRecordTypeArc: int
        WmfRecordTypeEllipse: int
        WmfRecordTypeFloodFill: int
        WmfRecordTypePie: int
        WmfRecordTypeRectangle: int
        WmfRecordTypeRoundRect: int
        WmfRecordTypePatBlt: int
        WmfRecordTypeSaveDC: int
        WmfRecordTypeSetPixel: int
        WmfRecordTypeOffsetClipRgn: int
        WmfRecordTypeTextOut: int
        WmfRecordTypeBitBlt: int
        WmfRecordTypeStretchBlt: int
        WmfRecordTypePolygon: int
        WmfRecordTypePolyline: int
        WmfRecordTypeEscape: int
        WmfRecordTypeRestoreDC: int
        WmfRecordTypeFillRegion: int
        WmfRecordTypeFrameRegion: int
        WmfRecordTypeInvertRegion: int
        WmfRecordTypePaintRegion: int
        WmfRecordTypeSelectClipRegion: int
        WmfRecordTypeSelectObject: int
        WmfRecordTypeSetTextAlign: int
        WmfRecordTypeDrawText: int
        WmfRecordTypeChord: int
        WmfRecordTypeSetMapperFlags: int
        WmfRecordTypeExtTextOut: int
        WmfRecordTypeSetDIBToDev: int
        WmfRecordTypeSelectPalette: int
        WmfRecordTypeRealizePalette: int
        WmfRecordTypeAnimatePalette: int
        WmfRecordTypeSetPalEntries: int
        WmfRecordTypePolyPolygon: int
        WmfRecordTypeResizePalette: int
        WmfRecordTypeDIBBitBlt: int
        WmfRecordTypeDIBStretchBlt: int
        WmfRecordTypeDIBCreatePatternBrush: int
        WmfRecordTypeStretchDIB: int
        WmfRecordTypeExtFloodFill: int
        WmfRecordTypeSetLayout: int
        WmfRecordTypeResetDC: int
        WmfRecordTypeStartDoc: int
        WmfRecordTypeStartPage: int
        WmfRecordTypeEndPage: int
        WmfRecordTypeAbortDoc: int
        WmfRecordTypeEndDoc: int
        WmfRecordTypeDeleteObject: int
        WmfRecordTypeCreatePalette: int
        WmfRecordTypeCreateBrush: int
        WmfRecordTypeCreatePatternBrush: int
        WmfRecordTypeCreatePenIndirect: int
        WmfRecordTypeCreateFontIndirect: int
        WmfRecordTypeCreateBrushIndirect: int
        WmfRecordTypeCreateBitmapIndirect: int
        WmfRecordTypeCreateBitmap: int
        WmfRecordTypeCreateRegion: int
        EmfRecordTypeHeader: int
        EmfRecordTypePolyBezier: int
        EmfRecordTypePolygon: int
        EmfRecordTypePolyline: int
        EmfRecordTypePolyBezierTo: int
        EmfRecordTypePolyLineTo: int
        EmfRecordTypePolyPolyline: int
        EmfRecordTypePolyPolygon: int
        EmfRecordTypeSetWindowExtEx: int
        EmfRecordTypeSetWindowOrgEx: int
        EmfRecordTypeSetViewportExtEx: int
        EmfRecordTypeSetViewportOrgEx: int
        EmfRecordTypeSetBrushOrgEx: int
        EmfRecordTypeEOF: int
        EmfRecordTypeSetPixelV: int
        EmfRecordTypeSetMapperFlags: int
        EmfRecordTypeSetMapMode: int
        EmfRecordTypeSetBkMode: int
        EmfRecordTypeSetPolyFillMode: int
        EmfRecordTypeSetROP2: int
        EmfRecordTypeSetStretchBltMode: int
        EmfRecordTypeSetTextAlign: int
        EmfRecordTypeSetColorAdjustment: int
        EmfRecordTypeSetTextColor: int
        EmfRecordTypeSetBkColor: int
        EmfRecordTypeOffsetClipRgn: int
        EmfRecordTypeMoveToEx: int
        EmfRecordTypeSetMetaRgn: int
        EmfRecordTypeExcludeClipRect: int
        EmfRecordTypeIntersectClipRect: int
        EmfRecordTypeScaleViewportExtEx: int
        EmfRecordTypeScaleWindowExtEx: int
        EmfRecordTypeSaveDC: int
        EmfRecordTypeRestoreDC: int
        EmfRecordTypeSetWorldTransform: int
        EmfRecordTypeModifyWorldTransform: int
        EmfRecordTypeSelectObject: int
        EmfRecordTypeCreatePen: int
        EmfRecordTypeCreateBrushIndirect: int
        EmfRecordTypeDeleteObject: int
        EmfRecordTypeAngleArc: int
        EmfRecordTypeEllipse: int
        EmfRecordTypeRectangle: int
        EmfRecordTypeRoundRect: int
        EmfRecordTypeArc: int
        EmfRecordTypeChord: int
        EmfRecordTypePie: int
        EmfRecordTypeSelectPalette: int
        EmfRecordTypeCreatePalette: int
        EmfRecordTypeSetPaletteEntries: int
        EmfRecordTypeResizePalette: int
        EmfRecordTypeRealizePalette: int
        EmfRecordTypeExtFloodFill: int
        EmfRecordTypeLineTo: int
        EmfRecordTypeArcTo: int
        EmfRecordTypePolyDraw: int
        EmfRecordTypeSetArcDirection: int
        EmfRecordTypeSetMiterLimit: int
        EmfRecordTypeBeginPath: int
        EmfRecordTypeEndPath: int
        EmfRecordTypeCloseFigure: int
        EmfRecordTypeFillPath: int
        EmfRecordTypeStrokeAndFillPath: int
        EmfRecordTypeStrokePath: int
        EmfRecordTypeFlattenPath: int
        EmfRecordTypeWidenPath: int
        EmfRecordTypeSelectClipPath: int
        EmfRecordTypeAbortPath: int
        EmfRecordTypeReserved_069: int
        EmfRecordTypeGdiComment: int
        EmfRecordTypeFillRgn: int
        EmfRecordTypeFrameRgn: int
        EmfRecordTypeInvertRgn: int
        EmfRecordTypePaintRgn: int
        EmfRecordTypeExtSelectClipRgn: int
        EmfRecordTypeBitBlt: int
        EmfRecordTypeStretchBlt: int
        EmfRecordTypeMaskBlt: int
        EmfRecordTypePlgBlt: int
        EmfRecordTypeSetDIBitsToDevice: int
        EmfRecordTypeStretchDIBits: int
        EmfRecordTypeExtCreateFontIndirect: int
        EmfRecordTypeExtTextOutA: int
        EmfRecordTypeExtTextOutW: int
        EmfRecordTypePolyBezier16: int
        EmfRecordTypePolygon16: int
        EmfRecordTypePolyline16: int
        EmfRecordTypePolyBezierTo16: int
        EmfRecordTypePolylineTo16: int
        EmfRecordTypePolyPolyline16: int
        EmfRecordTypePolyPolygon16: int
        EmfRecordTypePolyDraw16: int
        EmfRecordTypeCreateMonoBrush: int
        EmfRecordTypeCreateDIBPatternBrushPt: int
        EmfRecordTypeExtCreatePen: int
        EmfRecordTypePolyTextOutA: int
        EmfRecordTypePolyTextOutW: int
        EmfRecordTypeSetICMMode: int
        EmfRecordTypeCreateColorSpace: int
        EmfRecordTypeSetColorSpace: int
        EmfRecordTypeDeleteColorSpace: int
        EmfRecordTypeGLSRecord: int
        EmfRecordTypeGLSBoundedRecord: int
        EmfRecordTypePixelFormat: int
        EmfRecordTypeDrawEscape: int
        EmfRecordTypeExtEscape: int
        EmfRecordTypeStartDoc: int
        EmfRecordTypeSmallTextOut: int
        EmfRecordTypeForceUFIMapping: int
        EmfRecordTypeNamedEscape: int
        EmfRecordTypeColorCorrectPalette: int
        EmfRecordTypeSetICMProfileA: int
        EmfRecordTypeSetICMProfileW: int
        EmfRecordTypeAlphaBlend: int
        EmfRecordTypeSetLayout: int
        EmfRecordTypeTransparentBlt: int
        EmfRecordTypeReserved_117: int
        EmfRecordTypeGradientFill: int
        EmfRecordTypeSetLinkedUFIs: int
        EmfRecordTypeSetTextJustification: int
        EmfRecordTypeColorMatchToTargetW: int
        EmfRecordTypeCreateColorSpaceW: int
        EmfRecordTypeMax: int
        EmfRecordTypeMin: int
        EmfPlusRecordTypeInvalid: int
        EmfPlusRecordTypeHeader: int
        EmfPlusRecordTypeEndOfFile: int
        EmfPlusRecordTypeComment: int
        EmfPlusRecordTypeGetDC: int
        EmfPlusRecordTypeMultiFormatStart: int
        EmfPlusRecordTypeMultiFormatSection: int
        EmfPlusRecordTypeMultiFormatEnd: int
        EmfPlusRecordTypeObject: int
        EmfPlusRecordTypeClear: int
        EmfPlusRecordTypeFillRects: int
        EmfPlusRecordTypeDrawRects: int
        EmfPlusRecordTypeFillPolygon: int
        EmfPlusRecordTypeDrawLines: int
        EmfPlusRecordTypeFillEllipse: int
        EmfPlusRecordTypeDrawEllipse: int
        EmfPlusRecordTypeFillPie: int
        EmfPlusRecordTypeDrawPie: int
        EmfPlusRecordTypeDrawArc: int
        EmfPlusRecordTypeFillRegion: int
        EmfPlusRecordTypeFillPath: int
        EmfPlusRecordTypeDrawPath: int
        EmfPlusRecordTypeFillClosedCurve: int
        EmfPlusRecordTypeDrawClosedCurve: int
        EmfPlusRecordTypeDrawCurve: int
        EmfPlusRecordTypeDrawBeziers: int
        EmfPlusRecordTypeDrawImage: int
        EmfPlusRecordTypeDrawImagePoints: int
        EmfPlusRecordTypeDrawString: int 
        EmfPlusRecordTypeSetRenderingOrigin: int
        EmfPlusRecordTypeSetAntiAliasMode: int
        EmfPlusRecordTypeSetTextRenderingHint: int
        EmfPlusRecordTypeSetTextContrast: int
        EmfPlusRecordTypeSetInterpolationMode: int
        EmfPlusRecordTypeSetPixelOffsetMode: int
        EmfPlusRecordTypeSetCompositingMode: int
        EmfPlusRecordTypeSetCompositingQuality: int
        EmfPlusRecordTypeSave: int
        EmfPlusRecordTypeRestore: int
        EmfPlusRecordTypeBeginContainer: int
        EmfPlusRecordTypeBeginContainerNoParams: int
        EmfPlusRecordTypeEndContainer: int
        EmfPlusRecordTypeSetWorldTransform: int
        EmfPlusRecordTypeResetWorldTransform: int
        EmfPlusRecordTypeMultiplyWorldTransform: int
        EmfPlusRecordTypeTranslateWorldTransform: int
        EmfPlusRecordTypeScaleWorldTransform: int
        EmfPlusRecordTypeRotateWorldTransform: int
        EmfPlusRecordTypeSetPageTransform: int
        EmfPlusRecordTypeResetClip: int
        EmfPlusRecordTypeSetClipRect: int
        EmfPlusRecordTypeSetClipPath: int
        EmfPlusRecordTypeSetClipRegion: int
        EmfPlusRecordTypeOffsetClip: int
        EmfPlusRecordTypeDrawDriverString: int
        if cpreproc.getdef("GDIPVER") >= 0x0110:
            EmfPlusRecordTypeStrokeFillPath: int
            EmfPlusRecordTypeSerializableObject: int

            EmfPlusRecordTypeSetTSGraphics: int
            EmfPlusRecordTypeSetTSClip: int
        EmfPlusRecordTotal: int
        EmfPlusRecordTypeMax: int
        EmfPlusRecordTypeMin: int
        StringFormatFlags: Type[_gdpenums.StringFormatFlags]
        StringFormatFlagsDirectionRightToLeft: int
        StringFormatFlagsDirectionVertical: int
        StringFormatFlagsNoFitBlackBox: int
        StringFormatFlagsDisplayFormatControl: int
        StringFormatFlagsNoFontFallback: int
        StringFormatFlagsMeasureTrailingSpaces: int
        StringFormatFlagsNoWrap: int
        StringFormatFlagsLineLimit: int
        StringFormatFlagsNoClip: int
        StringFormatFlagsBypassGDI: int
        StringTrimming: Type[_gdpenums.StringTrimming]
        StringTrimmingNone: int
        StringTrimmingCharacter: int
        StringTrimmingWord: int
        StringTrimmingEllipsisCharacter: int
        StringTrimmingEllipsisWord: int
        StringTrimmingEllipsisPath: int
        StringDigitSubstitute: Type[_gdpenums.StringDigitSubstitute]
        StringDigitSubstituteUser: int
        StringDigitSubstituteNone: int
        StringDigitSubstituteNational: int
        StringDigitSubstituteTraditional: int
        HotkeyPrefix: Type[_gdpenums.HotkeyPrefix]
        HotkeyPrefixNone: int
        HotkeyPrefixShow: int
        HotkeyPrefixHide: int
        StringAlignment: Type[_gdpenums.StringAlignment]
        StringAlignmentNear: int
        StringAlignmentCenter: int
        StringAlignmentFar: int
        DriverStringOptions: Type[_gdpenums.DriverStringOptions]
        DriverStringOptionsCmapLookup: int
        DriverStringOptionsVertical: int
        DriverStringOptionsRealizedAdvance: int
        DriverStringOptionsLimitSubpixel: int
        FlushIntention: Type[_gdpenums.FlushIntention]
        FlushIntentionFlush: int
        FlushIntentionSync: int
        EncoderParameterValueType: Type[_gdpenums.EncoderParameterValueType]
        EncoderParameterValueTypeByte: int
        EncoderParameterValueTypeASCII: int
        EncoderParameterValueTypeShort: int
        EncoderParameterValueTypeLong: int
        EncoderParameterValueTypeRational: int
        EncoderParameterValueTypeLongRange: int
        EncoderParameterValueTypeUndefined: int
        EncoderParameterValueTypeRationalRange: int
        EncoderParameterValueTypePointer: int
        EncoderValue: Type[_gdpenums.EncoderValue]
        EncoderValueColorTypeCMYK: int
        EncoderValueColorTypeYCCK: int
        EncoderValueCompressionLZW: int
        EncoderValueCompressionCCITT3: int
        EncoderValueCompressionCCITT4: int
        EncoderValueCompressionRle: int
        EncoderValueCompressionNone: int
        EncoderValueScanMethodInterlaced: int
        EncoderValueScanMethodNonInterlaced: int
        EncoderValueVersionGif87: int
        EncoderValueVersionGif89: int
        EncoderValueRenderProgressive: int
        EncoderValueRenderNonProgressive: int
        EncoderValueTransformRotate90: int
        EncoderValueTransformRotate180: int
        EncoderValueTransformRotate270: int
        EncoderValueTransformFlipHorizontal: int
        EncoderValueTransformFlipVertical: int
        EncoderValueMultiFrame: int
        EncoderValueLastFrame: int
        EncoderValueFlush: int
        EncoderValueFrameDimensionTime: int
        EncoderValueFrameDimensionResolution: int
        EncoderValueFrameDimensionPage: int
        if cpreproc.getdef("GDIPVER") >= 0x0110:
            EncoderValueColorTypeGray: int
            EncoderValueColorTypeRGB: int
        EmfToWmfBitsFlags: Type[_gdpenums.EmfToWmfBitsFlags]
        EmfToWmfBitsFlagsDefault: int
        EmfToWmfBitsFlagsEmbedEmf: int
        EmfToWmfBitsFlagsIncludePlaceable: int
        EmfToWmfBitsFlagsNoXORClip: int
        if cpreproc.getdef("GDIPVER") >= 0x0110:
            ConvertToEmfPlusFlags: Type[_gdpenums.ConvertToEmfPlusFlags]
            ConvertToEmfPlusFlagsDefault: int
            ConvertToEmfPlusFlagsRopUsed: int
            ConvertToEmfPlusFlagsText: int
            ConvertToEmfPlusFlagsInvalidRecord: int
        GpTestControlEnum: Type[_gdpenums.GpTestControlEnum]
        TestControlForceBilinear: int
        TestControlNoICM: int
        TestControlGetBuildNumber: int
    # gdiplustypes.py
    ImageAbort: Type[CFuncPtr]
    DrawImageAbort: Type[CFuncPtr]
    GetThumbnailImageAbort: Type[CFuncPtr]
    EnumerateMetafileProc: Type[CFuncPtr]
    GdiplusAbort: Type[_gdptypes.GdiplusAbort]
    
    # gdiplusinit.py
    
    module_to_namespace(_gdpbase, Gdiplus)
    
    module_to_namespace(_gdpenums, Gdiplus)
    module_to_namespace(_gdptypes, Gdiplus)
    module_to_namespace(_gdpinit, Gdiplus)
    module_to_namespace(_gdppf, Gdiplus)
    module_to_namespace(_gdpcolor, Gdiplus)
    module_to_namespace(_gdpmh, Gdiplus)
    module_to_namespace(_gdpimg, Gdiplus)
    module_to_namespace(_gdpcmat, Gdiplus)

    # TODO:
    """
    #if (GDIPVER >= 0x0110)    
        #include "GdiplusEffects.h"
    #endif
        #include "GdiplusGpStubs.h"
        #include "GdiplusHeaders.h"

        namespace DllExports
        {
        #include "GdiplusFlat.h"
        };

        #include "GdiplusImageAttributes.h"
        #include "GdiplusMatrix.h"
        #include "GdiplusBrush.h"
        #include "GdiplusPen.h"
        #include "GdiplusStringFormat.h"
        #include "GdiplusPath.h"
        #include "GdiplusLineCaps.h"
        #include "GdiplusGraphics.h"
        #include "GdiplusMetafile.h"
        #include "GdiplusCachedBitmap.h"
        #include "GdiplusRegion.h"
        #include "GdiplusFontCollection.h"
        #include "GdiplusFontFamily.h"
        #include "GdiplusFont.h"
        #include "GdiplusBitmap.h"
        #include "GdiplusImageCodec.h"
    """

    # namespace Gdiplus
    
    # REGION ***

    # !_GDIPLUS_HPP
