#+-------------------------------------------------------------------------
#
#  Microsoft Windows HTTP Services (WinHTTP)
#  Copyright (C) Microsoft Corporation. All rights reserved.
#
#--------------------------------------------------------------------------

from . import cpreproc

if cpreproc.pragma_once("__HTTPREQUESTID_H__"):
    # REGION *** Desktop Family or OneCore Family ***

    DISPID_HTTPREQUEST_BASE                    = 0x00000001

    DISPID_HTTPREQUEST_OPEN                    = (DISPID_HTTPREQUEST_BASE)
    DISPID_HTTPREQUEST_SETREQUESTHEADER        = (DISPID_HTTPREQUEST_BASE + 1)
    DISPID_HTTPREQUEST_GETRESPONSEHEADER       = (DISPID_HTTPREQUEST_BASE + 2)
    DISPID_HTTPREQUEST_GETALLRESPONSEHEADERS   = (DISPID_HTTPREQUEST_BASE + 3)
    DISPID_HTTPREQUEST_SEND                    = (DISPID_HTTPREQUEST_BASE + 4)
    DISPID_HTTPREQUEST_OPTION                  = (DISPID_HTTPREQUEST_BASE + 5)
    DISPID_HTTPREQUEST_STATUS                  = (DISPID_HTTPREQUEST_BASE + 6)
    DISPID_HTTPREQUEST_STATUSTEXT              = (DISPID_HTTPREQUEST_BASE + 7)
    DISPID_HTTPREQUEST_RESPONSETEXT            = (DISPID_HTTPREQUEST_BASE + 8)
    DISPID_HTTPREQUEST_RESPONSEBODY            = (DISPID_HTTPREQUEST_BASE + 9)
    DISPID_HTTPREQUEST_RESPONSESTREAM          = (DISPID_HTTPREQUEST_BASE + 10)
    DISPID_HTTPREQUEST_ABORT                   = (DISPID_HTTPREQUEST_BASE + 11)
    DISPID_HTTPREQUEST_SETPROXY                = (DISPID_HTTPREQUEST_BASE + 12)
    DISPID_HTTPREQUEST_SETCREDENTIALS          = (DISPID_HTTPREQUEST_BASE + 13)
    DISPID_HTTPREQUEST_WAITFORRESPONSE         = (DISPID_HTTPREQUEST_BASE + 14)
    DISPID_HTTPREQUEST_SETTIMEOUTS             = (DISPID_HTTPREQUEST_BASE + 15)
    DISPID_HTTPREQUEST_SETCLIENTCERTIFICATE    = (DISPID_HTTPREQUEST_BASE + 16)
    DISPID_HTTPREQUEST_SETAUTOLOGONPOLICY      = (DISPID_HTTPREQUEST_BASE + 17)

    # REGION ***

# __HTTPREQUESTID_H__