##################
# GUID.PY
#
# Module declaring
# GUIDs, IIDs and
# CLSIDs.
##################

from typing import TYPE_CHECKING

from .. import defbase as defb

from .comdefbase import *

class GUID(CStructure):
    """
    Globally unique identifier structure.
    """

    _fields_ = [("Data1", DWORD), ("Data2", WORD), ("Data3", WORD), ("Data4", BYTE * 8)]
    
    @classmethod
    def new(cls):
        CheckCOMInitialized()
        
        guid = cls()
        hr = CoCreateGuid(guid.ref())
        if FAILED(hr): raise COMError(hr)
        
        return guid
    
    def copy(self) -> 'GUID':
        guid = GUID()
        memmove(guid.ref(), self.ref(), self.size())
        return guid
    
    def __repr__(self) -> str:
        return f'<GUID {str(self)}>'
    
    def __str__(self) -> str:
        CheckCOMInitialized()
        
        szGUID = create_unicode_buffer(39) # 32 GUID characters, 4 dashes, 2 curly braces and 1 zero-terminator
        hr = StringFromGUID2(self, szGUID, 39)
        if FAILED(hr): raise COMError(hr)
        
        return szGUID.value
    
    def __bool__(self) -> bool:
        return self != GUID_NULL
    
    def __eq__(self, other: 'GUID') -> bool: 
        if not isinstance(other, GUID):
            return NotImplemented
        
        return IsEqualGUID(self, other)
    
GUID_NULL = GUID()
REFGUID = PGUID = LPCGUID = LPGUID = GUID.PTR()
    
# GUID functions
@ole32.foreign(BOOL, REFGUID, REFGUID, result_function=bool, intermediate_method=True)
def IsEqualGUID(guid1: GUID, guid2: GUID, **kwargs) -> bool: 
    """
    Determines whether two GUIDs are equal.
    """
    return delegate(guid1.ref(), guid2.ref())
    
@ole_foreign(PGUID)
def CoCreateGuid(pguid: IPointer[GUID]) -> int: 
    """
    Creates a GUID, a unique 128-bit integer used for CLSIDs and interface identifiers.
    """
    
@ole_foreign(REFGUID, LPOLESTR, INT, intermediate_method=True)
def StringFromGUID2(guid: GUID, lpsz: LPOLESTR, cchMax: int, **kwargs) -> int:
    """
    Converts a globally unique identifier (GUID) into a string of printable characters.
    """
    
    return delegate(guid.ref(), lpsz, cchMax)
    
class CLSID(GUID):
    """
    Class identifier structure.
    """
    
    @overload
    def __init__(self, clsid: str): ...
    
    @overload
    def __init__(self, progID: str): ...
    
    def __init__(self, value: str = None):
        if value is not None:
            CheckCOMInitialized()
            
            if value.startswith('{'):
                hr = CLSIDFromString(value, self.ref())
            else:
                hr = CLSIDFromProgID(value, self.ref())
            
            if FAILED(hr): raise COMError(hr)
                
    def __str__(self) -> str:
        CheckCOMInitialized()
        
        lpsz = LPOLESTR()
        
        hr = StringFromCLSID(self, byref(lpsz))
        if FAILED(hr): raise COMError(hr)
        
        result: str = lpsz.value
        CoTaskMemFree(lpsz)
        
        return result
    
    @property
    def progid(self) -> str:
        CheckCOMInitialized()
        
        lpsz = LPOLESTR()
        
        hr = ProgIDFromCLSID(self, byref(lpsz))
        if FAILED(hr): raise COMError(hr)
        
        result: str = lpsz.value
        CoTaskMemFree(lpsz)
        
        return result
    
    @classmethod
    def from_param(cls, value):
        unknwn = getattr(defb._defb_state, '_unknwn', None)
        if unknwn is None:
            from . import unknwn
            defb._defb_state._unknwn = unknwn
            
        if isinstance(value, type) and issubclass(value, unknwn.COMClass):
            com_class: type[COMClass] = value
            return com_class._clsid_
            
        return value
    
class REFCLSID(CLSID.PTR()):
    @classmethod
    def from_param(cls, value):
        unknwn = getattr(defb._defb_state, '_unknwn', None)
        if unknwn is None:
            from . import unknwn
            defb._defb_state._unknwn = unknwn
            
        if isinstance(value, type) and issubclass(value, unknwn.COMClass):
            com_class: type[COMClass] = value
            return com_class._clsid_.ptr()
            
        return value
    
PCLSID = LPCCLSID = LPCLSID = REFCLSID
CLSID_NULL = CLSID()
    
# CLSID Functions
@ole_foreign(LPCOLESTR, LPCLSID)
def CLSIDFromProgID(lpszProgId: str, lpclsid: IPointer[CLSID]) -> int: 
    """
    Looks up a CLSID in the registry, given a ProgID.
    """
    
@ole_foreign(LPCOLESTR, LPCLSID)
def CLSIDFromString(lpsz: str, pclsid: IPointer[CLSID]) -> int: 
    """
    Converts a string generated by the `StringFromCLSID` function back into the original CLSID.
    """
    
@ole_foreign(REFCLSID, POINTER(LPOLESTR), intermediate_method=True)
def StringFromCLSID(clsid: CLSID, lplpsz: IPointer[LPOLESTR], **kwargs) -> int:
    """
    Converts a CLSID into a string of printable characters. Different CLSIDs always convert to different strings.
    """
    return delegate(clsid.ref(), lplpsz)

@ole_foreign(REFCLSID, POINTER(LPOLESTR), intermediate_method=True)
def ProgIDFromCLSID(clsid: CLSID, lplpsz: IPointer[LPOLESTR], **kwargs) -> int:
    """
    Retrieves the ProgID for a given CLSID.
    """
    return delegate(clsid.ref(), lplpsz)

class IID(GUID):
    """
    Interface identifier structure.
    """
    
    def __init__(self, iid: str = None):
        if iid is not None:
            CheckCOMInitialized()
            
            hr = IIDFromString(iid, self.ref())
            if FAILED(hr): raise COMError(hr)
    
    def __str__(self) -> str: 
        CheckCOMInitialized()
        lpsz = LPOLESTR()
        
        hr = StringFromIID(self, byref(lpsz))
        if FAILED(hr): raise COMError(hr)
        
        result: str = lpsz.value
        CoTaskMemFree(lpsz)
        
        return result
    
    @classmethod
    def from_param(cls, value):
        interfacedef = getattr(defb._defb_state, '_interfacedef', None)
        if interfacedef is None:
            from . import interfacedef
            defb._defb_state._interfacedef = interfacedef
            
        if isinstance(value, type) and issubclass(value, interfacedef.COMInterface):
            com_interface: type[COMInterface] = value
            return com_interface._iid_
            
        return super().from_param(value)
    
class REFIID(IID.PTR()):
    @classmethod
    def from_param(cls, value):
        interfacedef = getattr(defb._defb_state, '_interfacedef', None)
        if interfacedef is None:
            from . import interfacedef
            defb._defb_state._interfacedef = interfacedef
            
        if isinstance(value, type) and issubclass(value, interfacedef.COMInterface):
            com_class: type[COMInterface] = value
            return com_class._iid_.ptr()
            
        return value
    
PIID = LPCIID = LPIID = REFIID
IID_NULL = IID()
        
@ole_foreign(LPCOLESTR, LPIID)
def IIDFromString(lpsz: str, lpiid: IPointer[IID]) -> int: 
    """
    Converts a string generated by the `StringFromIID` function back into the original interface identifier (IID).
    """
        
@ole_foreign(REFIID, POINTER(LPOLESTR), intermediate_method=True)
def StringFromIID(clsid: CLSID, lplpsz: IPointer[LPOLESTR], **kwargs) -> int:
    """
    Converts an interface identifier into a string of printable characters.
    """
    return delegate(clsid.ref(), lplpsz)

if TYPE_CHECKING:
    from .interfacedef import COMInterface
    from .unknwn import COMClass