#
# This file generated by a Win.Tools.GLGen generator as a part of the Win project.
# Definitions for the OpenGL gl_1.0, do not change this file
# Date/Time of a generation: Thu Aug 27 21:13:35 2026
#

# OpenGL Imports
from win.gl.gl import *
from win.gl.glu import *
from win.abs.glext import *

# Basic OpenGL Types definitions
khronos_int8_t = GLbyte
khronos_uint8_t = GLubyte
khronos_int16_t = GLshort
khornos_uint16_t = GLushort
GLclampx = UINT32
GLeglClientBufferEXT = PVOID
GLeglImageOES = PVOID
GLchar = CHAR
GLcharARB = CHAR
GLhandleARB = UINT
GLhalf = UINT16
GLhalfARB = UINT16
GLfixed = INT32
GLintptr = INT_PTR
GLintptrARB = INT_PTR
GLsizeiptr = SSIZE_T
GLsizeiptrARB = SSIZE_T
GLint64 = INT64
GLint64EXT = INT64
GLuint64 = UINT64
GLuint64EXT = UINT64
GLsync = PVOID
GLDEBUGPROC = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCARB = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCKHR = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCAMD = APIENTRY(VOID, GLuint, GLenum, GLenum, GLsizei, LPSTR, PVOID)
GLhalfNV = USHORT
GLvdpauSurfaceNV = GLintptr
GLVULKANPROCNV = APIENTRY(VOID)

class GL10:
    #
    # Enum definitions
    #

    GL_DEPTH_BUFFER_BIT = 0x00000100
    GL_STENCIL_BUFFER_BIT = 0x00000400
    GL_COLOR_BUFFER_BIT = 0x00004000
    GL_FALSE = 0
    GL_TRUE = 1
    GL_POINTS = 0x0000
    GL_LINES = 0x0001
    GL_LINE_LOOP = 0x0002
    GL_LINE_STRIP = 0x0003
    GL_TRIANGLES = 0x0004
    GL_TRIANGLE_STRIP = 0x0005
    GL_TRIANGLE_FAN = 0x0006
    GL_QUADS = 0x0007
    GL_NEVER = 0x0200
    GL_LESS = 0x0201
    GL_EQUAL = 0x0202
    GL_LEQUAL = 0x0203
    GL_GREATER = 0x0204
    GL_NOTEQUAL = 0x0205
    GL_GEQUAL = 0x0206
    GL_ALWAYS = 0x0207
    GL_ZERO = 0
    GL_ONE = 1
    GL_SRC_COLOR = 0x0300
    GL_ONE_MINUS_SRC_COLOR = 0x0301
    GL_SRC_ALPHA = 0x0302
    GL_ONE_MINUS_SRC_ALPHA = 0x0303
    GL_DST_ALPHA = 0x0304
    GL_ONE_MINUS_DST_ALPHA = 0x0305
    GL_DST_COLOR = 0x0306
    GL_ONE_MINUS_DST_COLOR = 0x0307
    GL_SRC_ALPHA_SATURATE = 0x0308
    GL_NONE = 0
    GL_FRONT_LEFT = 0x0400
    GL_FRONT_RIGHT = 0x0401
    GL_BACK_LEFT = 0x0402
    GL_BACK_RIGHT = 0x0403
    GL_FRONT = 0x0404
    GL_BACK = 0x0405
    GL_LEFT = 0x0406
    GL_RIGHT = 0x0407
    GL_FRONT_AND_BACK = 0x0408
    GL_NO_ERROR = 0
    GL_INVALID_ENUM = 0x0500
    GL_INVALID_VALUE = 0x0501
    GL_INVALID_OPERATION = 0x0502
    GL_OUT_OF_MEMORY = 0x0505
    GL_CW = 0x0900
    GL_CCW = 0x0901
    GL_POINT_SIZE = 0x0B11
    GL_POINT_SIZE_RANGE = 0x0B12
    GL_POINT_SIZE_GRANULARITY = 0x0B13
    GL_LINE_SMOOTH = 0x0B20
    GL_LINE_WIDTH = 0x0B21
    GL_LINE_WIDTH_RANGE = 0x0B22
    GL_LINE_WIDTH_GRANULARITY = 0x0B23
    GL_POLYGON_MODE = 0x0B40
    GL_POLYGON_SMOOTH = 0x0B41
    GL_CULL_FACE = 0x0B44
    GL_CULL_FACE_MODE = 0x0B45
    GL_FRONT_FACE = 0x0B46
    GL_DEPTH_RANGE = 0x0B70
    GL_DEPTH_TEST = 0x0B71
    GL_DEPTH_WRITEMASK = 0x0B72
    GL_DEPTH_CLEAR_VALUE = 0x0B73
    GL_DEPTH_FUNC = 0x0B74
    GL_STENCIL_TEST = 0x0B90
    GL_STENCIL_CLEAR_VALUE = 0x0B91
    GL_STENCIL_FUNC = 0x0B92
    GL_STENCIL_VALUE_MASK = 0x0B93
    GL_STENCIL_FAIL = 0x0B94
    GL_STENCIL_PASS_DEPTH_FAIL = 0x0B95
    GL_STENCIL_PASS_DEPTH_PASS = 0x0B96
    GL_STENCIL_REF = 0x0B97
    GL_STENCIL_WRITEMASK = 0x0B98
    GL_VIEWPORT = 0x0BA2
    GL_DITHER = 0x0BD0
    GL_BLEND_DST = 0x0BE0
    GL_BLEND_SRC = 0x0BE1
    GL_BLEND = 0x0BE2
    GL_LOGIC_OP_MODE = 0x0BF0
    GL_DRAW_BUFFER = 0x0C01
    GL_READ_BUFFER = 0x0C02
    GL_SCISSOR_BOX = 0x0C10
    GL_SCISSOR_TEST = 0x0C11
    GL_COLOR_CLEAR_VALUE = 0x0C22
    GL_COLOR_WRITEMASK = 0x0C23
    GL_DOUBLEBUFFER = 0x0C32
    GL_STEREO = 0x0C33
    GL_LINE_SMOOTH_HINT = 0x0C52
    GL_POLYGON_SMOOTH_HINT = 0x0C53
    GL_UNPACK_SWAP_BYTES = 0x0CF0
    GL_UNPACK_LSB_FIRST = 0x0CF1
    GL_UNPACK_ROW_LENGTH = 0x0CF2
    GL_UNPACK_SKIP_ROWS = 0x0CF3
    GL_UNPACK_SKIP_PIXELS = 0x0CF4
    GL_UNPACK_ALIGNMENT = 0x0CF5
    GL_PACK_SWAP_BYTES = 0x0D00
    GL_PACK_LSB_FIRST = 0x0D01
    GL_PACK_ROW_LENGTH = 0x0D02
    GL_PACK_SKIP_ROWS = 0x0D03
    GL_PACK_SKIP_PIXELS = 0x0D04
    GL_PACK_ALIGNMENT = 0x0D05
    GL_MAX_TEXTURE_SIZE = 0x0D33
    GL_MAX_VIEWPORT_DIMS = 0x0D3A
    GL_SUBPIXEL_BITS = 0x0D50
    GL_TEXTURE_1D = 0x0DE0
    GL_TEXTURE_2D = 0x0DE1
    GL_TEXTURE_WIDTH = 0x1000
    GL_TEXTURE_HEIGHT = 0x1001
    GL_TEXTURE_BORDER_COLOR = 0x1004
    GL_DONT_CARE = 0x1100
    GL_FASTEST = 0x1101
    GL_NICEST = 0x1102
    GL_BYTE = 0x1400
    GL_UNSIGNED_BYTE = 0x1401
    GL_SHORT = 0x1402
    GL_UNSIGNED_SHORT = 0x1403
    GL_INT = 0x1404
    GL_UNSIGNED_INT = 0x1405
    GL_FLOAT = 0x1406
    GL_STACK_OVERFLOW = 0x0503
    GL_STACK_UNDERFLOW = 0x0504
    GL_CLEAR = 0x1500
    GL_AND = 0x1501
    GL_AND_REVERSE = 0x1502
    GL_COPY = 0x1503
    GL_AND_INVERTED = 0x1504
    GL_NOOP = 0x1505
    GL_XOR = 0x1506
    GL_OR = 0x1507
    GL_NOR = 0x1508
    GL_EQUIV = 0x1509
    GL_INVERT = 0x150A
    GL_OR_REVERSE = 0x150B
    GL_COPY_INVERTED = 0x150C
    GL_OR_INVERTED = 0x150D
    GL_NAND = 0x150E
    GL_SET = 0x150F
    GL_TEXTURE = 0x1702
    GL_COLOR = 0x1800
    GL_DEPTH = 0x1801
    GL_STENCIL = 0x1802
    GL_STENCIL_INDEX = 0x1901
    GL_DEPTH_COMPONENT = 0x1902
    GL_RED = 0x1903
    GL_GREEN = 0x1904
    GL_BLUE = 0x1905
    GL_ALPHA = 0x1906
    GL_RGB = 0x1907
    GL_RGBA = 0x1908
    GL_POINT = 0x1B00
    GL_LINE = 0x1B01
    GL_FILL = 0x1B02
    GL_KEEP = 0x1E00
    GL_REPLACE = 0x1E01
    GL_INCR = 0x1E02
    GL_DECR = 0x1E03
    GL_VENDOR = 0x1F00
    GL_RENDERER = 0x1F01
    GL_VERSION = 0x1F02
    GL_EXTENSIONS = 0x1F03
    GL_NEAREST = 0x2600
    GL_LINEAR = 0x2601
    GL_NEAREST_MIPMAP_NEAREST = 0x2700
    GL_LINEAR_MIPMAP_NEAREST = 0x2701
    GL_NEAREST_MIPMAP_LINEAR = 0x2702
    GL_LINEAR_MIPMAP_LINEAR = 0x2703
    GL_TEXTURE_MAG_FILTER = 0x2800
    GL_TEXTURE_MIN_FILTER = 0x2801
    GL_TEXTURE_WRAP_S = 0x2802
    GL_TEXTURE_WRAP_T = 0x2803
    GL_REPEAT = 0x2901
    GL_CURRENT_BIT = 0x00000001
    GL_POINT_BIT = 0x00000002
    GL_LINE_BIT = 0x00000004
    GL_POLYGON_BIT = 0x00000008
    GL_POLYGON_STIPPLE_BIT = 0x00000010
    GL_PIXEL_MODE_BIT = 0x00000020
    GL_LIGHTING_BIT = 0x00000040
    GL_FOG_BIT = 0x00000080
    GL_ACCUM_BUFFER_BIT = 0x00000200
    GL_VIEWPORT_BIT = 0x00000800
    GL_TRANSFORM_BIT = 0x00001000
    GL_ENABLE_BIT = 0x00002000
    GL_HINT_BIT = 0x00008000
    GL_EVAL_BIT = 0x00010000
    GL_LIST_BIT = 0x00020000
    GL_TEXTURE_BIT = 0x00040000
    GL_SCISSOR_BIT = 0x00080000
    GL_ALL_ATTRIB_BITS = 0xFFFFFFFF
    GL_QUAD_STRIP = 0x0008
    GL_POLYGON = 0x0009
    GL_ACCUM = 0x0100
    GL_LOAD = 0x0101
    GL_RETURN = 0x0102
    GL_MULT = 0x0103
    GL_ADD = 0x0104
    GL_AUX0 = 0x0409
    GL_AUX1 = 0x040A
    GL_AUX2 = 0x040B
    GL_AUX3 = 0x040C
    GL_2D = 0x0600
    GL_3D = 0x0601
    GL_3D_COLOR = 0x0602
    GL_3D_COLOR_TEXTURE = 0x0603
    GL_4D_COLOR_TEXTURE = 0x0604
    GL_PASS_THROUGH_TOKEN = 0x0700
    GL_POINT_TOKEN = 0x0701
    GL_LINE_TOKEN = 0x0702
    GL_POLYGON_TOKEN = 0x0703
    GL_BITMAP_TOKEN = 0x0704
    GL_DRAW_PIXEL_TOKEN = 0x0705
    GL_COPY_PIXEL_TOKEN = 0x0706
    GL_LINE_RESET_TOKEN = 0x0707
    GL_EXP = 0x0800
    GL_EXP2 = 0x0801
    GL_COEFF = 0x0A00
    GL_ORDER = 0x0A01
    GL_DOMAIN = 0x0A02
    GL_PIXEL_MAP_I_TO_I = 0x0C70
    GL_PIXEL_MAP_S_TO_S = 0x0C71
    GL_PIXEL_MAP_I_TO_R = 0x0C72
    GL_PIXEL_MAP_I_TO_G = 0x0C73
    GL_PIXEL_MAP_I_TO_B = 0x0C74
    GL_PIXEL_MAP_I_TO_A = 0x0C75
    GL_PIXEL_MAP_R_TO_R = 0x0C76
    GL_PIXEL_MAP_G_TO_G = 0x0C77
    GL_PIXEL_MAP_B_TO_B = 0x0C78
    GL_PIXEL_MAP_A_TO_A = 0x0C79
    GL_CURRENT_COLOR = 0x0B00
    GL_CURRENT_INDEX = 0x0B01
    GL_CURRENT_NORMAL = 0x0B02
    GL_CURRENT_TEXTURE_COORDS = 0x0B03
    GL_CURRENT_RASTER_COLOR = 0x0B04
    GL_CURRENT_RASTER_INDEX = 0x0B05
    GL_CURRENT_RASTER_TEXTURE_COORDS = 0x0B06
    GL_CURRENT_RASTER_POSITION = 0x0B07
    GL_CURRENT_RASTER_POSITION_VALID = 0x0B08
    GL_CURRENT_RASTER_DISTANCE = 0x0B09
    GL_POINT_SMOOTH = 0x0B10
    GL_LINE_STIPPLE = 0x0B24
    GL_LINE_STIPPLE_PATTERN = 0x0B25
    GL_LINE_STIPPLE_REPEAT = 0x0B26
    GL_LIST_MODE = 0x0B30
    GL_MAX_LIST_NESTING = 0x0B31
    GL_LIST_BASE = 0x0B32
    GL_LIST_INDEX = 0x0B33
    GL_POLYGON_STIPPLE = 0x0B42
    GL_EDGE_FLAG = 0x0B43
    GL_LIGHTING = 0x0B50
    GL_LIGHT_MODEL_LOCAL_VIEWER = 0x0B51
    GL_LIGHT_MODEL_TWO_SIDE = 0x0B52
    GL_LIGHT_MODEL_AMBIENT = 0x0B53
    GL_SHADE_MODEL = 0x0B54
    GL_COLOR_MATERIAL_FACE = 0x0B55
    GL_COLOR_MATERIAL_PARAMETER = 0x0B56
    GL_COLOR_MATERIAL = 0x0B57
    GL_FOG = 0x0B60
    GL_FOG_INDEX = 0x0B61
    GL_FOG_DENSITY = 0x0B62
    GL_FOG_START = 0x0B63
    GL_FOG_END = 0x0B64
    GL_FOG_MODE = 0x0B65
    GL_FOG_COLOR = 0x0B66
    GL_ACCUM_CLEAR_VALUE = 0x0B80
    GL_MATRIX_MODE = 0x0BA0
    GL_NORMALIZE = 0x0BA1
    GL_MODELVIEW_STACK_DEPTH = 0x0BA3
    GL_PROJECTION_STACK_DEPTH = 0x0BA4
    GL_TEXTURE_STACK_DEPTH = 0x0BA5
    GL_MODELVIEW_MATRIX = 0x0BA6
    GL_PROJECTION_MATRIX = 0x0BA7
    GL_TEXTURE_MATRIX = 0x0BA8
    GL_ATTRIB_STACK_DEPTH = 0x0BB0
    GL_ALPHA_TEST = 0x0BC0
    GL_ALPHA_TEST_FUNC = 0x0BC1
    GL_ALPHA_TEST_REF = 0x0BC2
    GL_LOGIC_OP = 0x0BF1
    GL_AUX_BUFFERS = 0x0C00
    GL_INDEX_CLEAR_VALUE = 0x0C20
    GL_INDEX_WRITEMASK = 0x0C21
    GL_INDEX_MODE = 0x0C30
    GL_RGBA_MODE = 0x0C31
    GL_RENDER_MODE = 0x0C40
    GL_PERSPECTIVE_CORRECTION_HINT = 0x0C50
    GL_POINT_SMOOTH_HINT = 0x0C51
    GL_FOG_HINT = 0x0C54
    GL_TEXTURE_GEN_S = 0x0C60
    GL_TEXTURE_GEN_T = 0x0C61
    GL_TEXTURE_GEN_R = 0x0C62
    GL_TEXTURE_GEN_Q = 0x0C63
    GL_PIXEL_MAP_I_TO_I_SIZE = 0x0CB0
    GL_PIXEL_MAP_S_TO_S_SIZE = 0x0CB1
    GL_PIXEL_MAP_I_TO_R_SIZE = 0x0CB2
    GL_PIXEL_MAP_I_TO_G_SIZE = 0x0CB3
    GL_PIXEL_MAP_I_TO_B_SIZE = 0x0CB4
    GL_PIXEL_MAP_I_TO_A_SIZE = 0x0CB5
    GL_PIXEL_MAP_R_TO_R_SIZE = 0x0CB6
    GL_PIXEL_MAP_G_TO_G_SIZE = 0x0CB7
    GL_PIXEL_MAP_B_TO_B_SIZE = 0x0CB8
    GL_PIXEL_MAP_A_TO_A_SIZE = 0x0CB9
    GL_MAP_COLOR = 0x0D10
    GL_MAP_STENCIL = 0x0D11
    GL_INDEX_SHIFT = 0x0D12
    GL_INDEX_OFFSET = 0x0D13
    GL_RED_SCALE = 0x0D14
    GL_RED_BIAS = 0x0D15
    GL_ZOOM_X = 0x0D16
    GL_ZOOM_Y = 0x0D17
    GL_GREEN_SCALE = 0x0D18
    GL_GREEN_BIAS = 0x0D19
    GL_BLUE_SCALE = 0x0D1A
    GL_BLUE_BIAS = 0x0D1B
    GL_ALPHA_SCALE = 0x0D1C
    GL_ALPHA_BIAS = 0x0D1D
    GL_DEPTH_SCALE = 0x0D1E
    GL_DEPTH_BIAS = 0x0D1F
    GL_MAX_EVAL_ORDER = 0x0D30
    GL_MAX_LIGHTS = 0x0D31
    GL_MAX_CLIP_PLANES = 0x0D32
    GL_MAX_PIXEL_MAP_TABLE = 0x0D34
    GL_MAX_ATTRIB_STACK_DEPTH = 0x0D35
    GL_MAX_MODELVIEW_STACK_DEPTH = 0x0D36
    GL_MAX_NAME_STACK_DEPTH = 0x0D37
    GL_MAX_PROJECTION_STACK_DEPTH = 0x0D38
    GL_MAX_TEXTURE_STACK_DEPTH = 0x0D39
    GL_INDEX_BITS = 0x0D51
    GL_RED_BITS = 0x0D52
    GL_GREEN_BITS = 0x0D53
    GL_BLUE_BITS = 0x0D54
    GL_ALPHA_BITS = 0x0D55
    GL_DEPTH_BITS = 0x0D56
    GL_STENCIL_BITS = 0x0D57
    GL_ACCUM_RED_BITS = 0x0D58
    GL_ACCUM_GREEN_BITS = 0x0D59
    GL_ACCUM_BLUE_BITS = 0x0D5A
    GL_ACCUM_ALPHA_BITS = 0x0D5B
    GL_NAME_STACK_DEPTH = 0x0D70
    GL_AUTO_NORMAL = 0x0D80
    GL_MAP1_COLOR_4 = 0x0D90
    GL_MAP1_INDEX = 0x0D91
    GL_MAP1_NORMAL = 0x0D92
    GL_MAP1_TEXTURE_COORD_1 = 0x0D93
    GL_MAP1_TEXTURE_COORD_2 = 0x0D94
    GL_MAP1_TEXTURE_COORD_3 = 0x0D95
    GL_MAP1_TEXTURE_COORD_4 = 0x0D96
    GL_MAP1_VERTEX_3 = 0x0D97
    GL_MAP1_VERTEX_4 = 0x0D98
    GL_MAP2_COLOR_4 = 0x0DB0
    GL_MAP2_INDEX = 0x0DB1
    GL_MAP2_NORMAL = 0x0DB2
    GL_MAP2_TEXTURE_COORD_1 = 0x0DB3
    GL_MAP2_TEXTURE_COORD_2 = 0x0DB4
    GL_MAP2_TEXTURE_COORD_3 = 0x0DB5
    GL_MAP2_TEXTURE_COORD_4 = 0x0DB6
    GL_MAP2_VERTEX_3 = 0x0DB7
    GL_MAP2_VERTEX_4 = 0x0DB8
    GL_MAP1_GRID_DOMAIN = 0x0DD0
    GL_MAP1_GRID_SEGMENTS = 0x0DD1
    GL_MAP2_GRID_DOMAIN = 0x0DD2
    GL_MAP2_GRID_SEGMENTS = 0x0DD3
    GL_TEXTURE_COMPONENTS = 0x1003
    GL_TEXTURE_BORDER = 0x1005
    GL_AMBIENT = 0x1200
    GL_DIFFUSE = 0x1201
    GL_SPECULAR = 0x1202
    GL_POSITION = 0x1203
    GL_SPOT_DIRECTION = 0x1204
    GL_SPOT_EXPONENT = 0x1205
    GL_SPOT_CUTOFF = 0x1206
    GL_CONSTANT_ATTENUATION = 0x1207
    GL_LINEAR_ATTENUATION = 0x1208
    GL_QUADRATIC_ATTENUATION = 0x1209
    GL_COMPILE = 0x1300
    GL_COMPILE_AND_EXECUTE = 0x1301
    GL_2_BYTES = 0x1407
    GL_3_BYTES = 0x1408
    GL_4_BYTES = 0x1409
    GL_EMISSION = 0x1600
    GL_SHININESS = 0x1601
    GL_AMBIENT_AND_DIFFUSE = 0x1602
    GL_COLOR_INDEXES = 0x1603
    GL_MODELVIEW = 0x1700
    GL_PROJECTION = 0x1701
    GL_COLOR_INDEX = 0x1900
    GL_LUMINANCE = 0x1909
    GL_LUMINANCE_ALPHA = 0x190A
    GL_BITMAP = 0x1A00
    GL_RENDER = 0x1C00
    GL_FEEDBACK = 0x1C01
    GL_SELECT = 0x1C02
    GL_FLAT = 0x1D00
    GL_SMOOTH = 0x1D01
    GL_S = 0x2000
    GL_T = 0x2001
    GL_R = 0x2002
    GL_Q = 0x2003
    GL_MODULATE = 0x2100
    GL_DECAL = 0x2101
    GL_TEXTURE_ENV_MODE = 0x2200
    GL_TEXTURE_ENV_COLOR = 0x2201
    GL_TEXTURE_ENV = 0x2300
    GL_EYE_LINEAR = 0x2400
    GL_OBJECT_LINEAR = 0x2401
    GL_SPHERE_MAP = 0x2402
    GL_TEXTURE_GEN_MODE = 0x2500
    GL_OBJECT_PLANE = 0x2501
    GL_EYE_PLANE = 0x2502
    GL_CLAMP = 0x2900
    GL_CLIP_PLANE0 = 0x3000
    GL_CLIP_PLANE1 = 0x3001
    GL_CLIP_PLANE2 = 0x3002
    GL_CLIP_PLANE3 = 0x3003
    GL_CLIP_PLANE4 = 0x3004
    GL_CLIP_PLANE5 = 0x3005
    GL_LIGHT0 = 0x4000
    GL_LIGHT1 = 0x4001
    GL_LIGHT2 = 0x4002
    GL_LIGHT3 = 0x4003
    GL_LIGHT4 = 0x4004
    GL_LIGHT5 = 0x4005
    GL_LIGHT6 = 0x4006
    GL_LIGHT7 = 0x4007

    #
    # Function/Command definitions
    #

    @opengl32.foreign(VOID, GLenum)
    def glCullFace(mode: int) -> None: pass

    @opengl32.foreign(VOID, GLenum)
    def glFrontFace(mode: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum)
    def glHint(target: int, mode: int) -> None: pass

    @opengl32.foreign(VOID, GLfloat)
    def glLineWidth(width: float) -> None: pass

    @opengl32.foreign(VOID, GLfloat)
    def glPointSize(size: float) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum)
    def glPolygonMode(face: int, mode: int) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint, GLsizei, GLsizei)
    def glScissor(x: int, y: int, width: int, height: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, GLfloat)
    def glTexParameterf(target: int, pname: int, param: float) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLfloat))
    def glTexParameterfv(target: int, pname: int, params: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, GLint)
    def glTexParameteri(target: int, pname: int, param: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLint))
    def glTexParameteriv(target: int, pname: int, params: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLint, GLint, GLsizei, GLint, GLenum, GLenum, PTR(VOID))
    def glTexImage1D(target: int, level: int, internalformat: int, width: int, border: int, format: int, type: int, pixels: IPointer[int]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLint, GLint, GLsizei, GLsizei, GLint, GLenum, GLenum, PTR(VOID))
    def glTexImage2D(target: int, level: int, internalformat: int, width: int, height: int, border: int, format: int, type: int, pixels: IPointer[int]) -> None: pass

    @opengl32.foreign(VOID, GLenum)
    def glDrawBuffer(buf: int) -> None: pass

    @opengl32.foreign(VOID, GLbitfield)
    def glClear(mask: int) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat, GLfloat, GLfloat)
    def glClearColor(red: float, green: float, blue: float, alpha: float) -> None: pass

    @opengl32.foreign(VOID, GLint)
    def glClearStencil(s: int) -> None: pass

    @opengl32.foreign(VOID, GLdouble)
    def glClearDepth(depth: float) -> None: pass

    @opengl32.foreign(VOID, GLuint)
    def glStencilMask(mask: int) -> None: pass

    @opengl32.foreign(VOID, GLboolean, GLboolean, GLboolean, GLboolean)
    def glColorMask(red: int, green: int, blue: int, alpha: int) -> None: pass

    @opengl32.foreign(VOID, GLboolean)
    def glDepthMask(flag: int) -> None: pass

    @opengl32.foreign(VOID, GLenum)
    def glDisable(cap: int) -> None: pass

    @opengl32.foreign(VOID, GLenum)
    def glEnable(cap: int) -> None: pass

    @opengl32.foreign(VOID, )
    def glFinish() -> None: pass

    @opengl32.foreign(VOID, )
    def glFlush() -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum)
    def glBlendFunc(sfactor: int, dfactor: int) -> None: pass

    @opengl32.foreign(VOID, GLenum)
    def glLogicOp(opcode: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLint, GLuint)
    def glStencilFunc(func: int, ref: int, mask: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, GLenum)
    def glStencilOp(fail: int, zfail: int, zpass: int) -> None: pass

    @opengl32.foreign(VOID, GLenum)
    def glDepthFunc(func: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLfloat)
    def glPixelStoref(pname: int, param: float) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLint)
    def glPixelStorei(pname: int, param: int) -> None: pass

    @opengl32.foreign(VOID, GLenum)
    def glReadBuffer(src: int) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, PTR(VOID))
    def glReadPixels(x: int, y: int, width: int, height: int, format: int, type: int, pixels: IPointer[int]) -> None: pass

    @opengl32.foreign(VOID, GLenum, PTR(GLboolean))
    def glGetBooleanv(pname: int, data: IPointer[GLboolean]) -> None: pass

    @opengl32.foreign(VOID, GLenum, PTR(GLdouble))
    def glGetDoublev(pname: int, data: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(GLenum, )
    def glGetError() -> int: pass

    @opengl32.foreign(VOID, GLenum, PTR(GLfloat))
    def glGetFloatv(pname: int, data: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, PTR(GLint))
    def glGetIntegerv(pname: int, data: IPointer[GLint]) -> None: pass

    @opengl32.foreign(LPSTR, GLenum)
    def glGetString(name: int) -> LPSTR: pass

    @opengl32.foreign(VOID, GLenum, GLint, GLenum, GLenum, PTR(VOID))
    def glGetTexImage(target: int, level: int, format: int, type: int, pixels: IPointer[int]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLfloat))
    def glGetTexParameterfv(target: int, pname: int, params: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLint))
    def glGetTexParameteriv(target: int, pname: int, params: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLint, GLenum, PTR(GLfloat))
    def glGetTexLevelParameterfv(target: int, level: int, pname: int, params: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLint, GLenum, PTR(GLint))
    def glGetTexLevelParameteriv(target: int, level: int, pname: int, params: IPointer[GLint]) -> None: pass

    @opengl32.foreign(GLboolean, GLenum)
    def glIsEnabled(cap: int) -> int: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble)
    def glDepthRange(n: float, f: float) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint, GLsizei, GLsizei)
    def glViewport(x: int, y: int, width: int, height: int) -> None: pass

    @opengl32.foreign(VOID, GLuint, GLenum)
    def glNewList(list: int, mode: int) -> None: pass

    @opengl32.foreign(VOID, )
    def glEndList() -> None: pass

    @opengl32.foreign(VOID, GLuint)
    def glCallList(list: int) -> None: pass

    @opengl32.foreign(VOID, GLsizei, GLenum, PTR(VOID))
    def glCallLists(n: int, type: int, lists: IPointer[int]) -> None: pass

    @opengl32.foreign(VOID, GLuint, GLsizei)
    def glDeleteLists(list: int, range: int) -> None: pass

    @opengl32.foreign(GLuint, GLsizei)
    def glGenLists(range: int) -> int: pass

    @opengl32.foreign(VOID, GLuint)
    def glListBase(base: int) -> None: pass

    @opengl32.foreign(VOID, GLenum)
    def glBegin(mode: int) -> None: pass

    @opengl32.foreign(VOID, GLsizei, GLsizei, GLfloat, GLfloat, GLfloat, GLfloat, PTR(GLubyte))
    def glBitmap(width: int, height: int, xorig: float, yorig: float, xmove: float, ymove: float, bitmap: IPointer[GLubyte]) -> None: pass

    @opengl32.foreign(VOID, GLbyte, GLbyte, GLbyte)
    def glColor3b(red: int, green: int, blue: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLbyte))
    def glColor3bv(v: IPointer[GLbyte]) -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble, GLdouble)
    def glColor3d(red: float, green: float, blue: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glColor3dv(v: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat, GLfloat)
    def glColor3f(red: float, green: float, blue: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glColor3fv(v: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint, GLint)
    def glColor3i(red: int, green: int, blue: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLint))
    def glColor3iv(v: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLshort, GLshort, GLshort)
    def glColor3s(red: int, green: int, blue: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLshort))
    def glColor3sv(v: IPointer[GLshort]) -> None: pass

    @opengl32.foreign(VOID, GLubyte, GLubyte, GLubyte)
    def glColor3ub(red: int, green: int, blue: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLubyte))
    def glColor3ubv(v: IPointer[GLubyte]) -> None: pass

    @opengl32.foreign(VOID, GLuint, GLuint, GLuint)
    def glColor3ui(red: int, green: int, blue: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLuint))
    def glColor3uiv(v: IPointer[GLuint]) -> None: pass

    @opengl32.foreign(VOID, GLushort, GLushort, GLushort)
    def glColor3us(red: int, green: int, blue: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLushort))
    def glColor3usv(v: IPointer[GLushort]) -> None: pass

    @opengl32.foreign(VOID, GLbyte, GLbyte, GLbyte, GLbyte)
    def glColor4b(red: int, green: int, blue: int, alpha: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLbyte))
    def glColor4bv(v: IPointer[GLbyte]) -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble, GLdouble, GLdouble)
    def glColor4d(red: float, green: float, blue: float, alpha: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glColor4dv(v: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat, GLfloat, GLfloat)
    def glColor4f(red: float, green: float, blue: float, alpha: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glColor4fv(v: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint, GLint, GLint)
    def glColor4i(red: int, green: int, blue: int, alpha: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLint))
    def glColor4iv(v: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLshort, GLshort, GLshort, GLshort)
    def glColor4s(red: int, green: int, blue: int, alpha: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLshort))
    def glColor4sv(v: IPointer[GLshort]) -> None: pass

    @opengl32.foreign(VOID, GLubyte, GLubyte, GLubyte, GLubyte)
    def glColor4ub(red: int, green: int, blue: int, alpha: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLubyte))
    def glColor4ubv(v: IPointer[GLubyte]) -> None: pass

    @opengl32.foreign(VOID, GLuint, GLuint, GLuint, GLuint)
    def glColor4ui(red: int, green: int, blue: int, alpha: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLuint))
    def glColor4uiv(v: IPointer[GLuint]) -> None: pass

    @opengl32.foreign(VOID, GLushort, GLushort, GLushort, GLushort)
    def glColor4us(red: int, green: int, blue: int, alpha: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLushort))
    def glColor4usv(v: IPointer[GLushort]) -> None: pass

    @opengl32.foreign(VOID, GLboolean)
    def glEdgeFlag(flag: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLboolean))
    def glEdgeFlagv(flag: IPointer[GLboolean]) -> None: pass

    @opengl32.foreign(VOID, )
    def glEnd() -> None: pass

    @opengl32.foreign(VOID, GLdouble)
    def glIndexd(c: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glIndexdv(c: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLfloat)
    def glIndexf(c: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glIndexfv(c: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLint)
    def glIndexi(c: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLint))
    def glIndexiv(c: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLshort)
    def glIndexs(c: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLshort))
    def glIndexsv(c: IPointer[GLshort]) -> None: pass

    @opengl32.foreign(VOID, GLbyte, GLbyte, GLbyte)
    def glNormal3b(nx: int, ny: int, nz: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLbyte))
    def glNormal3bv(v: IPointer[GLbyte]) -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble, GLdouble)
    def glNormal3d(nx: float, ny: float, nz: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glNormal3dv(v: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat, GLfloat)
    def glNormal3f(nx: float, ny: float, nz: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glNormal3fv(v: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint, GLint)
    def glNormal3i(nx: int, ny: int, nz: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLint))
    def glNormal3iv(v: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLshort, GLshort, GLshort)
    def glNormal3s(nx: int, ny: int, nz: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLshort))
    def glNormal3sv(v: IPointer[GLshort]) -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble)
    def glRasterPos2d(x: float, y: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glRasterPos2dv(v: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat)
    def glRasterPos2f(x: float, y: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glRasterPos2fv(v: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint)
    def glRasterPos2i(x: int, y: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLint))
    def glRasterPos2iv(v: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLshort, GLshort)
    def glRasterPos2s(x: int, y: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLshort))
    def glRasterPos2sv(v: IPointer[GLshort]) -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble, GLdouble)
    def glRasterPos3d(x: float, y: float, z: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glRasterPos3dv(v: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat, GLfloat)
    def glRasterPos3f(x: float, y: float, z: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glRasterPos3fv(v: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint, GLint)
    def glRasterPos3i(x: int, y: int, z: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLint))
    def glRasterPos3iv(v: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLshort, GLshort, GLshort)
    def glRasterPos3s(x: int, y: int, z: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLshort))
    def glRasterPos3sv(v: IPointer[GLshort]) -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble, GLdouble, GLdouble)
    def glRasterPos4d(x: float, y: float, z: float, w: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glRasterPos4dv(v: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat, GLfloat, GLfloat)
    def glRasterPos4f(x: float, y: float, z: float, w: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glRasterPos4fv(v: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint, GLint, GLint)
    def glRasterPos4i(x: int, y: int, z: int, w: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLint))
    def glRasterPos4iv(v: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLshort, GLshort, GLshort, GLshort)
    def glRasterPos4s(x: int, y: int, z: int, w: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLshort))
    def glRasterPos4sv(v: IPointer[GLshort]) -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble, GLdouble, GLdouble)
    def glRectd(x1: float, y1: float, x2: float, y2: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble), PTR(GLdouble))
    def glRectdv(v1: IPointer[GLdouble], v2: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat, GLfloat, GLfloat)
    def glRectf(x1: float, y1: float, x2: float, y2: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat), PTR(GLfloat))
    def glRectfv(v1: IPointer[GLfloat], v2: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint, GLint, GLint)
    def glRecti(x1: int, y1: int, x2: int, y2: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLint), PTR(GLint))
    def glRectiv(v1: IPointer[GLint], v2: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLshort, GLshort, GLshort, GLshort)
    def glRects(x1: int, y1: int, x2: int, y2: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLshort), PTR(GLshort))
    def glRectsv(v1: IPointer[GLshort], v2: IPointer[GLshort]) -> None: pass

    @opengl32.foreign(VOID, GLdouble)
    def glTexCoord1d(s: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glTexCoord1dv(v: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLfloat)
    def glTexCoord1f(s: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glTexCoord1fv(v: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLint)
    def glTexCoord1i(s: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLint))
    def glTexCoord1iv(v: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLshort)
    def glTexCoord1s(s: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLshort))
    def glTexCoord1sv(v: IPointer[GLshort]) -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble)
    def glTexCoord2d(s: float, t: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glTexCoord2dv(v: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat)
    def glTexCoord2f(s: float, t: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glTexCoord2fv(v: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint)
    def glTexCoord2i(s: int, t: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLint))
    def glTexCoord2iv(v: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLshort, GLshort)
    def glTexCoord2s(s: int, t: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLshort))
    def glTexCoord2sv(v: IPointer[GLshort]) -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble, GLdouble)
    def glTexCoord3d(s: float, t: float, r: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glTexCoord3dv(v: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat, GLfloat)
    def glTexCoord3f(s: float, t: float, r: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glTexCoord3fv(v: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint, GLint)
    def glTexCoord3i(s: int, t: int, r: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLint))
    def glTexCoord3iv(v: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLshort, GLshort, GLshort)
    def glTexCoord3s(s: int, t: int, r: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLshort))
    def glTexCoord3sv(v: IPointer[GLshort]) -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble, GLdouble, GLdouble)
    def glTexCoord4d(s: float, t: float, r: float, q: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glTexCoord4dv(v: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat, GLfloat, GLfloat)
    def glTexCoord4f(s: float, t: float, r: float, q: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glTexCoord4fv(v: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint, GLint, GLint)
    def glTexCoord4i(s: int, t: int, r: int, q: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLint))
    def glTexCoord4iv(v: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLshort, GLshort, GLshort, GLshort)
    def glTexCoord4s(s: int, t: int, r: int, q: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLshort))
    def glTexCoord4sv(v: IPointer[GLshort]) -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble)
    def glVertex2d(x: float, y: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glVertex2dv(v: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat)
    def glVertex2f(x: float, y: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glVertex2fv(v: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint)
    def glVertex2i(x: int, y: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLint))
    def glVertex2iv(v: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLshort, GLshort)
    def glVertex2s(x: int, y: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLshort))
    def glVertex2sv(v: IPointer[GLshort]) -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble, GLdouble)
    def glVertex3d(x: float, y: float, z: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glVertex3dv(v: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat, GLfloat)
    def glVertex3f(x: float, y: float, z: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glVertex3fv(v: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint, GLint)
    def glVertex3i(x: int, y: int, z: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLint))
    def glVertex3iv(v: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLshort, GLshort, GLshort)
    def glVertex3s(x: int, y: int, z: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLshort))
    def glVertex3sv(v: IPointer[GLshort]) -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble, GLdouble, GLdouble)
    def glVertex4d(x: float, y: float, z: float, w: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glVertex4dv(v: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat, GLfloat, GLfloat)
    def glVertex4f(x: float, y: float, z: float, w: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glVertex4fv(v: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint, GLint, GLint)
    def glVertex4i(x: int, y: int, z: int, w: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLint))
    def glVertex4iv(v: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLshort, GLshort, GLshort, GLshort)
    def glVertex4s(x: int, y: int, z: int, w: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLshort))
    def glVertex4sv(v: IPointer[GLshort]) -> None: pass

    @opengl32.foreign(VOID, GLenum, PTR(GLdouble))
    def glClipPlane(plane: int, equation: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum)
    def glColorMaterial(face: int, mode: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLfloat)
    def glFogf(pname: int, param: float) -> None: pass

    @opengl32.foreign(VOID, GLenum, PTR(GLfloat))
    def glFogfv(pname: int, params: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLint)
    def glFogi(pname: int, param: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, PTR(GLint))
    def glFogiv(pname: int, params: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, GLfloat)
    def glLightf(light: int, pname: int, param: float) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLfloat))
    def glLightfv(light: int, pname: int, params: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, GLint)
    def glLighti(light: int, pname: int, param: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLint))
    def glLightiv(light: int, pname: int, params: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLfloat)
    def glLightModelf(pname: int, param: float) -> None: pass

    @opengl32.foreign(VOID, GLenum, PTR(GLfloat))
    def glLightModelfv(pname: int, params: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLint)
    def glLightModeli(pname: int, param: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, PTR(GLint))
    def glLightModeliv(pname: int, params: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLushort)
    def glLineStipple(factor: int, pattern: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, GLfloat)
    def glMaterialf(face: int, pname: int, param: float) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLfloat))
    def glMaterialfv(face: int, pname: int, params: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, GLint)
    def glMateriali(face: int, pname: int, param: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLint))
    def glMaterialiv(face: int, pname: int, params: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, PTR(GLubyte))
    def glPolygonStipple(mask: IPointer[GLubyte]) -> None: pass

    @opengl32.foreign(VOID, GLenum)
    def glShadeModel(mode: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, GLfloat)
    def glTexEnvf(target: int, pname: int, param: float) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLfloat))
    def glTexEnvfv(target: int, pname: int, params: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, GLint)
    def glTexEnvi(target: int, pname: int, param: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLint))
    def glTexEnviv(target: int, pname: int, params: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, GLdouble)
    def glTexGend(coord: int, pname: int, param: float) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLdouble))
    def glTexGendv(coord: int, pname: int, params: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, GLfloat)
    def glTexGenf(coord: int, pname: int, param: float) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLfloat))
    def glTexGenfv(coord: int, pname: int, params: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, GLint)
    def glTexGeni(coord: int, pname: int, param: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLint))
    def glTexGeniv(coord: int, pname: int, params: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLsizei, GLenum, PTR(GLfloat))
    def glFeedbackBuffer(size: int, type: int, buffer: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLsizei, PTR(GLuint))
    def glSelectBuffer(size: int, buffer: IPointer[GLuint]) -> None: pass

    @opengl32.foreign(GLint, GLenum)
    def glRenderMode(mode: int) -> int: pass

    @opengl32.foreign(VOID, )
    def glInitNames() -> None: pass

    @opengl32.foreign(VOID, GLuint)
    def glLoadName(name: int) -> None: pass

    @opengl32.foreign(VOID, GLfloat)
    def glPassThrough(token: float) -> None: pass

    @opengl32.foreign(VOID, )
    def glPopName() -> None: pass

    @opengl32.foreign(VOID, GLuint)
    def glPushName(name: int) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat, GLfloat, GLfloat)
    def glClearAccum(red: float, green: float, blue: float, alpha: float) -> None: pass

    @opengl32.foreign(VOID, GLfloat)
    def glClearIndex(c: float) -> None: pass

    @opengl32.foreign(VOID, GLuint)
    def glIndexMask(mask: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLfloat)
    def glAccum(op: int, value: float) -> None: pass

    @opengl32.foreign(VOID, )
    def glPopAttrib() -> None: pass

    @opengl32.foreign(VOID, GLbitfield)
    def glPushAttrib(mask: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLdouble, GLdouble, GLint, GLint, PTR(GLdouble))
    def glMap1d(target: int, u1: float, u2: float, stride: int, order: int, points: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLfloat, GLfloat, GLint, GLint, PTR(GLfloat))
    def glMap1f(target: int, u1: float, u2: float, stride: int, order: int, points: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLdouble, GLdouble, GLint, GLint, GLdouble, GLdouble, GLint, GLint, PTR(GLdouble))
    def glMap2d(target: int, u1: float, u2: float, ustride: int, uorder: int, v1: float, v2: float, vstride: int, vorder: int, points: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLfloat, GLfloat, GLint, GLint, GLfloat, GLfloat, GLint, GLint, PTR(GLfloat))
    def glMap2f(target: int, u1: float, u2: float, ustride: int, uorder: int, v1: float, v2: float, vstride: int, vorder: int, points: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLdouble, GLdouble)
    def glMapGrid1d(un: int, u1: float, u2: float) -> None: pass

    @opengl32.foreign(VOID, GLint, GLfloat, GLfloat)
    def glMapGrid1f(un: int, u1: float, u2: float) -> None: pass

    @opengl32.foreign(VOID, GLint, GLdouble, GLdouble, GLint, GLdouble, GLdouble)
    def glMapGrid2d(un: int, u1: float, u2: float, vn: int, v1: float, v2: float) -> None: pass

    @opengl32.foreign(VOID, GLint, GLfloat, GLfloat, GLint, GLfloat, GLfloat)
    def glMapGrid2f(un: int, u1: float, u2: float, vn: int, v1: float, v2: float) -> None: pass

    @opengl32.foreign(VOID, GLdouble)
    def glEvalCoord1d(u: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glEvalCoord1dv(u: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLfloat)
    def glEvalCoord1f(u: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glEvalCoord1fv(u: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble)
    def glEvalCoord2d(u: float, v: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glEvalCoord2dv(u: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat)
    def glEvalCoord2f(u: float, v: float) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glEvalCoord2fv(u: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLint, GLint)
    def glEvalMesh1(mode: int, i1: int, i2: int) -> None: pass

    @opengl32.foreign(VOID, GLint)
    def glEvalPoint1(i: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLint, GLint, GLint, GLint)
    def glEvalMesh2(mode: int, i1: int, i2: int, j1: int, j2: int) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint)
    def glEvalPoint2(i: int, j: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLfloat)
    def glAlphaFunc(func: int, ref: float) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat)
    def glPixelZoom(xfactor: float, yfactor: float) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLfloat)
    def glPixelTransferf(pname: int, param: float) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLint)
    def glPixelTransferi(pname: int, param: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLsizei, PTR(GLfloat))
    def glPixelMapfv(map: int, mapsize: int, values: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLsizei, PTR(GLuint))
    def glPixelMapuiv(map: int, mapsize: int, values: IPointer[GLuint]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLsizei, PTR(GLushort))
    def glPixelMapusv(map: int, mapsize: int, values: IPointer[GLushort]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLint, GLsizei, GLsizei, GLenum)
    def glCopyPixels(x: int, y: int, width: int, height: int, type: int) -> None: pass

    @opengl32.foreign(VOID, GLsizei, GLsizei, GLenum, GLenum, PTR(VOID))
    def glDrawPixels(width: int, height: int, format: int, type: int, pixels: IPointer[int]) -> None: pass

    @opengl32.foreign(VOID, GLenum, PTR(GLdouble))
    def glGetClipPlane(plane: int, equation: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLfloat))
    def glGetLightfv(light: int, pname: int, params: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLint))
    def glGetLightiv(light: int, pname: int, params: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLdouble))
    def glGetMapdv(target: int, query: int, v: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLfloat))
    def glGetMapfv(target: int, query: int, v: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLint))
    def glGetMapiv(target: int, query: int, v: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLfloat))
    def glGetMaterialfv(face: int, pname: int, params: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLint))
    def glGetMaterialiv(face: int, pname: int, params: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLenum, PTR(GLfloat))
    def glGetPixelMapfv(map: int, values: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, PTR(GLuint))
    def glGetPixelMapuiv(map: int, values: IPointer[GLuint]) -> None: pass

    @opengl32.foreign(VOID, GLenum, PTR(GLushort))
    def glGetPixelMapusv(map: int, values: IPointer[GLushort]) -> None: pass

    @opengl32.foreign(VOID, PTR(GLubyte))
    def glGetPolygonStipple(mask: IPointer[GLubyte]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLfloat))
    def glGetTexEnvfv(target: int, pname: int, params: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLint))
    def glGetTexEnviv(target: int, pname: int, params: IPointer[GLint]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLdouble))
    def glGetTexGendv(coord: int, pname: int, params: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLfloat))
    def glGetTexGenfv(coord: int, pname: int, params: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLenum, PTR(GLint))
    def glGetTexGeniv(coord: int, pname: int, params: IPointer[GLint]) -> None: pass

    @opengl32.foreign(GLboolean, GLuint)
    def glIsList(list: int) -> int: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble)
    def glFrustum(left: float, right: float, bottom: float, top: float, zNear: float, zFar: float) -> None: pass

    @opengl32.foreign(VOID, )
    def glLoadIdentity() -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glLoadMatrixf(m: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glLoadMatrixd(m: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLenum)
    def glMatrixMode(mode: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLfloat))
    def glMultMatrixf(m: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, PTR(GLdouble))
    def glMultMatrixd(m: IPointer[GLdouble]) -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble, GLdouble)
    def glOrtho(left: float, right: float, bottom: float, top: float, zNear: float, zFar: float) -> None: pass

    @opengl32.foreign(VOID, )
    def glPopMatrix() -> None: pass

    @opengl32.foreign(VOID, )
    def glPushMatrix() -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble, GLdouble, GLdouble)
    def glRotated(angle: float, x: float, y: float, z: float) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat, GLfloat, GLfloat)
    def glRotatef(angle: float, x: float, y: float, z: float) -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble, GLdouble)
    def glScaled(x: float, y: float, z: float) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat, GLfloat)
    def glScalef(x: float, y: float, z: float) -> None: pass

    @opengl32.foreign(VOID, GLdouble, GLdouble, GLdouble)
    def glTranslated(x: float, y: float, z: float) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat, GLfloat)
    def glTranslatef(x: float, y: float, z: float) -> None: pass

