#
# This file generated by a Win.Tools.GLGen generator as a part of the Win project.
# Definitions for the OpenGL gl_1.1, do not change this file
# Date/Time of a generation: Thu Aug 27 21:13:35 2026
#

# OpenGL Imports
from win.gl.gl import *
from win.gl.glu import *
from win.abs.glext import *

# Basic OpenGL Types definitions
khronos_int8_t = GLbyte
khronos_uint8_t = GLubyte
khronos_int16_t = GLshort
khornos_uint16_t = GLushort
GLclampx = UINT32
GLeglClientBufferEXT = PVOID
GLeglImageOES = PVOID
GLchar = CHAR
GLcharARB = CHAR
GLhandleARB = UINT
GLhalf = UINT16
GLhalfARB = UINT16
GLfixed = INT32
GLintptr = INT_PTR
GLintptrARB = INT_PTR
GLsizeiptr = SSIZE_T
GLsizeiptrARB = SSIZE_T
GLint64 = INT64
GLint64EXT = INT64
GLuint64 = UINT64
GLuint64EXT = UINT64
GLsync = PVOID
GLDEBUGPROC = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCARB = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCKHR = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCAMD = APIENTRY(VOID, GLuint, GLenum, GLenum, GLsizei, LPSTR, PVOID)
GLhalfNV = USHORT
GLvdpauSurfaceNV = GLintptr
GLVULKANPROCNV = APIENTRY(VOID)

class GL11:
    #
    # Enum definitions
    #

    GL_COLOR_LOGIC_OP = 0x0BF2
    GL_POLYGON_OFFSET_UNITS = 0x2A00
    GL_POLYGON_OFFSET_POINT = 0x2A01
    GL_POLYGON_OFFSET_LINE = 0x2A02
    GL_POLYGON_OFFSET_FILL = 0x8037
    GL_POLYGON_OFFSET_FACTOR = 0x8038
    GL_TEXTURE_BINDING_1D = 0x8068
    GL_TEXTURE_BINDING_2D = 0x8069
    GL_TEXTURE_INTERNAL_FORMAT = 0x1003
    GL_TEXTURE_RED_SIZE = 0x805C
    GL_TEXTURE_GREEN_SIZE = 0x805D
    GL_TEXTURE_BLUE_SIZE = 0x805E
    GL_TEXTURE_ALPHA_SIZE = 0x805F
    GL_DOUBLE = 0x140A
    GL_PROXY_TEXTURE_1D = 0x8063
    GL_PROXY_TEXTURE_2D = 0x8064
    GL_R3_G3_B2 = 0x2A10
    GL_RGB4 = 0x804F
    GL_RGB5 = 0x8050
    GL_RGB8 = 0x8051
    GL_RGB10 = 0x8052
    GL_RGB12 = 0x8053
    GL_RGB16 = 0x8054
    GL_RGBA2 = 0x8055
    GL_RGBA4 = 0x8056
    GL_RGB5_A1 = 0x8057
    GL_RGBA8 = 0x8058
    GL_RGB10_A2 = 0x8059
    GL_RGBA12 = 0x805A
    GL_RGBA16 = 0x805B
    GL_CLIENT_PIXEL_STORE_BIT = 0x00000001
    GL_CLIENT_VERTEX_ARRAY_BIT = 0x00000002
    GL_CLIENT_ALL_ATTRIB_BITS = 0xFFFFFFFF
    GL_VERTEX_ARRAY_POINTER = 0x808E
    GL_NORMAL_ARRAY_POINTER = 0x808F
    GL_COLOR_ARRAY_POINTER = 0x8090
    GL_INDEX_ARRAY_POINTER = 0x8091
    GL_TEXTURE_COORD_ARRAY_POINTER = 0x8092
    GL_EDGE_FLAG_ARRAY_POINTER = 0x8093
    GL_FEEDBACK_BUFFER_POINTER = 0x0DF0
    GL_SELECTION_BUFFER_POINTER = 0x0DF3
    GL_CLIENT_ATTRIB_STACK_DEPTH = 0x0BB1
    GL_INDEX_LOGIC_OP = 0x0BF1
    GL_MAX_CLIENT_ATTRIB_STACK_DEPTH = 0x0D3B
    GL_FEEDBACK_BUFFER_SIZE = 0x0DF1
    GL_FEEDBACK_BUFFER_TYPE = 0x0DF2
    GL_SELECTION_BUFFER_SIZE = 0x0DF4
    GL_VERTEX_ARRAY = 0x8074
    GL_NORMAL_ARRAY = 0x8075
    GL_COLOR_ARRAY = 0x8076
    GL_INDEX_ARRAY = 0x8077
    GL_TEXTURE_COORD_ARRAY = 0x8078
    GL_EDGE_FLAG_ARRAY = 0x8079
    GL_VERTEX_ARRAY_SIZE = 0x807A
    GL_VERTEX_ARRAY_TYPE = 0x807B
    GL_VERTEX_ARRAY_STRIDE = 0x807C
    GL_NORMAL_ARRAY_TYPE = 0x807E
    GL_NORMAL_ARRAY_STRIDE = 0x807F
    GL_COLOR_ARRAY_SIZE = 0x8081
    GL_COLOR_ARRAY_TYPE = 0x8082
    GL_COLOR_ARRAY_STRIDE = 0x8083
    GL_INDEX_ARRAY_TYPE = 0x8085
    GL_INDEX_ARRAY_STRIDE = 0x8086
    GL_TEXTURE_COORD_ARRAY_SIZE = 0x8088
    GL_TEXTURE_COORD_ARRAY_TYPE = 0x8089
    GL_TEXTURE_COORD_ARRAY_STRIDE = 0x808A
    GL_EDGE_FLAG_ARRAY_STRIDE = 0x808C
    GL_TEXTURE_LUMINANCE_SIZE = 0x8060
    GL_TEXTURE_INTENSITY_SIZE = 0x8061
    GL_TEXTURE_PRIORITY = 0x8066
    GL_TEXTURE_RESIDENT = 0x8067
    GL_ALPHA4 = 0x803B
    GL_ALPHA8 = 0x803C
    GL_ALPHA12 = 0x803D
    GL_ALPHA16 = 0x803E
    GL_LUMINANCE4 = 0x803F
    GL_LUMINANCE8 = 0x8040
    GL_LUMINANCE12 = 0x8041
    GL_LUMINANCE16 = 0x8042
    GL_LUMINANCE4_ALPHA4 = 0x8043
    GL_LUMINANCE6_ALPHA2 = 0x8044
    GL_LUMINANCE8_ALPHA8 = 0x8045
    GL_LUMINANCE12_ALPHA4 = 0x8046
    GL_LUMINANCE12_ALPHA12 = 0x8047
    GL_LUMINANCE16_ALPHA16 = 0x8048
    GL_INTENSITY = 0x8049
    GL_INTENSITY4 = 0x804A
    GL_INTENSITY8 = 0x804B
    GL_INTENSITY12 = 0x804C
    GL_INTENSITY16 = 0x804D
    GL_V2F = 0x2A20
    GL_V3F = 0x2A21
    GL_C4UB_V2F = 0x2A22
    GL_C4UB_V3F = 0x2A23
    GL_C3F_V3F = 0x2A24
    GL_N3F_V3F = 0x2A25
    GL_C4F_N3F_V3F = 0x2A26
    GL_T2F_V3F = 0x2A27
    GL_T4F_V4F = 0x2A28
    GL_T2F_C4UB_V3F = 0x2A29
    GL_T2F_C3F_V3F = 0x2A2A
    GL_T2F_N3F_V3F = 0x2A2B
    GL_T2F_C4F_N3F_V3F = 0x2A2C
    GL_T4F_C4F_N3F_V4F = 0x2A2D

    #
    # Function/Command definitions
    #

    @opengl32.foreign(VOID, GLenum, GLint, GLsizei)
    def glDrawArrays(mode: int, first: int, count: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLsizei, GLenum, PTR(VOID))
    def glDrawElements(mode: int, count: int, type: int, indices: IPointer[int]) -> None: pass

    @opengl32.foreign(VOID, GLenum, PTR(PTR(VOID)))
    def glGetPointerv(pname: int, params: IPointer[IPointer[int]]) -> None: pass

    @opengl32.foreign(VOID, GLfloat, GLfloat)
    def glPolygonOffset(factor: float, units: float) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLint)
    def glCopyTexImage1D(target: int, level: int, internalformat: int, x: int, y: int, width: int, border: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLint, GLenum, GLint, GLint, GLsizei, GLsizei, GLint)
    def glCopyTexImage2D(target: int, level: int, internalformat: int, x: int, y: int, width: int, height: int, border: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLint, GLint, GLint, GLint, GLsizei)
    def glCopyTexSubImage1D(target: int, level: int, xoffset: int, x: int, y: int, width: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei)
    def glCopyTexSubImage2D(target: int, level: int, xoffset: int, yoffset: int, x: int, y: int, width: int, height: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLint, GLint, GLsizei, GLenum, GLenum, PTR(VOID))
    def glTexSubImage1D(target: int, level: int, xoffset: int, width: int, format: int, type: int, pixels: IPointer[int]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, PTR(VOID))
    def glTexSubImage2D(target: int, level: int, xoffset: int, yoffset: int, width: int, height: int, format: int, type: int, pixels: IPointer[int]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLuint)
    def glBindTexture(target: int, texture: int) -> None: pass

    @opengl32.foreign(VOID, GLsizei, PTR(GLuint))
    def glDeleteTextures(n: int, textures: IPointer[GLuint]) -> None: pass

    @opengl32.foreign(VOID, GLsizei, PTR(GLuint))
    def glGenTextures(n: int, textures: IPointer[GLuint]) -> None: pass

    @opengl32.foreign(GLboolean, GLuint)
    def glIsTexture(texture: int) -> int: pass

    @opengl32.foreign(VOID, GLint)
    def glArrayElement(i: int) -> None: pass

    @opengl32.foreign(VOID, GLint, GLenum, GLsizei, PTR(VOID))
    def glColorPointer(size: int, type: int, stride: int, pointer: IPointer[int]) -> None: pass

    @opengl32.foreign(VOID, GLenum)
    def glDisableClientState(array: int) -> None: pass

    @opengl32.foreign(VOID, GLsizei, PTR(VOID))
    def glEdgeFlagPointer(stride: int, pointer: IPointer[int]) -> None: pass

    @opengl32.foreign(VOID, GLenum)
    def glEnableClientState(array: int) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLsizei, PTR(VOID))
    def glIndexPointer(type: int, stride: int, pointer: IPointer[int]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLsizei, PTR(VOID))
    def glInterleavedArrays(format: int, stride: int, pointer: IPointer[int]) -> None: pass

    @opengl32.foreign(VOID, GLenum, GLsizei, PTR(VOID))
    def glNormalPointer(type: int, stride: int, pointer: IPointer[int]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLenum, GLsizei, PTR(VOID))
    def glTexCoordPointer(size: int, type: int, stride: int, pointer: IPointer[int]) -> None: pass

    @opengl32.foreign(VOID, GLint, GLenum, GLsizei, PTR(VOID))
    def glVertexPointer(size: int, type: int, stride: int, pointer: IPointer[int]) -> None: pass

    @opengl32.foreign(GLboolean, GLsizei, PTR(GLuint), PTR(GLboolean))
    def glAreTexturesResident(n: int, textures: IPointer[GLuint], residences: IPointer[GLboolean]) -> int: pass

    @opengl32.foreign(VOID, GLsizei, PTR(GLuint), PTR(GLfloat))
    def glPrioritizeTextures(n: int, textures: IPointer[GLuint], priorities: IPointer[GLfloat]) -> None: pass

    @opengl32.foreign(VOID, GLubyte)
    def glIndexub(c: int) -> None: pass

    @opengl32.foreign(VOID, PTR(GLubyte))
    def glIndexubv(c: IPointer[GLubyte]) -> None: pass

    @opengl32.foreign(VOID, )
    def glPopClientAttrib() -> None: pass

    @opengl32.foreign(VOID, GLbitfield)
    def glPushClientAttrib(mask: int) -> None: pass

