#
# This file generated by a Win.Tools.GLGen generator as a part of the Win project.
# Definitions for the OpenGL gl_1.2, do not change this file
# Date/Time of a generation: Thu Aug 27 21:13:35 2026
#

# OpenGL Imports
from win.gl.gl import *
from win.gl.glu import *
from win.abs.glext import *

# Basic OpenGL Types definitions
khronos_int8_t = GLbyte
khronos_uint8_t = GLubyte
khronos_int16_t = GLshort
khornos_uint16_t = GLushort
GLclampx = UINT32
GLeglClientBufferEXT = PVOID
GLeglImageOES = PVOID
GLchar = CHAR
GLcharARB = CHAR
GLhandleARB = UINT
GLhalf = UINT16
GLhalfARB = UINT16
GLfixed = INT32
GLintptr = INT_PTR
GLintptrARB = INT_PTR
GLsizeiptr = SSIZE_T
GLsizeiptrARB = SSIZE_T
GLint64 = INT64
GLint64EXT = INT64
GLuint64 = UINT64
GLuint64EXT = UINT64
GLsync = PVOID
GLDEBUGPROC = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCARB = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCKHR = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCAMD = APIENTRY(VOID, GLuint, GLenum, GLenum, GLsizei, LPSTR, PVOID)
GLhalfNV = USHORT
GLvdpauSurfaceNV = GLintptr
GLVULKANPROCNV = APIENTRY(VOID)

class GL12:
    #
    # Enum definitions
    #

    GL_UNSIGNED_BYTE_3_3_2 = 0x8032
    GL_UNSIGNED_SHORT_4_4_4_4 = 0x8033
    GL_UNSIGNED_SHORT_5_5_5_1 = 0x8034
    GL_UNSIGNED_INT_8_8_8_8 = 0x8035
    GL_UNSIGNED_INT_10_10_10_2 = 0x8036
    GL_TEXTURE_BINDING_3D = 0x806A
    GL_PACK_SKIP_IMAGES = 0x806B
    GL_PACK_IMAGE_HEIGHT = 0x806C
    GL_UNPACK_SKIP_IMAGES = 0x806D
    GL_UNPACK_IMAGE_HEIGHT = 0x806E
    GL_TEXTURE_3D = 0x806F
    GL_PROXY_TEXTURE_3D = 0x8070
    GL_TEXTURE_DEPTH = 0x8071
    GL_TEXTURE_WRAP_R = 0x8072
    GL_MAX_3D_TEXTURE_SIZE = 0x8073
    GL_UNSIGNED_BYTE_2_3_3_REV = 0x8362
    GL_UNSIGNED_SHORT_5_6_5 = 0x8363
    GL_UNSIGNED_SHORT_5_6_5_REV = 0x8364
    GL_UNSIGNED_SHORT_4_4_4_4_REV = 0x8365
    GL_UNSIGNED_SHORT_1_5_5_5_REV = 0x8366
    GL_UNSIGNED_INT_8_8_8_8_REV = 0x8367
    GL_UNSIGNED_INT_2_10_10_10_REV = 0x8368
    GL_BGR = 0x80E0
    GL_BGRA = 0x80E1
    GL_MAX_ELEMENTS_VERTICES = 0x80E8
    GL_MAX_ELEMENTS_INDICES = 0x80E9
    GL_CLAMP_TO_EDGE = 0x812F
    GL_TEXTURE_MIN_LOD = 0x813A
    GL_TEXTURE_MAX_LOD = 0x813B
    GL_TEXTURE_BASE_LEVEL = 0x813C
    GL_TEXTURE_MAX_LEVEL = 0x813D
    GL_SMOOTH_POINT_SIZE_RANGE = 0x0B12
    GL_SMOOTH_POINT_SIZE_GRANULARITY = 0x0B13
    GL_SMOOTH_LINE_WIDTH_RANGE = 0x0B22
    GL_SMOOTH_LINE_WIDTH_GRANULARITY = 0x0B23
    GL_ALIASED_LINE_WIDTH_RANGE = 0x846E
    GL_RESCALE_NORMAL = 0x803A
    GL_LIGHT_MODEL_COLOR_CONTROL = 0x81F8
    GL_SINGLE_COLOR = 0x81F9
    GL_SEPARATE_SPECULAR_COLOR = 0x81FA
    GL_ALIASED_POINT_SIZE_RANGE = 0x846D

    #
    # Function/Command definitions
    #

    @GLExtAPI.method(VOID, GLenum, GLuint, GLuint, GLsizei, GLenum, PTR(VOID))
    def glDrawRangeElements(mode: int, start: int, end: int, count: int, type: int, indices: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint, GLint, GLsizei, GLsizei, GLsizei, GLint, GLenum, GLenum, PTR(VOID))
    def glTexImage3D(target: int, level: int, internalformat: int, width: int, height: int, depth: int, border: int, format: int, type: int, pixels: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, PTR(VOID))
    def glTexSubImage3D(target: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, format: int, type: int, pixels: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei)
    def glCopyTexSubImage3D(target: int, level: int, xoffset: int, yoffset: int, zoffset: int, x: int, y: int, width: int, height: int) -> None: pass

