#
# This file generated by a Win.Tools.GLGen generator as a part of the Win project.
# Definitions for the OpenGL gl_1.3, do not change this file
# Date/Time of a generation: Thu Aug 27 21:13:35 2026
#

# OpenGL Imports
from win.gl.gl import *
from win.gl.glu import *
from win.abs.glext import *

# Basic OpenGL Types definitions
khronos_int8_t = GLbyte
khronos_uint8_t = GLubyte
khronos_int16_t = GLshort
khornos_uint16_t = GLushort
GLclampx = UINT32
GLeglClientBufferEXT = PVOID
GLeglImageOES = PVOID
GLchar = CHAR
GLcharARB = CHAR
GLhandleARB = UINT
GLhalf = UINT16
GLhalfARB = UINT16
GLfixed = INT32
GLintptr = INT_PTR
GLintptrARB = INT_PTR
GLsizeiptr = SSIZE_T
GLsizeiptrARB = SSIZE_T
GLint64 = INT64
GLint64EXT = INT64
GLuint64 = UINT64
GLuint64EXT = UINT64
GLsync = PVOID
GLDEBUGPROC = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCARB = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCKHR = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCAMD = APIENTRY(VOID, GLuint, GLenum, GLenum, GLsizei, LPSTR, PVOID)
GLhalfNV = USHORT
GLvdpauSurfaceNV = GLintptr
GLVULKANPROCNV = APIENTRY(VOID)

class GL13:
    #
    # Enum definitions
    #

    GL_TEXTURE0 = 0x84C0
    GL_TEXTURE1 = 0x84C1
    GL_TEXTURE2 = 0x84C2
    GL_TEXTURE3 = 0x84C3
    GL_TEXTURE4 = 0x84C4
    GL_TEXTURE5 = 0x84C5
    GL_TEXTURE6 = 0x84C6
    GL_TEXTURE7 = 0x84C7
    GL_TEXTURE8 = 0x84C8
    GL_TEXTURE9 = 0x84C9
    GL_TEXTURE10 = 0x84CA
    GL_TEXTURE11 = 0x84CB
    GL_TEXTURE12 = 0x84CC
    GL_TEXTURE13 = 0x84CD
    GL_TEXTURE14 = 0x84CE
    GL_TEXTURE15 = 0x84CF
    GL_TEXTURE16 = 0x84D0
    GL_TEXTURE17 = 0x84D1
    GL_TEXTURE18 = 0x84D2
    GL_TEXTURE19 = 0x84D3
    GL_TEXTURE20 = 0x84D4
    GL_TEXTURE21 = 0x84D5
    GL_TEXTURE22 = 0x84D6
    GL_TEXTURE23 = 0x84D7
    GL_TEXTURE24 = 0x84D8
    GL_TEXTURE25 = 0x84D9
    GL_TEXTURE26 = 0x84DA
    GL_TEXTURE27 = 0x84DB
    GL_TEXTURE28 = 0x84DC
    GL_TEXTURE29 = 0x84DD
    GL_TEXTURE30 = 0x84DE
    GL_TEXTURE31 = 0x84DF
    GL_ACTIVE_TEXTURE = 0x84E0
    GL_MULTISAMPLE = 0x809D
    GL_SAMPLE_ALPHA_TO_COVERAGE = 0x809E
    GL_SAMPLE_ALPHA_TO_ONE = 0x809F
    GL_SAMPLE_COVERAGE = 0x80A0
    GL_SAMPLE_BUFFERS = 0x80A8
    GL_SAMPLES = 0x80A9
    GL_SAMPLE_COVERAGE_VALUE = 0x80AA
    GL_SAMPLE_COVERAGE_INVERT = 0x80AB
    GL_TEXTURE_CUBE_MAP = 0x8513
    GL_TEXTURE_BINDING_CUBE_MAP = 0x8514
    GL_TEXTURE_CUBE_MAP_POSITIVE_X = 0x8515
    GL_TEXTURE_CUBE_MAP_NEGATIVE_X = 0x8516
    GL_TEXTURE_CUBE_MAP_POSITIVE_Y = 0x8517
    GL_TEXTURE_CUBE_MAP_NEGATIVE_Y = 0x8518
    GL_TEXTURE_CUBE_MAP_POSITIVE_Z = 0x8519
    GL_TEXTURE_CUBE_MAP_NEGATIVE_Z = 0x851A
    GL_PROXY_TEXTURE_CUBE_MAP = 0x851B
    GL_MAX_CUBE_MAP_TEXTURE_SIZE = 0x851C
    GL_COMPRESSED_RGB = 0x84ED
    GL_COMPRESSED_RGBA = 0x84EE
    GL_TEXTURE_COMPRESSION_HINT = 0x84EF
    GL_TEXTURE_COMPRESSED_IMAGE_SIZE = 0x86A0
    GL_TEXTURE_COMPRESSED = 0x86A1
    GL_NUM_COMPRESSED_TEXTURE_FORMATS = 0x86A2
    GL_COMPRESSED_TEXTURE_FORMATS = 0x86A3
    GL_CLAMP_TO_BORDER = 0x812D
    GL_CLIENT_ACTIVE_TEXTURE = 0x84E1
    GL_MAX_TEXTURE_UNITS = 0x84E2
    GL_TRANSPOSE_MODELVIEW_MATRIX = 0x84E3
    GL_TRANSPOSE_PROJECTION_MATRIX = 0x84E4
    GL_TRANSPOSE_TEXTURE_MATRIX = 0x84E5
    GL_TRANSPOSE_COLOR_MATRIX = 0x84E6
    GL_MULTISAMPLE_BIT = 0x20000000
    GL_NORMAL_MAP = 0x8511
    GL_REFLECTION_MAP = 0x8512
    GL_COMPRESSED_ALPHA = 0x84E9
    GL_COMPRESSED_LUMINANCE = 0x84EA
    GL_COMPRESSED_LUMINANCE_ALPHA = 0x84EB
    GL_COMPRESSED_INTENSITY = 0x84EC
    GL_COMBINE = 0x8570
    GL_COMBINE_RGB = 0x8571
    GL_COMBINE_ALPHA = 0x8572
    GL_SOURCE0_RGB = 0x8580
    GL_SOURCE1_RGB = 0x8581
    GL_SOURCE2_RGB = 0x8582
    GL_SOURCE0_ALPHA = 0x8588
    GL_SOURCE1_ALPHA = 0x8589
    GL_SOURCE2_ALPHA = 0x858A
    GL_OPERAND0_RGB = 0x8590
    GL_OPERAND1_RGB = 0x8591
    GL_OPERAND2_RGB = 0x8592
    GL_OPERAND0_ALPHA = 0x8598
    GL_OPERAND1_ALPHA = 0x8599
    GL_OPERAND2_ALPHA = 0x859A
    GL_RGB_SCALE = 0x8573
    GL_ADD_SIGNED = 0x8574
    GL_INTERPOLATE = 0x8575
    GL_SUBTRACT = 0x84E7
    GL_CONSTANT = 0x8576
    GL_PRIMARY_COLOR = 0x8577
    GL_PREVIOUS = 0x8578
    GL_DOT3_RGB = 0x86AE
    GL_DOT3_RGBA = 0x86AF

    #
    # Function/Command definitions
    #

    @GLExtAPI.method(VOID, GLenum)
    def glActiveTexture(texture: int) -> None: pass

    @GLExtAPI.method(VOID, GLfloat, GLboolean)
    def glSampleCoverage(value: float, invert: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint, GLenum, GLsizei, GLsizei, GLsizei, GLint, GLsizei, PTR(VOID))
    def glCompressedTexImage3D(target: int, level: int, internalformat: int, width: int, height: int, depth: int, border: int, imageSize: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint, GLenum, GLsizei, GLsizei, GLint, GLsizei, PTR(VOID))
    def glCompressedTexImage2D(target: int, level: int, internalformat: int, width: int, height: int, border: int, imageSize: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint, GLenum, GLsizei, GLint, GLsizei, PTR(VOID))
    def glCompressedTexImage1D(target: int, level: int, internalformat: int, width: int, border: int, imageSize: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, PTR(VOID))
    def glCompressedTexSubImage3D(target: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, format: int, imageSize: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, PTR(VOID))
    def glCompressedTexSubImage2D(target: int, level: int, xoffset: int, yoffset: int, width: int, height: int, format: int, imageSize: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint, GLint, GLsizei, GLenum, GLsizei, PTR(VOID))
    def glCompressedTexSubImage1D(target: int, level: int, xoffset: int, width: int, format: int, imageSize: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint, PTR(VOID))
    def glGetCompressedTexImage(target: int, level: int, img: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum)
    def glClientActiveTexture(texture: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLdouble)
    def glMultiTexCoord1d(target: int, s: float) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLdouble))
    def glMultiTexCoord1dv(target: int, v: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLfloat)
    def glMultiTexCoord1f(target: int, s: float) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLfloat))
    def glMultiTexCoord1fv(target: int, v: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint)
    def glMultiTexCoord1i(target: int, s: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLint))
    def glMultiTexCoord1iv(target: int, v: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLshort)
    def glMultiTexCoord1s(target: int, s: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLshort))
    def glMultiTexCoord1sv(target: int, v: IPointer[GLshort]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLdouble, GLdouble)
    def glMultiTexCoord2d(target: int, s: float, t: float) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLdouble))
    def glMultiTexCoord2dv(target: int, v: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLfloat, GLfloat)
    def glMultiTexCoord2f(target: int, s: float, t: float) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLfloat))
    def glMultiTexCoord2fv(target: int, v: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint, GLint)
    def glMultiTexCoord2i(target: int, s: int, t: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLint))
    def glMultiTexCoord2iv(target: int, v: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLshort, GLshort)
    def glMultiTexCoord2s(target: int, s: int, t: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLshort))
    def glMultiTexCoord2sv(target: int, v: IPointer[GLshort]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLdouble, GLdouble, GLdouble)
    def glMultiTexCoord3d(target: int, s: float, t: float, r: float) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLdouble))
    def glMultiTexCoord3dv(target: int, v: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLfloat, GLfloat, GLfloat)
    def glMultiTexCoord3f(target: int, s: float, t: float, r: float) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLfloat))
    def glMultiTexCoord3fv(target: int, v: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint, GLint, GLint)
    def glMultiTexCoord3i(target: int, s: int, t: int, r: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLint))
    def glMultiTexCoord3iv(target: int, v: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLshort, GLshort, GLshort)
    def glMultiTexCoord3s(target: int, s: int, t: int, r: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLshort))
    def glMultiTexCoord3sv(target: int, v: IPointer[GLshort]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLdouble, GLdouble, GLdouble, GLdouble)
    def glMultiTexCoord4d(target: int, s: float, t: float, r: float, q: float) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLdouble))
    def glMultiTexCoord4dv(target: int, v: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLfloat, GLfloat, GLfloat, GLfloat)
    def glMultiTexCoord4f(target: int, s: float, t: float, r: float, q: float) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLfloat))
    def glMultiTexCoord4fv(target: int, v: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint, GLint, GLint, GLint)
    def glMultiTexCoord4i(target: int, s: int, t: int, r: int, q: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLint))
    def glMultiTexCoord4iv(target: int, v: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLshort, GLshort, GLshort, GLshort)
    def glMultiTexCoord4s(target: int, s: int, t: int, r: int, q: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLshort))
    def glMultiTexCoord4sv(target: int, v: IPointer[GLshort]) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLfloat))
    def glLoadTransposeMatrixf(m: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLdouble))
    def glLoadTransposeMatrixd(m: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLfloat))
    def glMultTransposeMatrixf(m: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLdouble))
    def glMultTransposeMatrixd(m: IPointer[GLdouble]) -> None: pass

