#
# This file generated by a Win.Tools.GLGen generator as a part of the Win project.
# Definitions for the OpenGL gl_1.4, do not change this file
# Date/Time of a generation: Thu Aug 27 21:13:35 2026
#

# OpenGL Imports
from win.gl.gl import *
from win.gl.glu import *
from win.abs.glext import *

# Basic OpenGL Types definitions
khronos_int8_t = GLbyte
khronos_uint8_t = GLubyte
khronos_int16_t = GLshort
khornos_uint16_t = GLushort
GLclampx = UINT32
GLeglClientBufferEXT = PVOID
GLeglImageOES = PVOID
GLchar = CHAR
GLcharARB = CHAR
GLhandleARB = UINT
GLhalf = UINT16
GLhalfARB = UINT16
GLfixed = INT32
GLintptr = INT_PTR
GLintptrARB = INT_PTR
GLsizeiptr = SSIZE_T
GLsizeiptrARB = SSIZE_T
GLint64 = INT64
GLint64EXT = INT64
GLuint64 = UINT64
GLuint64EXT = UINT64
GLsync = PVOID
GLDEBUGPROC = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCARB = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCKHR = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCAMD = APIENTRY(VOID, GLuint, GLenum, GLenum, GLsizei, LPSTR, PVOID)
GLhalfNV = USHORT
GLvdpauSurfaceNV = GLintptr
GLVULKANPROCNV = APIENTRY(VOID)

class GL14:
    #
    # Enum definitions
    #

    GL_BLEND_DST_RGB = 0x80C8
    GL_BLEND_SRC_RGB = 0x80C9
    GL_BLEND_DST_ALPHA = 0x80CA
    GL_BLEND_SRC_ALPHA = 0x80CB
    GL_POINT_FADE_THRESHOLD_SIZE = 0x8128
    GL_DEPTH_COMPONENT16 = 0x81A5
    GL_DEPTH_COMPONENT24 = 0x81A6
    GL_DEPTH_COMPONENT32 = 0x81A7
    GL_MIRRORED_REPEAT = 0x8370
    GL_MAX_TEXTURE_LOD_BIAS = 0x84FD
    GL_TEXTURE_LOD_BIAS = 0x8501
    GL_INCR_WRAP = 0x8507
    GL_DECR_WRAP = 0x8508
    GL_TEXTURE_DEPTH_SIZE = 0x884A
    GL_TEXTURE_COMPARE_MODE = 0x884C
    GL_TEXTURE_COMPARE_FUNC = 0x884D
    GL_POINT_SIZE_MIN = 0x8126
    GL_POINT_SIZE_MAX = 0x8127
    GL_POINT_DISTANCE_ATTENUATION = 0x8129
    GL_GENERATE_MIPMAP = 0x8191
    GL_GENERATE_MIPMAP_HINT = 0x8192
    GL_FOG_COORDINATE_SOURCE = 0x8450
    GL_FOG_COORDINATE = 0x8451
    GL_FRAGMENT_DEPTH = 0x8452
    GL_CURRENT_FOG_COORDINATE = 0x8453
    GL_FOG_COORDINATE_ARRAY_TYPE = 0x8454
    GL_FOG_COORDINATE_ARRAY_STRIDE = 0x8455
    GL_FOG_COORDINATE_ARRAY_POINTER = 0x8456
    GL_FOG_COORDINATE_ARRAY = 0x8457
    GL_COLOR_SUM = 0x8458
    GL_CURRENT_SECONDARY_COLOR = 0x8459
    GL_SECONDARY_COLOR_ARRAY_SIZE = 0x845A
    GL_SECONDARY_COLOR_ARRAY_TYPE = 0x845B
    GL_SECONDARY_COLOR_ARRAY_STRIDE = 0x845C
    GL_SECONDARY_COLOR_ARRAY_POINTER = 0x845D
    GL_SECONDARY_COLOR_ARRAY = 0x845E
    GL_TEXTURE_FILTER_CONTROL = 0x8500
    GL_DEPTH_TEXTURE_MODE = 0x884B
    GL_COMPARE_R_TO_TEXTURE = 0x884E
    GL_BLEND_COLOR = 0x8005
    GL_BLEND_EQUATION = 0x8009
    GL_CONSTANT_COLOR = 0x8001
    GL_ONE_MINUS_CONSTANT_COLOR = 0x8002
    GL_CONSTANT_ALPHA = 0x8003
    GL_ONE_MINUS_CONSTANT_ALPHA = 0x8004
    GL_FUNC_ADD = 0x8006
    GL_FUNC_REVERSE_SUBTRACT = 0x800B
    GL_FUNC_SUBTRACT = 0x800A
    GL_MIN = 0x8007
    GL_MAX = 0x8008

    #
    # Function/Command definitions
    #

    @GLExtAPI.method(VOID, GLenum, GLenum, GLenum, GLenum)
    def glBlendFuncSeparate(sfactorRGB: int, dfactorRGB: int, sfactorAlpha: int, dfactorAlpha: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLint), PTR(GLsizei), GLsizei)
    def glMultiDrawArrays(mode: int, first: IPointer[GLint], count: IPointer[GLsizei], drawcount: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLsizei), GLenum, PTR(PTR(VOID)), GLsizei)
    def glMultiDrawElements(mode: int, count: IPointer[GLsizei], type: int, indices: IPointer[IPointer[int]], drawcount: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLfloat)
    def glPointParameterf(pname: int, param: float) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLfloat))
    def glPointParameterfv(pname: int, params: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint)
    def glPointParameteri(pname: int, param: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLint))
    def glPointParameteriv(pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLfloat)
    def glFogCoordf(coord: float) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLfloat))
    def glFogCoordfv(coord: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLdouble)
    def glFogCoordd(coord: float) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLdouble))
    def glFogCoorddv(coord: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLsizei, PTR(VOID))
    def glFogCoordPointer(type: int, stride: int, pointer: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLbyte, GLbyte, GLbyte)
    def glSecondaryColor3b(red: int, green: int, blue: int) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLbyte))
    def glSecondaryColor3bv(v: IPointer[GLbyte]) -> None: pass

    @GLExtAPI.method(VOID, GLdouble, GLdouble, GLdouble)
    def glSecondaryColor3d(red: float, green: float, blue: float) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLdouble))
    def glSecondaryColor3dv(v: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLfloat, GLfloat, GLfloat)
    def glSecondaryColor3f(red: float, green: float, blue: float) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLfloat))
    def glSecondaryColor3fv(v: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLint, GLint)
    def glSecondaryColor3i(red: int, green: int, blue: int) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLint))
    def glSecondaryColor3iv(v: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLshort, GLshort, GLshort)
    def glSecondaryColor3s(red: int, green: int, blue: int) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLshort))
    def glSecondaryColor3sv(v: IPointer[GLshort]) -> None: pass

    @GLExtAPI.method(VOID, GLubyte, GLubyte, GLubyte)
    def glSecondaryColor3ub(red: int, green: int, blue: int) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLubyte))
    def glSecondaryColor3ubv(v: IPointer[GLubyte]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLuint)
    def glSecondaryColor3ui(red: int, green: int, blue: int) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLuint))
    def glSecondaryColor3uiv(v: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLushort, GLushort, GLushort)
    def glSecondaryColor3us(red: int, green: int, blue: int) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLushort))
    def glSecondaryColor3usv(v: IPointer[GLushort]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLenum, GLsizei, PTR(VOID))
    def glSecondaryColorPointer(size: int, type: int, stride: int, pointer: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLdouble, GLdouble)
    def glWindowPos2d(x: float, y: float) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLdouble))
    def glWindowPos2dv(v: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLfloat, GLfloat)
    def glWindowPos2f(x: float, y: float) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLfloat))
    def glWindowPos2fv(v: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLint)
    def glWindowPos2i(x: int, y: int) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLint))
    def glWindowPos2iv(v: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLshort, GLshort)
    def glWindowPos2s(x: int, y: int) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLshort))
    def glWindowPos2sv(v: IPointer[GLshort]) -> None: pass

    @GLExtAPI.method(VOID, GLdouble, GLdouble, GLdouble)
    def glWindowPos3d(x: float, y: float, z: float) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLdouble))
    def glWindowPos3dv(v: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLfloat, GLfloat, GLfloat)
    def glWindowPos3f(x: float, y: float, z: float) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLfloat))
    def glWindowPos3fv(v: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLint, GLint)
    def glWindowPos3i(x: int, y: int, z: int) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLint))
    def glWindowPos3iv(v: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLshort, GLshort, GLshort)
    def glWindowPos3s(x: int, y: int, z: int) -> None: pass

    @GLExtAPI.method(VOID, PTR(GLshort))
    def glWindowPos3sv(v: IPointer[GLshort]) -> None: pass

    @GLExtAPI.method(VOID, GLfloat, GLfloat, GLfloat, GLfloat)
    def glBlendColor(red: float, green: float, blue: float, alpha: float) -> None: pass

    @GLExtAPI.method(VOID, GLenum)
    def glBlendEquation(mode: int) -> None: pass

