#
# This file generated by a Win.Tools.GLGen generator as a part of the Win project.
# Definitions for the OpenGL gl_1.5, do not change this file
# Date/Time of a generation: Thu Aug 27 21:13:35 2026
#

# OpenGL Imports
from win.gl.gl import *
from win.gl.glu import *
from win.abs.glext import *

# Basic OpenGL Types definitions
khronos_int8_t = GLbyte
khronos_uint8_t = GLubyte
khronos_int16_t = GLshort
khornos_uint16_t = GLushort
GLclampx = UINT32
GLeglClientBufferEXT = PVOID
GLeglImageOES = PVOID
GLchar = CHAR
GLcharARB = CHAR
GLhandleARB = UINT
GLhalf = UINT16
GLhalfARB = UINT16
GLfixed = INT32
GLintptr = INT_PTR
GLintptrARB = INT_PTR
GLsizeiptr = SSIZE_T
GLsizeiptrARB = SSIZE_T
GLint64 = INT64
GLint64EXT = INT64
GLuint64 = UINT64
GLuint64EXT = UINT64
GLsync = PVOID
GLDEBUGPROC = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCARB = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCKHR = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCAMD = APIENTRY(VOID, GLuint, GLenum, GLenum, GLsizei, LPSTR, PVOID)
GLhalfNV = USHORT
GLvdpauSurfaceNV = GLintptr
GLVULKANPROCNV = APIENTRY(VOID)

class GL15:
    #
    # Enum definitions
    #

    GL_BUFFER_SIZE = 0x8764
    GL_BUFFER_USAGE = 0x8765
    GL_QUERY_COUNTER_BITS = 0x8864
    GL_CURRENT_QUERY = 0x8865
    GL_QUERY_RESULT = 0x8866
    GL_QUERY_RESULT_AVAILABLE = 0x8867
    GL_ARRAY_BUFFER = 0x8892
    GL_ELEMENT_ARRAY_BUFFER = 0x8893
    GL_ARRAY_BUFFER_BINDING = 0x8894
    GL_ELEMENT_ARRAY_BUFFER_BINDING = 0x8895
    GL_VERTEX_ATTRIB_ARRAY_BUFFER_BINDING = 0x889F
    GL_READ_ONLY = 0x88B8
    GL_WRITE_ONLY = 0x88B9
    GL_READ_WRITE = 0x88BA
    GL_BUFFER_ACCESS = 0x88BB
    GL_BUFFER_MAPPED = 0x88BC
    GL_BUFFER_MAP_POINTER = 0x88BD
    GL_STREAM_DRAW = 0x88E0
    GL_STREAM_READ = 0x88E1
    GL_STREAM_COPY = 0x88E2
    GL_STATIC_DRAW = 0x88E4
    GL_STATIC_READ = 0x88E5
    GL_STATIC_COPY = 0x88E6
    GL_DYNAMIC_DRAW = 0x88E8
    GL_DYNAMIC_READ = 0x88E9
    GL_DYNAMIC_COPY = 0x88EA
    GL_SAMPLES_PASSED = 0x8914
    GL_SRC1_ALPHA = 0x8589
    GL_VERTEX_ARRAY_BUFFER_BINDING = 0x8896
    GL_NORMAL_ARRAY_BUFFER_BINDING = 0x8897
    GL_COLOR_ARRAY_BUFFER_BINDING = 0x8898
    GL_INDEX_ARRAY_BUFFER_BINDING = 0x8899
    GL_TEXTURE_COORD_ARRAY_BUFFER_BINDING = 0x889A
    GL_EDGE_FLAG_ARRAY_BUFFER_BINDING = 0x889B
    GL_SECONDARY_COLOR_ARRAY_BUFFER_BINDING = 0x889C
    GL_FOG_COORDINATE_ARRAY_BUFFER_BINDING = 0x889D
    GL_WEIGHT_ARRAY_BUFFER_BINDING = 0x889E
    GL_FOG_COORD_SRC = 0x8450
    GL_FOG_COORD = 0x8451
    GL_CURRENT_FOG_COORD = 0x8453
    GL_FOG_COORD_ARRAY_TYPE = 0x8454
    GL_FOG_COORD_ARRAY_STRIDE = 0x8455
    GL_FOG_COORD_ARRAY_POINTER = 0x8456
    GL_FOG_COORD_ARRAY = 0x8457
    GL_FOG_COORD_ARRAY_BUFFER_BINDING = 0x889D
    GL_SRC0_RGB = 0x8580
    GL_SRC1_RGB = 0x8581
    GL_SRC2_RGB = 0x8582
    GL_SRC0_ALPHA = 0x8588
    GL_SRC2_ALPHA = 0x858A

    #
    # Function/Command definitions
    #

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint))
    def glGenQueries(n: int, ids: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint))
    def glDeleteQueries(n: int, ids: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(GLboolean, GLuint)
    def glIsQuery(id: int) -> int: pass

    @GLExtAPI.method(VOID, GLenum, GLuint)
    def glBeginQuery(target: int, id: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum)
    def glEndQuery(target: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, PTR(GLint))
    def glGetQueryiv(target: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glGetQueryObjectiv(id: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLuint))
    def glGetQueryObjectuiv(id: int, pname: int, params: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint)
    def glBindBuffer(target: int, buffer: int) -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint))
    def glDeleteBuffers(n: int, buffers: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint))
    def glGenBuffers(n: int, buffers: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(GLboolean, GLuint)
    def glIsBuffer(buffer: int) -> int: pass

    @GLExtAPI.method(VOID, GLenum, GLsizeiptr, PTR(VOID), GLenum)
    def glBufferData(target: int, size: int, data: IPointer[int], usage: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLintptr, GLsizeiptr, PTR(VOID))
    def glBufferSubData(target: int, offset: int, size: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLintptr, GLsizeiptr, PTR(VOID))
    def glGetBufferSubData(target: int, offset: int, size: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(PTR(VOID), GLenum, GLenum)
    def glMapBuffer(target: int, access: int) -> IPointer[int]: pass

    @GLExtAPI.method(GLboolean, GLenum)
    def glUnmapBuffer(target: int) -> int: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, PTR(GLint))
    def glGetBufferParameteriv(target: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, PTR(PTR(VOID)))
    def glGetBufferPointerv(target: int, pname: int, params: IPointer[IPointer[int]]) -> None: pass

