#
# This file generated by a Win.Tools.GLGen generator as a part of the Win project.
# Definitions for the OpenGL gl_2.0, do not change this file
# Date/Time of a generation: Thu Aug 27 21:13:35 2026
#

# OpenGL Imports
from win.gl.gl import *
from win.gl.glu import *
from win.abs.glext import *

# Basic OpenGL Types definitions
khronos_int8_t = GLbyte
khronos_uint8_t = GLubyte
khronos_int16_t = GLshort
khornos_uint16_t = GLushort
GLclampx = UINT32
GLeglClientBufferEXT = PVOID
GLeglImageOES = PVOID
GLchar = CHAR
GLcharARB = CHAR
GLhandleARB = UINT
GLhalf = UINT16
GLhalfARB = UINT16
GLfixed = INT32
GLintptr = INT_PTR
GLintptrARB = INT_PTR
GLsizeiptr = SSIZE_T
GLsizeiptrARB = SSIZE_T
GLint64 = INT64
GLint64EXT = INT64
GLuint64 = UINT64
GLuint64EXT = UINT64
GLsync = PVOID
GLDEBUGPROC = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCARB = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCKHR = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCAMD = APIENTRY(VOID, GLuint, GLenum, GLenum, GLsizei, LPSTR, PVOID)
GLhalfNV = USHORT
GLvdpauSurfaceNV = GLintptr
GLVULKANPROCNV = APIENTRY(VOID)

class GL20:
    #
    # Enum definitions
    #

    GL_BLEND_EQUATION_RGB = 0x8009
    GL_VERTEX_ATTRIB_ARRAY_ENABLED = 0x8622
    GL_VERTEX_ATTRIB_ARRAY_SIZE = 0x8623
    GL_VERTEX_ATTRIB_ARRAY_STRIDE = 0x8624
    GL_VERTEX_ATTRIB_ARRAY_TYPE = 0x8625
    GL_CURRENT_VERTEX_ATTRIB = 0x8626
    GL_VERTEX_PROGRAM_POINT_SIZE = 0x8642
    GL_VERTEX_ATTRIB_ARRAY_POINTER = 0x8645
    GL_STENCIL_BACK_FUNC = 0x8800
    GL_STENCIL_BACK_FAIL = 0x8801
    GL_STENCIL_BACK_PASS_DEPTH_FAIL = 0x8802
    GL_STENCIL_BACK_PASS_DEPTH_PASS = 0x8803
    GL_MAX_DRAW_BUFFERS = 0x8824
    GL_DRAW_BUFFER0 = 0x8825
    GL_DRAW_BUFFER1 = 0x8826
    GL_DRAW_BUFFER2 = 0x8827
    GL_DRAW_BUFFER3 = 0x8828
    GL_DRAW_BUFFER4 = 0x8829
    GL_DRAW_BUFFER5 = 0x882A
    GL_DRAW_BUFFER6 = 0x882B
    GL_DRAW_BUFFER7 = 0x882C
    GL_DRAW_BUFFER8 = 0x882D
    GL_DRAW_BUFFER9 = 0x882E
    GL_DRAW_BUFFER10 = 0x882F
    GL_DRAW_BUFFER11 = 0x8830
    GL_DRAW_BUFFER12 = 0x8831
    GL_DRAW_BUFFER13 = 0x8832
    GL_DRAW_BUFFER14 = 0x8833
    GL_DRAW_BUFFER15 = 0x8834
    GL_BLEND_EQUATION_ALPHA = 0x883D
    GL_MAX_VERTEX_ATTRIBS = 0x8869
    GL_VERTEX_ATTRIB_ARRAY_NORMALIZED = 0x886A
    GL_MAX_TEXTURE_IMAGE_UNITS = 0x8872
    GL_FRAGMENT_SHADER = 0x8B30
    GL_VERTEX_SHADER = 0x8B31
    GL_MAX_FRAGMENT_UNIFORM_COMPONENTS = 0x8B49
    GL_MAX_VERTEX_UNIFORM_COMPONENTS = 0x8B4A
    GL_MAX_VARYING_FLOATS = 0x8B4B
    GL_MAX_VERTEX_TEXTURE_IMAGE_UNITS = 0x8B4C
    GL_MAX_COMBINED_TEXTURE_IMAGE_UNITS = 0x8B4D
    GL_SHADER_TYPE = 0x8B4F
    GL_FLOAT_VEC2 = 0x8B50
    GL_FLOAT_VEC3 = 0x8B51
    GL_FLOAT_VEC4 = 0x8B52
    GL_INT_VEC2 = 0x8B53
    GL_INT_VEC3 = 0x8B54
    GL_INT_VEC4 = 0x8B55
    GL_BOOL = 0x8B56
    GL_BOOL_VEC2 = 0x8B57
    GL_BOOL_VEC3 = 0x8B58
    GL_BOOL_VEC4 = 0x8B59
    GL_FLOAT_MAT2 = 0x8B5A
    GL_FLOAT_MAT3 = 0x8B5B
    GL_FLOAT_MAT4 = 0x8B5C
    GL_SAMPLER_1D = 0x8B5D
    GL_SAMPLER_2D = 0x8B5E
    GL_SAMPLER_3D = 0x8B5F
    GL_SAMPLER_CUBE = 0x8B60
    GL_SAMPLER_1D_SHADOW = 0x8B61
    GL_SAMPLER_2D_SHADOW = 0x8B62
    GL_DELETE_STATUS = 0x8B80
    GL_COMPILE_STATUS = 0x8B81
    GL_LINK_STATUS = 0x8B82
    GL_VALIDATE_STATUS = 0x8B83
    GL_INFO_LOG_LENGTH = 0x8B84
    GL_ATTACHED_SHADERS = 0x8B85
    GL_ACTIVE_UNIFORMS = 0x8B86
    GL_ACTIVE_UNIFORM_MAX_LENGTH = 0x8B87
    GL_SHADER_SOURCE_LENGTH = 0x8B88
    GL_ACTIVE_ATTRIBUTES = 0x8B89
    GL_ACTIVE_ATTRIBUTE_MAX_LENGTH = 0x8B8A
    GL_FRAGMENT_SHADER_DERIVATIVE_HINT = 0x8B8B
    GL_SHADING_LANGUAGE_VERSION = 0x8B8C
    GL_CURRENT_PROGRAM = 0x8B8D
    GL_POINT_SPRITE_COORD_ORIGIN = 0x8CA0
    GL_LOWER_LEFT = 0x8CA1
    GL_UPPER_LEFT = 0x8CA2
    GL_STENCIL_BACK_REF = 0x8CA3
    GL_STENCIL_BACK_VALUE_MASK = 0x8CA4
    GL_STENCIL_BACK_WRITEMASK = 0x8CA5
    GL_VERTEX_PROGRAM_TWO_SIDE = 0x8643
    GL_POINT_SPRITE = 0x8861
    GL_COORD_REPLACE = 0x8862
    GL_MAX_TEXTURE_COORDS = 0x8871

    #
    # Function/Command definitions
    #

    @GLExtAPI.method(VOID, GLenum, GLenum)
    def glBlendEquationSeparate(modeRGB: int, modeAlpha: int) -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLenum))
    def glDrawBuffers(n: int, bufs: IPointer[GLenum]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLenum, GLenum)
    def glStencilOpSeparate(face: int, sfail: int, dpfail: int, dppass: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLint, GLuint)
    def glStencilFuncSeparate(face: int, func: int, ref: int, mask: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint)
    def glStencilMaskSeparate(face: int, mask: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint)
    def glAttachShader(program: int, shader: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, PTR(GLchar))
    def glBindAttribLocation(program: int, index: int, name: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(VOID, GLuint)
    def glCompileShader(shader: int) -> None: pass

    @GLExtAPI.method(GLuint, )
    def glCreateProgram() -> int: pass

    @GLExtAPI.method(GLuint, GLenum)
    def glCreateShader(type: int) -> int: pass

    @GLExtAPI.method(VOID, GLuint)
    def glDeleteProgram(program: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint)
    def glDeleteShader(shader: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint)
    def glDetachShader(program: int, shader: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint)
    def glDisableVertexAttribArray(index: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint)
    def glEnableVertexAttribArray(index: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLsizei, PTR(GLsizei), PTR(GLint), PTR(GLenum), PTR(GLchar))
    def glGetActiveAttrib(program: int, index: int, bufSize: int, length: IPointer[GLsizei], size: IPointer[GLint], type: IPointer[GLenum], name: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLsizei, PTR(GLsizei), PTR(GLint), PTR(GLenum), PTR(GLchar))
    def glGetActiveUniform(program: int, index: int, bufSize: int, length: IPointer[GLsizei], size: IPointer[GLint], type: IPointer[GLenum], name: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(GLsizei), PTR(GLuint))
    def glGetAttachedShaders(program: int, maxCount: int, count: IPointer[GLsizei], shaders: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(GLint, GLuint, PTR(GLchar))
    def glGetAttribLocation(program: int, name: IPointer[GLchar]) -> int: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glGetProgramiv(program: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(GLsizei), PTR(GLchar))
    def glGetProgramInfoLog(program: int, bufSize: int, length: IPointer[GLsizei], infoLog: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glGetShaderiv(shader: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(GLsizei), PTR(GLchar))
    def glGetShaderInfoLog(shader: int, bufSize: int, length: IPointer[GLsizei], infoLog: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(GLsizei), PTR(GLchar))
    def glGetShaderSource(shader: int, bufSize: int, length: IPointer[GLsizei], source: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(GLint, GLuint, PTR(GLchar))
    def glGetUniformLocation(program: int, name: IPointer[GLchar]) -> int: pass

    @GLExtAPI.method(VOID, GLuint, GLint, PTR(GLfloat))
    def glGetUniformfv(program: int, location: int, params: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, PTR(GLint))
    def glGetUniformiv(program: int, location: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLdouble))
    def glGetVertexAttribdv(index: int, pname: int, params: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLfloat))
    def glGetVertexAttribfv(index: int, pname: int, params: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glGetVertexAttribiv(index: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(PTR(VOID)))
    def glGetVertexAttribPointerv(index: int, pname: int, pointer: IPointer[IPointer[int]]) -> None: pass

    @GLExtAPI.method(GLboolean, GLuint)
    def glIsProgram(program: int) -> int: pass

    @GLExtAPI.method(GLboolean, GLuint)
    def glIsShader(shader: int) -> int: pass

    @GLExtAPI.method(VOID, GLuint)
    def glLinkProgram(program: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(PTR(GLchar)), PTR(GLint))
    def glShaderSource(shader: int, count: int, string: IPointer[IPointer[GLchar]], length: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint)
    def glUseProgram(program: int) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLfloat)
    def glUniform1f(location: int, v0: float) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLfloat, GLfloat)
    def glUniform2f(location: int, v0: float, v1: float) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLfloat, GLfloat, GLfloat)
    def glUniform3f(location: int, v0: float, v1: float, v2: float) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLfloat, GLfloat, GLfloat, GLfloat)
    def glUniform4f(location: int, v0: float, v1: float, v2: float, v3: float) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLint)
    def glUniform1i(location: int, v0: int) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLint, GLint)
    def glUniform2i(location: int, v0: int, v1: int) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLint, GLint, GLint)
    def glUniform3i(location: int, v0: int, v1: int, v2: int) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLint, GLint, GLint, GLint)
    def glUniform4i(location: int, v0: int, v1: int, v2: int, v3: int) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, PTR(GLfloat))
    def glUniform1fv(location: int, count: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, PTR(GLfloat))
    def glUniform2fv(location: int, count: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, PTR(GLfloat))
    def glUniform3fv(location: int, count: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, PTR(GLfloat))
    def glUniform4fv(location: int, count: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, PTR(GLint))
    def glUniform1iv(location: int, count: int, value: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, PTR(GLint))
    def glUniform2iv(location: int, count: int, value: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, PTR(GLint))
    def glUniform3iv(location: int, count: int, value: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, PTR(GLint))
    def glUniform4iv(location: int, count: int, value: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glUniformMatrix2fv(location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glUniformMatrix3fv(location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glUniformMatrix4fv(location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint)
    def glValidateProgram(program: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLdouble)
    def glVertexAttrib1d(index: int, x: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLdouble))
    def glVertexAttrib1dv(index: int, v: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLfloat)
    def glVertexAttrib1f(index: int, x: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLfloat))
    def glVertexAttrib1fv(index: int, v: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLshort)
    def glVertexAttrib1s(index: int, x: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLshort))
    def glVertexAttrib1sv(index: int, v: IPointer[GLshort]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLdouble, GLdouble)
    def glVertexAttrib2d(index: int, x: float, y: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLdouble))
    def glVertexAttrib2dv(index: int, v: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLfloat, GLfloat)
    def glVertexAttrib2f(index: int, x: float, y: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLfloat))
    def glVertexAttrib2fv(index: int, v: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLshort, GLshort)
    def glVertexAttrib2s(index: int, x: int, y: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLshort))
    def glVertexAttrib2sv(index: int, v: IPointer[GLshort]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLdouble, GLdouble, GLdouble)
    def glVertexAttrib3d(index: int, x: float, y: float, z: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLdouble))
    def glVertexAttrib3dv(index: int, v: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLfloat, GLfloat, GLfloat)
    def glVertexAttrib3f(index: int, x: float, y: float, z: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLfloat))
    def glVertexAttrib3fv(index: int, v: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLshort, GLshort, GLshort)
    def glVertexAttrib3s(index: int, x: int, y: int, z: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLshort))
    def glVertexAttrib3sv(index: int, v: IPointer[GLshort]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLbyte))
    def glVertexAttrib4Nbv(index: int, v: IPointer[GLbyte]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLint))
    def glVertexAttrib4Niv(index: int, v: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLshort))
    def glVertexAttrib4Nsv(index: int, v: IPointer[GLshort]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLubyte, GLubyte, GLubyte, GLubyte)
    def glVertexAttrib4Nub(index: int, x: int, y: int, z: int, w: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLubyte))
    def glVertexAttrib4Nubv(index: int, v: IPointer[GLubyte]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLuint))
    def glVertexAttrib4Nuiv(index: int, v: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLushort))
    def glVertexAttrib4Nusv(index: int, v: IPointer[GLushort]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLbyte))
    def glVertexAttrib4bv(index: int, v: IPointer[GLbyte]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLdouble, GLdouble, GLdouble, GLdouble)
    def glVertexAttrib4d(index: int, x: float, y: float, z: float, w: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLdouble))
    def glVertexAttrib4dv(index: int, v: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLfloat, GLfloat, GLfloat, GLfloat)
    def glVertexAttrib4f(index: int, x: float, y: float, z: float, w: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLfloat))
    def glVertexAttrib4fv(index: int, v: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLint))
    def glVertexAttrib4iv(index: int, v: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLshort, GLshort, GLshort, GLshort)
    def glVertexAttrib4s(index: int, x: int, y: int, z: int, w: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLshort))
    def glVertexAttrib4sv(index: int, v: IPointer[GLshort]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLubyte))
    def glVertexAttrib4ubv(index: int, v: IPointer[GLubyte]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLuint))
    def glVertexAttrib4uiv(index: int, v: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLushort))
    def glVertexAttrib4usv(index: int, v: IPointer[GLushort]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLenum, GLboolean, GLsizei, PTR(VOID))
    def glVertexAttribPointer(index: int, size: int, type: int, normalized: int, stride: int, pointer: IPointer[int]) -> None: pass

