#
# This file generated by a Win.Tools.GLGen generator as a part of the Win project.
# Definitions for the OpenGL gl_2.1, do not change this file
# Date/Time of a generation: Thu Aug 27 21:13:35 2026
#

# OpenGL Imports
from win.gl.gl import *
from win.gl.glu import *
from win.abs.glext import *

# Basic OpenGL Types definitions
khronos_int8_t = GLbyte
khronos_uint8_t = GLubyte
khronos_int16_t = GLshort
khornos_uint16_t = GLushort
GLclampx = UINT32
GLeglClientBufferEXT = PVOID
GLeglImageOES = PVOID
GLchar = CHAR
GLcharARB = CHAR
GLhandleARB = UINT
GLhalf = UINT16
GLhalfARB = UINT16
GLfixed = INT32
GLintptr = INT_PTR
GLintptrARB = INT_PTR
GLsizeiptr = SSIZE_T
GLsizeiptrARB = SSIZE_T
GLint64 = INT64
GLint64EXT = INT64
GLuint64 = UINT64
GLuint64EXT = UINT64
GLsync = PVOID
GLDEBUGPROC = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCARB = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCKHR = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCAMD = APIENTRY(VOID, GLuint, GLenum, GLenum, GLsizei, LPSTR, PVOID)
GLhalfNV = USHORT
GLvdpauSurfaceNV = GLintptr
GLVULKANPROCNV = APIENTRY(VOID)

class GL21:
    #
    # Enum definitions
    #

    GL_PIXEL_PACK_BUFFER = 0x88EB
    GL_PIXEL_UNPACK_BUFFER = 0x88EC
    GL_PIXEL_PACK_BUFFER_BINDING = 0x88ED
    GL_PIXEL_UNPACK_BUFFER_BINDING = 0x88EF
    GL_FLOAT_MAT2x3 = 0x8B65
    GL_FLOAT_MAT2x4 = 0x8B66
    GL_FLOAT_MAT3x2 = 0x8B67
    GL_FLOAT_MAT3x4 = 0x8B68
    GL_FLOAT_MAT4x2 = 0x8B69
    GL_FLOAT_MAT4x3 = 0x8B6A
    GL_SRGB = 0x8C40
    GL_SRGB8 = 0x8C41
    GL_SRGB_ALPHA = 0x8C42
    GL_SRGB8_ALPHA8 = 0x8C43
    GL_COMPRESSED_SRGB = 0x8C48
    GL_COMPRESSED_SRGB_ALPHA = 0x8C49
    GL_CURRENT_RASTER_SECONDARY_COLOR = 0x845F
    GL_SLUMINANCE_ALPHA = 0x8C44
    GL_SLUMINANCE8_ALPHA8 = 0x8C45
    GL_SLUMINANCE = 0x8C46
    GL_SLUMINANCE8 = 0x8C47
    GL_COMPRESSED_SLUMINANCE = 0x8C4A
    GL_COMPRESSED_SLUMINANCE_ALPHA = 0x8C4B

    #
    # Function/Command definitions
    #

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glUniformMatrix2x3fv(location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glUniformMatrix3x2fv(location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glUniformMatrix2x4fv(location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glUniformMatrix4x2fv(location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glUniformMatrix3x4fv(location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glUniformMatrix4x3fv(location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

