#
# This file generated by a Win.Tools.GLGen generator as a part of the Win project.
# Definitions for the OpenGL gl_3.1, do not change this file
# Date/Time of a generation: Thu Aug 27 21:13:35 2026
#

# OpenGL Imports
from win.gl.gl import *
from win.gl.glu import *
from win.abs.glext import *

# Basic OpenGL Types definitions
khronos_int8_t = GLbyte
khronos_uint8_t = GLubyte
khronos_int16_t = GLshort
khornos_uint16_t = GLushort
GLclampx = UINT32
GLeglClientBufferEXT = PVOID
GLeglImageOES = PVOID
GLchar = CHAR
GLcharARB = CHAR
GLhandleARB = UINT
GLhalf = UINT16
GLhalfARB = UINT16
GLfixed = INT32
GLintptr = INT_PTR
GLintptrARB = INT_PTR
GLsizeiptr = SSIZE_T
GLsizeiptrARB = SSIZE_T
GLint64 = INT64
GLint64EXT = INT64
GLuint64 = UINT64
GLuint64EXT = UINT64
GLsync = PVOID
GLDEBUGPROC = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCARB = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCKHR = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCAMD = APIENTRY(VOID, GLuint, GLenum, GLenum, GLsizei, LPSTR, PVOID)
GLhalfNV = USHORT
GLvdpauSurfaceNV = GLintptr
GLVULKANPROCNV = APIENTRY(VOID)

class GL31:
    #
    # Enum definitions
    #

    GL_SAMPLER_2D_RECT = 0x8B63
    GL_SAMPLER_2D_RECT_SHADOW = 0x8B64
    GL_SAMPLER_BUFFER = 0x8DC2
    GL_INT_SAMPLER_2D_RECT = 0x8DCD
    GL_INT_SAMPLER_BUFFER = 0x8DD0
    GL_UNSIGNED_INT_SAMPLER_2D_RECT = 0x8DD5
    GL_UNSIGNED_INT_SAMPLER_BUFFER = 0x8DD8
    GL_TEXTURE_BUFFER = 0x8C2A
    GL_MAX_TEXTURE_BUFFER_SIZE = 0x8C2B
    GL_TEXTURE_BINDING_BUFFER = 0x8C2C
    GL_TEXTURE_BUFFER_DATA_STORE_BINDING = 0x8C2D
    GL_TEXTURE_RECTANGLE = 0x84F5
    GL_TEXTURE_BINDING_RECTANGLE = 0x84F6
    GL_PROXY_TEXTURE_RECTANGLE = 0x84F7
    GL_MAX_RECTANGLE_TEXTURE_SIZE = 0x84F8
    GL_R8_SNORM = 0x8F94
    GL_RG8_SNORM = 0x8F95
    GL_RGB8_SNORM = 0x8F96
    GL_RGBA8_SNORM = 0x8F97
    GL_R16_SNORM = 0x8F98
    GL_RG16_SNORM = 0x8F99
    GL_RGB16_SNORM = 0x8F9A
    GL_RGBA16_SNORM = 0x8F9B
    GL_SIGNED_NORMALIZED = 0x8F9C
    GL_PRIMITIVE_RESTART = 0x8F9D
    GL_PRIMITIVE_RESTART_INDEX = 0x8F9E
    GL_COPY_READ_BUFFER = 0x8F36
    GL_COPY_WRITE_BUFFER = 0x8F37
    GL_UNIFORM_BUFFER = 0x8A11
    GL_UNIFORM_BUFFER_BINDING = 0x8A28
    GL_UNIFORM_BUFFER_START = 0x8A29
    GL_UNIFORM_BUFFER_SIZE = 0x8A2A
    GL_MAX_VERTEX_UNIFORM_BLOCKS = 0x8A2B
    GL_MAX_GEOMETRY_UNIFORM_BLOCKS = 0x8A2C
    GL_MAX_FRAGMENT_UNIFORM_BLOCKS = 0x8A2D
    GL_MAX_COMBINED_UNIFORM_BLOCKS = 0x8A2E
    GL_MAX_UNIFORM_BUFFER_BINDINGS = 0x8A2F
    GL_MAX_UNIFORM_BLOCK_SIZE = 0x8A30
    GL_MAX_COMBINED_VERTEX_UNIFORM_COMPONENTS = 0x8A31
    GL_MAX_COMBINED_GEOMETRY_UNIFORM_COMPONENTS = 0x8A32
    GL_MAX_COMBINED_FRAGMENT_UNIFORM_COMPONENTS = 0x8A33
    GL_UNIFORM_BUFFER_OFFSET_ALIGNMENT = 0x8A34
    GL_ACTIVE_UNIFORM_BLOCK_MAX_NAME_LENGTH = 0x8A35
    GL_ACTIVE_UNIFORM_BLOCKS = 0x8A36
    GL_UNIFORM_TYPE = 0x8A37
    GL_UNIFORM_SIZE = 0x8A38
    GL_UNIFORM_NAME_LENGTH = 0x8A39
    GL_UNIFORM_BLOCK_INDEX = 0x8A3A
    GL_UNIFORM_OFFSET = 0x8A3B
    GL_UNIFORM_ARRAY_STRIDE = 0x8A3C
    GL_UNIFORM_MATRIX_STRIDE = 0x8A3D
    GL_UNIFORM_IS_ROW_MAJOR = 0x8A3E
    GL_UNIFORM_BLOCK_BINDING = 0x8A3F
    GL_UNIFORM_BLOCK_DATA_SIZE = 0x8A40
    GL_UNIFORM_BLOCK_NAME_LENGTH = 0x8A41
    GL_UNIFORM_BLOCK_ACTIVE_UNIFORMS = 0x8A42
    GL_UNIFORM_BLOCK_ACTIVE_UNIFORM_INDICES = 0x8A43
    GL_UNIFORM_BLOCK_REFERENCED_BY_VERTEX_SHADER = 0x8A44
    GL_UNIFORM_BLOCK_REFERENCED_BY_GEOMETRY_SHADER = 0x8A45
    GL_UNIFORM_BLOCK_REFERENCED_BY_FRAGMENT_SHADER = 0x8A46
    GL_INVALID_INDEX = 0xFFFFFFFF

    #
    # Function/Command definitions
    #

    @GLExtAPI.method(VOID, GLenum, GLint, GLsizei, GLsizei)
    def glDrawArraysInstanced(mode: int, first: int, count: int, instancecount: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLsizei, GLenum, PTR(VOID), GLsizei)
    def glDrawElementsInstanced(mode: int, count: int, type: int, indices: IPointer[int], instancecount: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLuint)
    def glTexBuffer(target: int, internalformat: int, buffer: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint)
    def glPrimitiveRestartIndex(index: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLintptr, GLintptr, GLsizeiptr)
    def glCopyBufferSubData(readTarget: int, writeTarget: int, readOffset: int, writeOffset: int, size: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(PTR(GLchar)), PTR(GLuint))
    def glGetUniformIndices(program: int, uniformCount: int, uniformNames: IPointer[IPointer[GLchar]], uniformIndices: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(GLuint), GLenum, PTR(GLint))
    def glGetActiveUniformsiv(program: int, uniformCount: int, uniformIndices: IPointer[GLuint], pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLsizei, PTR(GLsizei), PTR(GLchar))
    def glGetActiveUniformName(program: int, uniformIndex: int, bufSize: int, length: IPointer[GLsizei], uniformName: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(GLuint, GLuint, PTR(GLchar))
    def glGetUniformBlockIndex(program: int, uniformBlockName: IPointer[GLchar]) -> int: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLenum, PTR(GLint))
    def glGetActiveUniformBlockiv(program: int, uniformBlockIndex: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLsizei, PTR(GLsizei), PTR(GLchar))
    def glGetActiveUniformBlockName(program: int, uniformBlockIndex: int, bufSize: int, length: IPointer[GLsizei], uniformBlockName: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLuint)
    def glUniformBlockBinding(program: int, uniformBlockIndex: int, uniformBlockBinding: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint, GLuint, GLintptr, GLsizeiptr)
    def glBindBufferRange(target: int, index: int, buffer: int, offset: int, size: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint, GLuint)
    def glBindBufferBase(target: int, index: int, buffer: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint, PTR(GLint))
    def glGetIntegeri_v(target: int, index: int, data: IPointer[GLint]) -> None: pass

