#
# This file generated by a Win.Tools.GLGen generator as a part of the Win project.
# Definitions for the OpenGL gl_3.2, do not change this file
# Date/Time of a generation: Thu Aug 27 21:13:35 2026
#

# OpenGL Imports
from win.gl.gl import *
from win.gl.glu import *
from win.abs.glext import *

# Basic OpenGL Types definitions
khronos_int8_t = GLbyte
khronos_uint8_t = GLubyte
khronos_int16_t = GLshort
khornos_uint16_t = GLushort
GLclampx = UINT32
GLeglClientBufferEXT = PVOID
GLeglImageOES = PVOID
GLchar = CHAR
GLcharARB = CHAR
GLhandleARB = UINT
GLhalf = UINT16
GLhalfARB = UINT16
GLfixed = INT32
GLintptr = INT_PTR
GLintptrARB = INT_PTR
GLsizeiptr = SSIZE_T
GLsizeiptrARB = SSIZE_T
GLint64 = INT64
GLint64EXT = INT64
GLuint64 = UINT64
GLuint64EXT = UINT64
GLsync = PVOID
GLDEBUGPROC = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCARB = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCKHR = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCAMD = APIENTRY(VOID, GLuint, GLenum, GLenum, GLsizei, LPSTR, PVOID)
GLhalfNV = USHORT
GLvdpauSurfaceNV = GLintptr
GLVULKANPROCNV = APIENTRY(VOID)

class GL32:
    #
    # Enum definitions
    #

    GL_CONTEXT_CORE_PROFILE_BIT = 0x00000001
    GL_CONTEXT_COMPATIBILITY_PROFILE_BIT = 0x00000002
    GL_LINES_ADJACENCY = 0x000A
    GL_LINE_STRIP_ADJACENCY = 0x000B
    GL_TRIANGLES_ADJACENCY = 0x000C
    GL_TRIANGLE_STRIP_ADJACENCY = 0x000D
    GL_PROGRAM_POINT_SIZE = 0x8642
    GL_MAX_GEOMETRY_TEXTURE_IMAGE_UNITS = 0x8C29
    GL_FRAMEBUFFER_ATTACHMENT_LAYERED = 0x8DA7
    GL_FRAMEBUFFER_INCOMPLETE_LAYER_TARGETS = 0x8DA8
    GL_GEOMETRY_SHADER = 0x8DD9
    GL_GEOMETRY_VERTICES_OUT = 0x8916
    GL_GEOMETRY_INPUT_TYPE = 0x8917
    GL_GEOMETRY_OUTPUT_TYPE = 0x8918
    GL_MAX_GEOMETRY_UNIFORM_COMPONENTS = 0x8DDF
    GL_MAX_GEOMETRY_OUTPUT_VERTICES = 0x8DE0
    GL_MAX_GEOMETRY_TOTAL_OUTPUT_COMPONENTS = 0x8DE1
    GL_MAX_VERTEX_OUTPUT_COMPONENTS = 0x9122
    GL_MAX_GEOMETRY_INPUT_COMPONENTS = 0x9123
    GL_MAX_GEOMETRY_OUTPUT_COMPONENTS = 0x9124
    GL_MAX_FRAGMENT_INPUT_COMPONENTS = 0x9125
    GL_CONTEXT_PROFILE_MASK = 0x9126
    GL_DEPTH_CLAMP = 0x864F
    GL_QUADS_FOLLOW_PROVOKING_VERTEX_CONVENTION = 0x8E4C
    GL_FIRST_VERTEX_CONVENTION = 0x8E4D
    GL_LAST_VERTEX_CONVENTION = 0x8E4E
    GL_PROVOKING_VERTEX = 0x8E4F
    GL_TEXTURE_CUBE_MAP_SEAMLESS = 0x884F
    GL_MAX_SERVER_WAIT_TIMEOUT = 0x9111
    GL_OBJECT_TYPE = 0x9112
    GL_SYNC_CONDITION = 0x9113
    GL_SYNC_STATUS = 0x9114
    GL_SYNC_FLAGS = 0x9115
    GL_SYNC_FENCE = 0x9116
    GL_SYNC_GPU_COMMANDS_COMPLETE = 0x9117
    GL_UNSIGNALED = 0x9118
    GL_SIGNALED = 0x9119
    GL_ALREADY_SIGNALED = 0x911A
    GL_TIMEOUT_EXPIRED = 0x911B
    GL_CONDITION_SATISFIED = 0x911C
    GL_WAIT_FAILED = 0x911D
    GL_TIMEOUT_IGNORED = 0xFFFFFFFFFFFFFFFF
    GL_SYNC_FLUSH_COMMANDS_BIT = 0x00000001
    GL_SAMPLE_POSITION = 0x8E50
    GL_SAMPLE_MASK = 0x8E51
    GL_SAMPLE_MASK_VALUE = 0x8E52
    GL_MAX_SAMPLE_MASK_WORDS = 0x8E59
    GL_TEXTURE_2D_MULTISAMPLE = 0x9100
    GL_PROXY_TEXTURE_2D_MULTISAMPLE = 0x9101
    GL_TEXTURE_2D_MULTISAMPLE_ARRAY = 0x9102
    GL_PROXY_TEXTURE_2D_MULTISAMPLE_ARRAY = 0x9103
    GL_TEXTURE_BINDING_2D_MULTISAMPLE = 0x9104
    GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY = 0x9105
    GL_TEXTURE_SAMPLES = 0x9106
    GL_TEXTURE_FIXED_SAMPLE_LOCATIONS = 0x9107
    GL_SAMPLER_2D_MULTISAMPLE = 0x9108
    GL_INT_SAMPLER_2D_MULTISAMPLE = 0x9109
    GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE = 0x910A
    GL_SAMPLER_2D_MULTISAMPLE_ARRAY = 0x910B
    GL_INT_SAMPLER_2D_MULTISAMPLE_ARRAY = 0x910C
    GL_UNSIGNED_INT_SAMPLER_2D_MULTISAMPLE_ARRAY = 0x910D
    GL_MAX_COLOR_TEXTURE_SAMPLES = 0x910E
    GL_MAX_DEPTH_TEXTURE_SAMPLES = 0x910F
    GL_MAX_INTEGER_SAMPLES = 0x9110

    #
    # Function/Command definitions
    #

    @GLExtAPI.method(VOID, GLenum, GLsizei, GLenum, PTR(VOID), GLint)
    def glDrawElementsBaseVertex(mode: int, count: int, type: int, indices: IPointer[int], basevertex: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint, GLuint, GLsizei, GLenum, PTR(VOID), GLint)
    def glDrawRangeElementsBaseVertex(mode: int, start: int, end: int, count: int, type: int, indices: IPointer[int], basevertex: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLsizei, GLenum, PTR(VOID), GLsizei, GLint)
    def glDrawElementsInstancedBaseVertex(mode: int, count: int, type: int, indices: IPointer[int], instancecount: int, basevertex: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLsizei), GLenum, PTR(PTR(VOID)), GLsizei, PTR(GLint))
    def glMultiDrawElementsBaseVertex(mode: int, count: IPointer[GLsizei], type: int, indices: IPointer[IPointer[int]], drawcount: int, basevertex: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum)
    def glProvokingVertex(mode: int) -> None: pass

    @GLExtAPI.method(GLsync, GLenum, GLbitfield)
    def glFenceSync(condition: int, flags: int) -> int: pass

    @GLExtAPI.method(GLboolean, GLsync)
    def glIsSync(sync: int) -> int: pass

    @GLExtAPI.method(VOID, GLsync)
    def glDeleteSync(sync: int) -> None: pass

    @GLExtAPI.method(GLenum, GLsync, GLbitfield, GLuint64)
    def glClientWaitSync(sync: int, flags: int, timeout: int) -> int: pass

    @GLExtAPI.method(VOID, GLsync, GLbitfield, GLuint64)
    def glWaitSync(sync: int, flags: int, timeout: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLint64))
    def glGetInteger64v(pname: int, data: IPointer[GLint64]) -> None: pass

    @GLExtAPI.method(VOID, GLsync, GLenum, GLsizei, PTR(GLsizei), PTR(GLint))
    def glGetSynciv(sync: int, pname: int, count: int, length: IPointer[GLsizei], values: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint, PTR(GLint64))
    def glGetInteger64i_v(target: int, index: int, data: IPointer[GLint64]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, PTR(GLint64))
    def glGetBufferParameteri64v(target: int, pname: int, params: IPointer[GLint64]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLuint, GLint)
    def glFramebufferTexture(target: int, attachment: int, texture: int, level: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLsizei, GLenum, GLsizei, GLsizei, GLboolean)
    def glTexImage2DMultisample(target: int, samples: int, internalformat: int, width: int, height: int, fixedsamplelocations: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLsizei, GLenum, GLsizei, GLsizei, GLsizei, GLboolean)
    def glTexImage3DMultisample(target: int, samples: int, internalformat: int, width: int, height: int, depth: int, fixedsamplelocations: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint, PTR(GLfloat))
    def glGetMultisamplefv(pname: int, index: int, val: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLbitfield)
    def glSampleMaski(maskNumber: int, mask: int) -> None: pass

