#
# This file generated by a Win.Tools.GLGen generator as a part of the Win project.
# Definitions for the OpenGL gl_3.3, do not change this file
# Date/Time of a generation: Thu Aug 27 21:13:35 2026
#

# OpenGL Imports
from win.gl.gl import *
from win.gl.glu import *
from win.abs.glext import *

# Basic OpenGL Types definitions
khronos_int8_t = GLbyte
khronos_uint8_t = GLubyte
khronos_int16_t = GLshort
khornos_uint16_t = GLushort
GLclampx = UINT32
GLeglClientBufferEXT = PVOID
GLeglImageOES = PVOID
GLchar = CHAR
GLcharARB = CHAR
GLhandleARB = UINT
GLhalf = UINT16
GLhalfARB = UINT16
GLfixed = INT32
GLintptr = INT_PTR
GLintptrARB = INT_PTR
GLsizeiptr = SSIZE_T
GLsizeiptrARB = SSIZE_T
GLint64 = INT64
GLint64EXT = INT64
GLuint64 = UINT64
GLuint64EXT = UINT64
GLsync = PVOID
GLDEBUGPROC = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCARB = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCKHR = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCAMD = APIENTRY(VOID, GLuint, GLenum, GLenum, GLsizei, LPSTR, PVOID)
GLhalfNV = USHORT
GLvdpauSurfaceNV = GLintptr
GLVULKANPROCNV = APIENTRY(VOID)

class GL33:
    #
    # Enum definitions
    #

    GL_VERTEX_ATTRIB_ARRAY_DIVISOR = 0x88FE
    GL_SRC1_COLOR = 0x88F9
    GL_ONE_MINUS_SRC1_COLOR = 0x88FA
    GL_ONE_MINUS_SRC1_ALPHA = 0x88FB
    GL_MAX_DUAL_SOURCE_DRAW_BUFFERS = 0x88FC
    GL_ANY_SAMPLES_PASSED = 0x8C2F
    GL_SAMPLER_BINDING = 0x8919
    GL_RGB10_A2UI = 0x906F
    GL_TEXTURE_SWIZZLE_R = 0x8E42
    GL_TEXTURE_SWIZZLE_G = 0x8E43
    GL_TEXTURE_SWIZZLE_B = 0x8E44
    GL_TEXTURE_SWIZZLE_A = 0x8E45
    GL_TEXTURE_SWIZZLE_RGBA = 0x8E46
    GL_TIME_ELAPSED = 0x88BF
    GL_TIMESTAMP = 0x8E28
    GL_INT_2_10_10_10_REV = 0x8D9F

    #
    # Function/Command definitions
    #

    @GLExtAPI.method(VOID, GLuint, GLuint, GLuint, PTR(GLchar))
    def glBindFragDataLocationIndexed(program: int, colorNumber: int, index: int, name: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(GLint, GLuint, PTR(GLchar))
    def glGetFragDataIndex(program: int, name: IPointer[GLchar]) -> int: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint))
    def glGenSamplers(count: int, samplers: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint))
    def glDeleteSamplers(count: int, samplers: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(GLboolean, GLuint)
    def glIsSampler(sampler: int) -> int: pass

    @GLExtAPI.method(VOID, GLuint, GLuint)
    def glBindSampler(unit: int, sampler: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLint)
    def glSamplerParameteri(sampler: int, pname: int, param: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glSamplerParameteriv(sampler: int, pname: int, param: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLfloat)
    def glSamplerParameterf(sampler: int, pname: int, param: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLfloat))
    def glSamplerParameterfv(sampler: int, pname: int, param: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glSamplerParameterIiv(sampler: int, pname: int, param: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLuint))
    def glSamplerParameterIuiv(sampler: int, pname: int, param: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glGetSamplerParameteriv(sampler: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glGetSamplerParameterIiv(sampler: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLfloat))
    def glGetSamplerParameterfv(sampler: int, pname: int, params: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLuint))
    def glGetSamplerParameterIuiv(sampler: int, pname: int, params: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum)
    def glQueryCounter(id: int, target: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint64))
    def glGetQueryObjecti64v(id: int, pname: int, params: IPointer[GLint64]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLuint64))
    def glGetQueryObjectui64v(id: int, pname: int, params: IPointer[GLuint64]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint)
    def glVertexAttribDivisor(index: int, divisor: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLboolean, GLuint)
    def glVertexAttribP1ui(index: int, type: int, normalized: int, value: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLboolean, PTR(GLuint))
    def glVertexAttribP1uiv(index: int, type: int, normalized: int, value: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLboolean, GLuint)
    def glVertexAttribP2ui(index: int, type: int, normalized: int, value: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLboolean, PTR(GLuint))
    def glVertexAttribP2uiv(index: int, type: int, normalized: int, value: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLboolean, GLuint)
    def glVertexAttribP3ui(index: int, type: int, normalized: int, value: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLboolean, PTR(GLuint))
    def glVertexAttribP3uiv(index: int, type: int, normalized: int, value: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLboolean, GLuint)
    def glVertexAttribP4ui(index: int, type: int, normalized: int, value: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLboolean, PTR(GLuint))
    def glVertexAttribP4uiv(index: int, type: int, normalized: int, value: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint)
    def glVertexP2ui(type: int, value: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLuint))
    def glVertexP2uiv(type: int, value: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint)
    def glVertexP3ui(type: int, value: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLuint))
    def glVertexP3uiv(type: int, value: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint)
    def glVertexP4ui(type: int, value: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLuint))
    def glVertexP4uiv(type: int, value: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint)
    def glTexCoordP1ui(type: int, coords: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLuint))
    def glTexCoordP1uiv(type: int, coords: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint)
    def glTexCoordP2ui(type: int, coords: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLuint))
    def glTexCoordP2uiv(type: int, coords: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint)
    def glTexCoordP3ui(type: int, coords: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLuint))
    def glTexCoordP3uiv(type: int, coords: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint)
    def glTexCoordP4ui(type: int, coords: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLuint))
    def glTexCoordP4uiv(type: int, coords: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLuint)
    def glMultiTexCoordP1ui(texture: int, type: int, coords: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, PTR(GLuint))
    def glMultiTexCoordP1uiv(texture: int, type: int, coords: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLuint)
    def glMultiTexCoordP2ui(texture: int, type: int, coords: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, PTR(GLuint))
    def glMultiTexCoordP2uiv(texture: int, type: int, coords: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLuint)
    def glMultiTexCoordP3ui(texture: int, type: int, coords: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, PTR(GLuint))
    def glMultiTexCoordP3uiv(texture: int, type: int, coords: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLuint)
    def glMultiTexCoordP4ui(texture: int, type: int, coords: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, PTR(GLuint))
    def glMultiTexCoordP4uiv(texture: int, type: int, coords: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint)
    def glNormalP3ui(type: int, coords: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLuint))
    def glNormalP3uiv(type: int, coords: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint)
    def glColorP3ui(type: int, color: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLuint))
    def glColorP3uiv(type: int, color: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint)
    def glColorP4ui(type: int, color: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLuint))
    def glColorP4uiv(type: int, color: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint)
    def glSecondaryColorP3ui(type: int, color: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLuint))
    def glSecondaryColorP3uiv(type: int, color: IPointer[GLuint]) -> None: pass

