#
# This file generated by a Win.Tools.GLGen generator as a part of the Win project.
# Definitions for the OpenGL gl_4.0, do not change this file
# Date/Time of a generation: Thu Aug 27 21:13:35 2026
#

# OpenGL Imports
from win.gl.gl import *
from win.gl.glu import *
from win.abs.glext import *

# Basic OpenGL Types definitions
khronos_int8_t = GLbyte
khronos_uint8_t = GLubyte
khronos_int16_t = GLshort
khornos_uint16_t = GLushort
GLclampx = UINT32
GLeglClientBufferEXT = PVOID
GLeglImageOES = PVOID
GLchar = CHAR
GLcharARB = CHAR
GLhandleARB = UINT
GLhalf = UINT16
GLhalfARB = UINT16
GLfixed = INT32
GLintptr = INT_PTR
GLintptrARB = INT_PTR
GLsizeiptr = SSIZE_T
GLsizeiptrARB = SSIZE_T
GLint64 = INT64
GLint64EXT = INT64
GLuint64 = UINT64
GLuint64EXT = UINT64
GLsync = PVOID
GLDEBUGPROC = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCARB = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCKHR = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCAMD = APIENTRY(VOID, GLuint, GLenum, GLenum, GLsizei, LPSTR, PVOID)
GLhalfNV = USHORT
GLvdpauSurfaceNV = GLintptr
GLVULKANPROCNV = APIENTRY(VOID)

class GL40:
    #
    # Enum definitions
    #

    GL_SAMPLE_SHADING = 0x8C36
    GL_MIN_SAMPLE_SHADING_VALUE = 0x8C37
    GL_MIN_PROGRAM_TEXTURE_GATHER_OFFSET = 0x8E5E
    GL_MAX_PROGRAM_TEXTURE_GATHER_OFFSET = 0x8E5F
    GL_TEXTURE_CUBE_MAP_ARRAY = 0x9009
    GL_TEXTURE_BINDING_CUBE_MAP_ARRAY = 0x900A
    GL_PROXY_TEXTURE_CUBE_MAP_ARRAY = 0x900B
    GL_SAMPLER_CUBE_MAP_ARRAY = 0x900C
    GL_SAMPLER_CUBE_MAP_ARRAY_SHADOW = 0x900D
    GL_INT_SAMPLER_CUBE_MAP_ARRAY = 0x900E
    GL_UNSIGNED_INT_SAMPLER_CUBE_MAP_ARRAY = 0x900F
    GL_DRAW_INDIRECT_BUFFER = 0x8F3F
    GL_DRAW_INDIRECT_BUFFER_BINDING = 0x8F43
    GL_GEOMETRY_SHADER_INVOCATIONS = 0x887F
    GL_MAX_GEOMETRY_SHADER_INVOCATIONS = 0x8E5A
    GL_MIN_FRAGMENT_INTERPOLATION_OFFSET = 0x8E5B
    GL_MAX_FRAGMENT_INTERPOLATION_OFFSET = 0x8E5C
    GL_FRAGMENT_INTERPOLATION_OFFSET_BITS = 0x8E5D
    GL_MAX_VERTEX_STREAMS = 0x8E71
    GL_DOUBLE_VEC2 = 0x8FFC
    GL_DOUBLE_VEC3 = 0x8FFD
    GL_DOUBLE_VEC4 = 0x8FFE
    GL_DOUBLE_MAT2 = 0x8F46
    GL_DOUBLE_MAT3 = 0x8F47
    GL_DOUBLE_MAT4 = 0x8F48
    GL_DOUBLE_MAT2x3 = 0x8F49
    GL_DOUBLE_MAT2x4 = 0x8F4A
    GL_DOUBLE_MAT3x2 = 0x8F4B
    GL_DOUBLE_MAT3x4 = 0x8F4C
    GL_DOUBLE_MAT4x2 = 0x8F4D
    GL_DOUBLE_MAT4x3 = 0x8F4E
    GL_ACTIVE_SUBROUTINES = 0x8DE5
    GL_ACTIVE_SUBROUTINE_UNIFORMS = 0x8DE6
    GL_ACTIVE_SUBROUTINE_UNIFORM_LOCATIONS = 0x8E47
    GL_ACTIVE_SUBROUTINE_MAX_LENGTH = 0x8E48
    GL_ACTIVE_SUBROUTINE_UNIFORM_MAX_LENGTH = 0x8E49
    GL_MAX_SUBROUTINES = 0x8DE7
    GL_MAX_SUBROUTINE_UNIFORM_LOCATIONS = 0x8DE8
    GL_NUM_COMPATIBLE_SUBROUTINES = 0x8E4A
    GL_COMPATIBLE_SUBROUTINES = 0x8E4B
    GL_PATCHES = 0x000E
    GL_PATCH_VERTICES = 0x8E72
    GL_PATCH_DEFAULT_INNER_LEVEL = 0x8E73
    GL_PATCH_DEFAULT_OUTER_LEVEL = 0x8E74
    GL_TESS_CONTROL_OUTPUT_VERTICES = 0x8E75
    GL_TESS_GEN_MODE = 0x8E76
    GL_TESS_GEN_SPACING = 0x8E77
    GL_TESS_GEN_VERTEX_ORDER = 0x8E78
    GL_TESS_GEN_POINT_MODE = 0x8E79
    GL_ISOLINES = 0x8E7A
    GL_QUADS = 0x0007
    GL_FRACTIONAL_ODD = 0x8E7B
    GL_FRACTIONAL_EVEN = 0x8E7C
    GL_MAX_PATCH_VERTICES = 0x8E7D
    GL_MAX_TESS_GEN_LEVEL = 0x8E7E
    GL_MAX_TESS_CONTROL_UNIFORM_COMPONENTS = 0x8E7F
    GL_MAX_TESS_EVALUATION_UNIFORM_COMPONENTS = 0x8E80
    GL_MAX_TESS_CONTROL_TEXTURE_IMAGE_UNITS = 0x8E81
    GL_MAX_TESS_EVALUATION_TEXTURE_IMAGE_UNITS = 0x8E82
    GL_MAX_TESS_CONTROL_OUTPUT_COMPONENTS = 0x8E83
    GL_MAX_TESS_PATCH_COMPONENTS = 0x8E84
    GL_MAX_TESS_CONTROL_TOTAL_OUTPUT_COMPONENTS = 0x8E85
    GL_MAX_TESS_EVALUATION_OUTPUT_COMPONENTS = 0x8E86
    GL_MAX_TESS_CONTROL_UNIFORM_BLOCKS = 0x8E89
    GL_MAX_TESS_EVALUATION_UNIFORM_BLOCKS = 0x8E8A
    GL_MAX_TESS_CONTROL_INPUT_COMPONENTS = 0x886C
    GL_MAX_TESS_EVALUATION_INPUT_COMPONENTS = 0x886D
    GL_MAX_COMBINED_TESS_CONTROL_UNIFORM_COMPONENTS = 0x8E1E
    GL_MAX_COMBINED_TESS_EVALUATION_UNIFORM_COMPONENTS = 0x8E1F
    GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_CONTROL_SHADER = 0x84F0
    GL_UNIFORM_BLOCK_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x84F1
    GL_TESS_EVALUATION_SHADER = 0x8E87
    GL_TESS_CONTROL_SHADER = 0x8E88
    GL_TRANSFORM_FEEDBACK = 0x8E22
    GL_TRANSFORM_FEEDBACK_BUFFER_PAUSED = 0x8E23
    GL_TRANSFORM_FEEDBACK_BUFFER_ACTIVE = 0x8E24
    GL_TRANSFORM_FEEDBACK_BINDING = 0x8E25
    GL_MAX_TRANSFORM_FEEDBACK_BUFFERS = 0x8E70
    GL_MAX_VERTEX_STREAMS = 0x8E71

    #
    # Function/Command definitions
    #

    @GLExtAPI.method(VOID, GLfloat)
    def glMinSampleShading(value: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum)
    def glBlendEquationi(buf: int, mode: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLenum)
    def glBlendEquationSeparatei(buf: int, modeRGB: int, modeAlpha: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLenum)
    def glBlendFunci(buf: int, src: int, dst: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLenum, GLenum, GLenum)
    def glBlendFuncSeparatei(buf: int, srcRGB: int, dstRGB: int, srcAlpha: int, dstAlpha: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(VOID))
    def glDrawArraysIndirect(mode: int, indirect: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, PTR(VOID))
    def glDrawElementsIndirect(mode: int, type: int, indirect: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLdouble)
    def glUniform1d(location: int, x: float) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLdouble, GLdouble)
    def glUniform2d(location: int, x: float, y: float) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLdouble, GLdouble, GLdouble)
    def glUniform3d(location: int, x: float, y: float, z: float) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLdouble, GLdouble, GLdouble, GLdouble)
    def glUniform4d(location: int, x: float, y: float, z: float, w: float) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, PTR(GLdouble))
    def glUniform1dv(location: int, count: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, PTR(GLdouble))
    def glUniform2dv(location: int, count: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, PTR(GLdouble))
    def glUniform3dv(location: int, count: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, PTR(GLdouble))
    def glUniform4dv(location: int, count: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glUniformMatrix2dv(location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glUniformMatrix3dv(location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glUniformMatrix4dv(location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glUniformMatrix2x3dv(location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glUniformMatrix2x4dv(location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glUniformMatrix3x2dv(location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glUniformMatrix3x4dv(location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glUniformMatrix4x2dv(location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glUniformMatrix4x3dv(location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, PTR(GLdouble))
    def glGetUniformdv(program: int, location: int, params: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(GLint, GLuint, GLenum, PTR(GLchar))
    def glGetSubroutineUniformLocation(program: int, shadertype: int, name: IPointer[GLchar]) -> int: pass

    @GLExtAPI.method(GLuint, GLuint, GLenum, PTR(GLchar))
    def glGetSubroutineIndex(program: int, shadertype: int, name: IPointer[GLchar]) -> int: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLuint, GLenum, PTR(GLint))
    def glGetActiveSubroutineUniformiv(program: int, shadertype: int, index: int, pname: int, values: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLuint, GLsizei, PTR(GLsizei), PTR(GLchar))
    def glGetActiveSubroutineUniformName(program: int, shadertype: int, index: int, bufSize: int, length: IPointer[GLsizei], name: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLuint, GLsizei, PTR(GLsizei), PTR(GLchar))
    def glGetActiveSubroutineName(program: int, shadertype: int, index: int, bufSize: int, length: IPointer[GLsizei], name: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLsizei, PTR(GLuint))
    def glUniformSubroutinesuiv(shadertype: int, count: int, indices: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint, PTR(GLuint))
    def glGetUniformSubroutineuiv(shadertype: int, location: int, params: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLenum, PTR(GLint))
    def glGetProgramStageiv(program: int, shadertype: int, pname: int, values: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint)
    def glPatchParameteri(pname: int, value: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(GLfloat))
    def glPatchParameterfv(pname: int, values: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint)
    def glBindTransformFeedback(target: int, id: int) -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint))
    def glDeleteTransformFeedbacks(n: int, ids: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint))
    def glGenTransformFeedbacks(n: int, ids: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(GLboolean, GLuint)
    def glIsTransformFeedback(id: int) -> int: pass

    @GLExtAPI.method(VOID, )
    def glPauseTransformFeedback() -> None: pass

    @GLExtAPI.method(VOID, )
    def glResumeTransformFeedback() -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint)
    def glDrawTransformFeedback(mode: int, id: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint, GLuint)
    def glDrawTransformFeedbackStream(mode: int, id: int, stream: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint, GLuint)
    def glBeginQueryIndexed(target: int, index: int, id: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint)
    def glEndQueryIndexed(target: int, index: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint, GLenum, PTR(GLint))
    def glGetQueryIndexediv(target: int, index: int, pname: int, params: IPointer[GLint]) -> None: pass

