#
# This file generated by a Win.Tools.GLGen generator as a part of the Win project.
# Definitions for the OpenGL gl_4.1, do not change this file
# Date/Time of a generation: Thu Aug 27 21:13:35 2026
#

# OpenGL Imports
from win.gl.gl import *
from win.gl.glu import *
from win.abs.glext import *

# Basic OpenGL Types definitions
khronos_int8_t = GLbyte
khronos_uint8_t = GLubyte
khronos_int16_t = GLshort
khornos_uint16_t = GLushort
GLclampx = UINT32
GLeglClientBufferEXT = PVOID
GLeglImageOES = PVOID
GLchar = CHAR
GLcharARB = CHAR
GLhandleARB = UINT
GLhalf = UINT16
GLhalfARB = UINT16
GLfixed = INT32
GLintptr = INT_PTR
GLintptrARB = INT_PTR
GLsizeiptr = SSIZE_T
GLsizeiptrARB = SSIZE_T
GLint64 = INT64
GLint64EXT = INT64
GLuint64 = UINT64
GLuint64EXT = UINT64
GLsync = PVOID
GLDEBUGPROC = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCARB = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCKHR = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCAMD = APIENTRY(VOID, GLuint, GLenum, GLenum, GLsizei, LPSTR, PVOID)
GLhalfNV = USHORT
GLvdpauSurfaceNV = GLintptr
GLVULKANPROCNV = APIENTRY(VOID)

class GL41:
    #
    # Enum definitions
    #

    GL_FIXED = 0x140C
    GL_IMPLEMENTATION_COLOR_READ_TYPE = 0x8B9A
    GL_IMPLEMENTATION_COLOR_READ_FORMAT = 0x8B9B
    GL_LOW_FLOAT = 0x8DF0
    GL_MEDIUM_FLOAT = 0x8DF1
    GL_HIGH_FLOAT = 0x8DF2
    GL_LOW_INT = 0x8DF3
    GL_MEDIUM_INT = 0x8DF4
    GL_HIGH_INT = 0x8DF5
    GL_SHADER_COMPILER = 0x8DFA
    GL_SHADER_BINARY_FORMATS = 0x8DF8
    GL_NUM_SHADER_BINARY_FORMATS = 0x8DF9
    GL_MAX_VERTEX_UNIFORM_VECTORS = 0x8DFB
    GL_MAX_VARYING_VECTORS = 0x8DFC
    GL_MAX_FRAGMENT_UNIFORM_VECTORS = 0x8DFD
    GL_RGB565 = 0x8D62
    GL_PROGRAM_BINARY_RETRIEVABLE_HINT = 0x8257
    GL_PROGRAM_BINARY_LENGTH = 0x8741
    GL_NUM_PROGRAM_BINARY_FORMATS = 0x87FE
    GL_PROGRAM_BINARY_FORMATS = 0x87FF
    GL_VERTEX_SHADER_BIT = 0x00000001
    GL_FRAGMENT_SHADER_BIT = 0x00000002
    GL_GEOMETRY_SHADER_BIT = 0x00000004
    GL_TESS_CONTROL_SHADER_BIT = 0x00000008
    GL_TESS_EVALUATION_SHADER_BIT = 0x00000010
    GL_ALL_SHADER_BITS = 0xFFFFFFFF
    GL_PROGRAM_SEPARABLE = 0x8258
    GL_ACTIVE_PROGRAM = 0x8259
    GL_PROGRAM_PIPELINE_BINDING = 0x825A
    GL_MAX_VIEWPORTS = 0x825B
    GL_VIEWPORT_SUBPIXEL_BITS = 0x825C
    GL_VIEWPORT_BOUNDS_RANGE = 0x825D
    GL_LAYER_PROVOKING_VERTEX = 0x825E
    GL_VIEWPORT_INDEX_PROVOKING_VERTEX = 0x825F
    GL_UNDEFINED_VERTEX = 0x8260

    #
    # Function/Command definitions
    #

    @GLExtAPI.method(VOID, )
    def glReleaseShaderCompiler() -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint), GLenum, PTR(VOID), GLsizei)
    def glShaderBinary(count: int, shaders: IPointer[GLuint], binaryFormat: int, binary: IPointer[int], length: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, PTR(GLint), PTR(GLint))
    def glGetShaderPrecisionFormat(shadertype: int, precisiontype: int, range: IPointer[GLint], precision: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLfloat, GLfloat)
    def glDepthRangef(n: float, f: float) -> None: pass

    @GLExtAPI.method(VOID, GLfloat)
    def glClearDepthf(d: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(GLsizei), PTR(GLenum), PTR(VOID))
    def glGetProgramBinary(program: int, bufSize: int, length: IPointer[GLsizei], binaryFormat: IPointer[GLenum], binary: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(VOID), GLsizei)
    def glProgramBinary(program: int, binaryFormat: int, binary: IPointer[int], length: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLint)
    def glProgramParameteri(program: int, pname: int, value: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLbitfield, GLuint)
    def glUseProgramStages(pipeline: int, stages: int, program: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint)
    def glActiveShaderProgram(pipeline: int, program: int) -> None: pass

    @GLExtAPI.method(GLuint, GLenum, GLsizei, PTR(PTR(GLchar)))
    def glCreateShaderProgramv(type: int, count: int, strings: IPointer[IPointer[GLchar]]) -> int: pass

    @GLExtAPI.method(VOID, GLuint)
    def glBindProgramPipeline(pipeline: int) -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint))
    def glDeleteProgramPipelines(n: int, pipelines: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint))
    def glGenProgramPipelines(n: int, pipelines: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(GLboolean, GLuint)
    def glIsProgramPipeline(pipeline: int) -> int: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glGetProgramPipelineiv(pipeline: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLint)
    def glProgramParameteri(program: int, pname: int, value: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint)
    def glProgramUniform1i(program: int, location: int, v0: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLint))
    def glProgramUniform1iv(program: int, location: int, count: int, value: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLfloat)
    def glProgramUniform1f(program: int, location: int, v0: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLfloat))
    def glProgramUniform1fv(program: int, location: int, count: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLdouble)
    def glProgramUniform1d(program: int, location: int, v0: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLdouble))
    def glProgramUniform1dv(program: int, location: int, count: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLuint)
    def glProgramUniform1ui(program: int, location: int, v0: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLuint))
    def glProgramUniform1uiv(program: int, location: int, count: int, value: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint, GLint)
    def glProgramUniform2i(program: int, location: int, v0: int, v1: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLint))
    def glProgramUniform2iv(program: int, location: int, count: int, value: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLfloat, GLfloat)
    def glProgramUniform2f(program: int, location: int, v0: float, v1: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLfloat))
    def glProgramUniform2fv(program: int, location: int, count: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLdouble, GLdouble)
    def glProgramUniform2d(program: int, location: int, v0: float, v1: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLdouble))
    def glProgramUniform2dv(program: int, location: int, count: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLuint, GLuint)
    def glProgramUniform2ui(program: int, location: int, v0: int, v1: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLuint))
    def glProgramUniform2uiv(program: int, location: int, count: int, value: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint, GLint, GLint)
    def glProgramUniform3i(program: int, location: int, v0: int, v1: int, v2: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLint))
    def glProgramUniform3iv(program: int, location: int, count: int, value: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLfloat, GLfloat, GLfloat)
    def glProgramUniform3f(program: int, location: int, v0: float, v1: float, v2: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLfloat))
    def glProgramUniform3fv(program: int, location: int, count: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLdouble, GLdouble, GLdouble)
    def glProgramUniform3d(program: int, location: int, v0: float, v1: float, v2: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLdouble))
    def glProgramUniform3dv(program: int, location: int, count: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLuint, GLuint, GLuint)
    def glProgramUniform3ui(program: int, location: int, v0: int, v1: int, v2: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLuint))
    def glProgramUniform3uiv(program: int, location: int, count: int, value: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint, GLint, GLint, GLint)
    def glProgramUniform4i(program: int, location: int, v0: int, v1: int, v2: int, v3: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLint))
    def glProgramUniform4iv(program: int, location: int, count: int, value: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLfloat, GLfloat, GLfloat, GLfloat)
    def glProgramUniform4f(program: int, location: int, v0: float, v1: float, v2: float, v3: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLfloat))
    def glProgramUniform4fv(program: int, location: int, count: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLdouble, GLdouble, GLdouble, GLdouble)
    def glProgramUniform4d(program: int, location: int, v0: float, v1: float, v2: float, v3: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLdouble))
    def glProgramUniform4dv(program: int, location: int, count: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLuint, GLuint, GLuint, GLuint)
    def glProgramUniform4ui(program: int, location: int, v0: int, v1: int, v2: int, v3: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLuint))
    def glProgramUniform4uiv(program: int, location: int, count: int, value: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glProgramUniformMatrix2fv(program: int, location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glProgramUniformMatrix3fv(program: int, location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glProgramUniformMatrix4fv(program: int, location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glProgramUniformMatrix2dv(program: int, location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glProgramUniformMatrix3dv(program: int, location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glProgramUniformMatrix4dv(program: int, location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glProgramUniformMatrix2x3fv(program: int, location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glProgramUniformMatrix3x2fv(program: int, location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glProgramUniformMatrix2x4fv(program: int, location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glProgramUniformMatrix4x2fv(program: int, location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glProgramUniformMatrix3x4fv(program: int, location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLfloat))
    def glProgramUniformMatrix4x3fv(program: int, location: int, count: int, transpose: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glProgramUniformMatrix2x3dv(program: int, location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glProgramUniformMatrix3x2dv(program: int, location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glProgramUniformMatrix2x4dv(program: int, location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glProgramUniformMatrix4x2dv(program: int, location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glProgramUniformMatrix3x4dv(program: int, location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, GLboolean, PTR(GLdouble))
    def glProgramUniformMatrix4x3dv(program: int, location: int, count: int, transpose: int, value: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint)
    def glValidateProgramPipeline(pipeline: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(GLsizei), PTR(GLchar))
    def glGetProgramPipelineInfoLog(pipeline: int, bufSize: int, length: IPointer[GLsizei], infoLog: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLdouble)
    def glVertexAttribL1d(index: int, x: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLdouble, GLdouble)
    def glVertexAttribL2d(index: int, x: float, y: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLdouble, GLdouble, GLdouble)
    def glVertexAttribL3d(index: int, x: float, y: float, z: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLdouble, GLdouble, GLdouble, GLdouble)
    def glVertexAttribL4d(index: int, x: float, y: float, z: float, w: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLdouble))
    def glVertexAttribL1dv(index: int, v: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLdouble))
    def glVertexAttribL2dv(index: int, v: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLdouble))
    def glVertexAttribL3dv(index: int, v: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLdouble))
    def glVertexAttribL4dv(index: int, v: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLenum, GLsizei, PTR(VOID))
    def glVertexAttribLPointer(index: int, size: int, type: int, stride: int, pointer: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLdouble))
    def glGetVertexAttribLdv(index: int, pname: int, params: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(GLfloat))
    def glViewportArrayv(first: int, count: int, v: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLfloat, GLfloat, GLfloat, GLfloat)
    def glViewportIndexedf(index: int, x: float, y: float, w: float, h: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLfloat))
    def glViewportIndexedfv(index: int, v: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(GLint))
    def glScissorArrayv(first: int, count: int, v: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint, GLsizei, GLsizei)
    def glScissorIndexed(index: int, left: int, bottom: int, width: int, height: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, PTR(GLint))
    def glScissorIndexedv(index: int, v: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(GLdouble))
    def glDepthRangeArrayv(first: int, count: int, v: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLdouble, GLdouble)
    def glDepthRangeIndexed(index: int, n: float, f: float) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint, PTR(GLfloat))
    def glGetFloati_v(target: int, index: int, data: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint, PTR(GLdouble))
    def glGetDoublei_v(target: int, index: int, data: IPointer[GLdouble]) -> None: pass

