#
# This file generated by a Win.Tools.GLGen generator as a part of the Win project.
# Definitions for the OpenGL gl_4.3, do not change this file
# Date/Time of a generation: Thu Aug 27 21:13:35 2026
#

# OpenGL Imports
from win.gl.gl import *
from win.gl.glu import *
from win.abs.glext import *

# Basic OpenGL Types definitions
khronos_int8_t = GLbyte
khronos_uint8_t = GLubyte
khronos_int16_t = GLshort
khornos_uint16_t = GLushort
GLclampx = UINT32
GLeglClientBufferEXT = PVOID
GLeglImageOES = PVOID
GLchar = CHAR
GLcharARB = CHAR
GLhandleARB = UINT
GLhalf = UINT16
GLhalfARB = UINT16
GLfixed = INT32
GLintptr = INT_PTR
GLintptrARB = INT_PTR
GLsizeiptr = SSIZE_T
GLsizeiptrARB = SSIZE_T
GLint64 = INT64
GLint64EXT = INT64
GLuint64 = UINT64
GLuint64EXT = UINT64
GLsync = PVOID
GLDEBUGPROC = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCARB = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCKHR = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCAMD = APIENTRY(VOID, GLuint, GLenum, GLenum, GLsizei, LPSTR, PVOID)
GLhalfNV = USHORT
GLvdpauSurfaceNV = GLintptr
GLVULKANPROCNV = APIENTRY(VOID)

class GL43:
    #
    # Enum definitions
    #

    GL_NUM_SHADING_LANGUAGE_VERSIONS = 0x82E9
    GL_VERTEX_ATTRIB_ARRAY_LONG = 0x874E
    GL_COMPRESSED_RGB8_ETC2 = 0x9274
    GL_COMPRESSED_SRGB8_ETC2 = 0x9275
    GL_COMPRESSED_RGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x9276
    GL_COMPRESSED_SRGB8_PUNCHTHROUGH_ALPHA1_ETC2 = 0x9277
    GL_COMPRESSED_RGBA8_ETC2_EAC = 0x9278
    GL_COMPRESSED_SRGB8_ALPHA8_ETC2_EAC = 0x9279
    GL_COMPRESSED_R11_EAC = 0x9270
    GL_COMPRESSED_SIGNED_R11_EAC = 0x9271
    GL_COMPRESSED_RG11_EAC = 0x9272
    GL_COMPRESSED_SIGNED_RG11_EAC = 0x9273
    GL_PRIMITIVE_RESTART_FIXED_INDEX = 0x8D69
    GL_ANY_SAMPLES_PASSED_CONSERVATIVE = 0x8D6A
    GL_MAX_ELEMENT_INDEX = 0x8D6B
    GL_COMPUTE_SHADER = 0x91B9
    GL_MAX_COMPUTE_UNIFORM_BLOCKS = 0x91BB
    GL_MAX_COMPUTE_TEXTURE_IMAGE_UNITS = 0x91BC
    GL_MAX_COMPUTE_IMAGE_UNIFORMS = 0x91BD
    GL_MAX_COMPUTE_SHARED_MEMORY_SIZE = 0x8262
    GL_MAX_COMPUTE_UNIFORM_COMPONENTS = 0x8263
    GL_MAX_COMPUTE_ATOMIC_COUNTER_BUFFERS = 0x8264
    GL_MAX_COMPUTE_ATOMIC_COUNTERS = 0x8265
    GL_MAX_COMBINED_COMPUTE_UNIFORM_COMPONENTS = 0x8266
    GL_MAX_COMPUTE_WORK_GROUP_INVOCATIONS = 0x90EB
    GL_MAX_COMPUTE_WORK_GROUP_COUNT = 0x91BE
    GL_MAX_COMPUTE_WORK_GROUP_SIZE = 0x91BF
    GL_COMPUTE_WORK_GROUP_SIZE = 0x8267
    GL_UNIFORM_BLOCK_REFERENCED_BY_COMPUTE_SHADER = 0x90EC
    GL_ATOMIC_COUNTER_BUFFER_REFERENCED_BY_COMPUTE_SHADER = 0x90ED
    GL_DISPATCH_INDIRECT_BUFFER = 0x90EE
    GL_DISPATCH_INDIRECT_BUFFER_BINDING = 0x90EF
    GL_COMPUTE_SHADER_BIT = 0x00000020
    GL_DEBUG_OUTPUT_SYNCHRONOUS = 0x8242
    GL_DEBUG_NEXT_LOGGED_MESSAGE_LENGTH = 0x8243
    GL_DEBUG_CALLBACK_FUNCTION = 0x8244
    GL_DEBUG_CALLBACK_USER_PARAM = 0x8245
    GL_DEBUG_SOURCE_API = 0x8246
    GL_DEBUG_SOURCE_WINDOW_SYSTEM = 0x8247
    GL_DEBUG_SOURCE_SHADER_COMPILER = 0x8248
    GL_DEBUG_SOURCE_THIRD_PARTY = 0x8249
    GL_DEBUG_SOURCE_APPLICATION = 0x824A
    GL_DEBUG_SOURCE_OTHER = 0x824B
    GL_DEBUG_TYPE_ERROR = 0x824C
    GL_DEBUG_TYPE_DEPRECATED_BEHAVIOR = 0x824D
    GL_DEBUG_TYPE_UNDEFINED_BEHAVIOR = 0x824E
    GL_DEBUG_TYPE_PORTABILITY = 0x824F
    GL_DEBUG_TYPE_PERFORMANCE = 0x8250
    GL_DEBUG_TYPE_OTHER = 0x8251
    GL_MAX_DEBUG_MESSAGE_LENGTH = 0x9143
    GL_MAX_DEBUG_LOGGED_MESSAGES = 0x9144
    GL_DEBUG_LOGGED_MESSAGES = 0x9145
    GL_DEBUG_SEVERITY_HIGH = 0x9146
    GL_DEBUG_SEVERITY_MEDIUM = 0x9147
    GL_DEBUG_SEVERITY_LOW = 0x9148
    GL_DEBUG_TYPE_MARKER = 0x8268
    GL_DEBUG_TYPE_PUSH_GROUP = 0x8269
    GL_DEBUG_TYPE_POP_GROUP = 0x826A
    GL_DEBUG_SEVERITY_NOTIFICATION = 0x826B
    GL_MAX_DEBUG_GROUP_STACK_DEPTH = 0x826C
    GL_DEBUG_GROUP_STACK_DEPTH = 0x826D
    GL_BUFFER = 0x82E0
    GL_SHADER = 0x82E1
    GL_PROGRAM = 0x82E2
    GL_VERTEX_ARRAY = 0x8074
    GL_QUERY = 0x82E3
    GL_PROGRAM_PIPELINE = 0x82E4
    GL_SAMPLER = 0x82E6
    GL_MAX_LABEL_LENGTH = 0x82E8
    GL_DEBUG_OUTPUT = 0x92E0
    GL_CONTEXT_FLAG_DEBUG_BIT = 0x00000002
    GL_MAX_UNIFORM_LOCATIONS = 0x826E
    GL_FRAMEBUFFER_DEFAULT_WIDTH = 0x9310
    GL_FRAMEBUFFER_DEFAULT_HEIGHT = 0x9311
    GL_FRAMEBUFFER_DEFAULT_LAYERS = 0x9312
    GL_FRAMEBUFFER_DEFAULT_SAMPLES = 0x9313
    GL_FRAMEBUFFER_DEFAULT_FIXED_SAMPLE_LOCATIONS = 0x9314
    GL_MAX_FRAMEBUFFER_WIDTH = 0x9315
    GL_MAX_FRAMEBUFFER_HEIGHT = 0x9316
    GL_MAX_FRAMEBUFFER_LAYERS = 0x9317
    GL_MAX_FRAMEBUFFER_SAMPLES = 0x9318
    GL_INTERNALFORMAT_SUPPORTED = 0x826F
    GL_INTERNALFORMAT_PREFERRED = 0x8270
    GL_INTERNALFORMAT_RED_SIZE = 0x8271
    GL_INTERNALFORMAT_GREEN_SIZE = 0x8272
    GL_INTERNALFORMAT_BLUE_SIZE = 0x8273
    GL_INTERNALFORMAT_ALPHA_SIZE = 0x8274
    GL_INTERNALFORMAT_DEPTH_SIZE = 0x8275
    GL_INTERNALFORMAT_STENCIL_SIZE = 0x8276
    GL_INTERNALFORMAT_SHARED_SIZE = 0x8277
    GL_INTERNALFORMAT_RED_TYPE = 0x8278
    GL_INTERNALFORMAT_GREEN_TYPE = 0x8279
    GL_INTERNALFORMAT_BLUE_TYPE = 0x827A
    GL_INTERNALFORMAT_ALPHA_TYPE = 0x827B
    GL_INTERNALFORMAT_DEPTH_TYPE = 0x827C
    GL_INTERNALFORMAT_STENCIL_TYPE = 0x827D
    GL_MAX_WIDTH = 0x827E
    GL_MAX_HEIGHT = 0x827F
    GL_MAX_DEPTH = 0x8280
    GL_MAX_LAYERS = 0x8281
    GL_MAX_COMBINED_DIMENSIONS = 0x8282
    GL_COLOR_COMPONENTS = 0x8283
    GL_DEPTH_COMPONENTS = 0x8284
    GL_STENCIL_COMPONENTS = 0x8285
    GL_COLOR_RENDERABLE = 0x8286
    GL_DEPTH_RENDERABLE = 0x8287
    GL_STENCIL_RENDERABLE = 0x8288
    GL_FRAMEBUFFER_RENDERABLE = 0x8289
    GL_FRAMEBUFFER_RENDERABLE_LAYERED = 0x828A
    GL_FRAMEBUFFER_BLEND = 0x828B
    GL_READ_PIXELS = 0x828C
    GL_READ_PIXELS_FORMAT = 0x828D
    GL_READ_PIXELS_TYPE = 0x828E
    GL_TEXTURE_IMAGE_FORMAT = 0x828F
    GL_TEXTURE_IMAGE_TYPE = 0x8290
    GL_GET_TEXTURE_IMAGE_FORMAT = 0x8291
    GL_GET_TEXTURE_IMAGE_TYPE = 0x8292
    GL_MIPMAP = 0x8293
    GL_MANUAL_GENERATE_MIPMAP = 0x8294
    GL_AUTO_GENERATE_MIPMAP = 0x8295
    GL_COLOR_ENCODING = 0x8296
    GL_SRGB_READ = 0x8297
    GL_SRGB_WRITE = 0x8298
    GL_FILTER = 0x829A
    GL_VERTEX_TEXTURE = 0x829B
    GL_TESS_CONTROL_TEXTURE = 0x829C
    GL_TESS_EVALUATION_TEXTURE = 0x829D
    GL_GEOMETRY_TEXTURE = 0x829E
    GL_FRAGMENT_TEXTURE = 0x829F
    GL_COMPUTE_TEXTURE = 0x82A0
    GL_TEXTURE_SHADOW = 0x82A1
    GL_TEXTURE_GATHER = 0x82A2
    GL_TEXTURE_GATHER_SHADOW = 0x82A3
    GL_SHADER_IMAGE_LOAD = 0x82A4
    GL_SHADER_IMAGE_STORE = 0x82A5
    GL_SHADER_IMAGE_ATOMIC = 0x82A6
    GL_IMAGE_TEXEL_SIZE = 0x82A7
    GL_IMAGE_COMPATIBILITY_CLASS = 0x82A8
    GL_IMAGE_PIXEL_FORMAT = 0x82A9
    GL_IMAGE_PIXEL_TYPE = 0x82AA
    GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_TEST = 0x82AC
    GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_TEST = 0x82AD
    GL_SIMULTANEOUS_TEXTURE_AND_DEPTH_WRITE = 0x82AE
    GL_SIMULTANEOUS_TEXTURE_AND_STENCIL_WRITE = 0x82AF
    GL_TEXTURE_COMPRESSED_BLOCK_WIDTH = 0x82B1
    GL_TEXTURE_COMPRESSED_BLOCK_HEIGHT = 0x82B2
    GL_TEXTURE_COMPRESSED_BLOCK_SIZE = 0x82B3
    GL_CLEAR_BUFFER = 0x82B4
    GL_TEXTURE_VIEW = 0x82B5
    GL_VIEW_COMPATIBILITY_CLASS = 0x82B6
    GL_FULL_SUPPORT = 0x82B7
    GL_CAVEAT_SUPPORT = 0x82B8
    GL_IMAGE_CLASS_4_X_32 = 0x82B9
    GL_IMAGE_CLASS_2_X_32 = 0x82BA
    GL_IMAGE_CLASS_1_X_32 = 0x82BB
    GL_IMAGE_CLASS_4_X_16 = 0x82BC
    GL_IMAGE_CLASS_2_X_16 = 0x82BD
    GL_IMAGE_CLASS_1_X_16 = 0x82BE
    GL_IMAGE_CLASS_4_X_8 = 0x82BF
    GL_IMAGE_CLASS_2_X_8 = 0x82C0
    GL_IMAGE_CLASS_1_X_8 = 0x82C1
    GL_IMAGE_CLASS_11_11_10 = 0x82C2
    GL_IMAGE_CLASS_10_10_10_2 = 0x82C3
    GL_VIEW_CLASS_128_BITS = 0x82C4
    GL_VIEW_CLASS_96_BITS = 0x82C5
    GL_VIEW_CLASS_64_BITS = 0x82C6
    GL_VIEW_CLASS_48_BITS = 0x82C7
    GL_VIEW_CLASS_32_BITS = 0x82C8
    GL_VIEW_CLASS_24_BITS = 0x82C9
    GL_VIEW_CLASS_16_BITS = 0x82CA
    GL_VIEW_CLASS_8_BITS = 0x82CB
    GL_VIEW_CLASS_S3TC_DXT1_RGB = 0x82CC
    GL_VIEW_CLASS_S3TC_DXT1_RGBA = 0x82CD
    GL_VIEW_CLASS_S3TC_DXT3_RGBA = 0x82CE
    GL_VIEW_CLASS_S3TC_DXT5_RGBA = 0x82CF
    GL_VIEW_CLASS_RGTC1_RED = 0x82D0
    GL_VIEW_CLASS_RGTC2_RG = 0x82D1
    GL_VIEW_CLASS_BPTC_UNORM = 0x82D2
    GL_VIEW_CLASS_BPTC_FLOAT = 0x82D3
    GL_UNIFORM = 0x92E1
    GL_UNIFORM_BLOCK = 0x92E2
    GL_PROGRAM_INPUT = 0x92E3
    GL_PROGRAM_OUTPUT = 0x92E4
    GL_BUFFER_VARIABLE = 0x92E5
    GL_SHADER_STORAGE_BLOCK = 0x92E6
    GL_VERTEX_SUBROUTINE = 0x92E8
    GL_TESS_CONTROL_SUBROUTINE = 0x92E9
    GL_TESS_EVALUATION_SUBROUTINE = 0x92EA
    GL_GEOMETRY_SUBROUTINE = 0x92EB
    GL_FRAGMENT_SUBROUTINE = 0x92EC
    GL_COMPUTE_SUBROUTINE = 0x92ED
    GL_VERTEX_SUBROUTINE_UNIFORM = 0x92EE
    GL_TESS_CONTROL_SUBROUTINE_UNIFORM = 0x92EF
    GL_TESS_EVALUATION_SUBROUTINE_UNIFORM = 0x92F0
    GL_GEOMETRY_SUBROUTINE_UNIFORM = 0x92F1
    GL_FRAGMENT_SUBROUTINE_UNIFORM = 0x92F2
    GL_COMPUTE_SUBROUTINE_UNIFORM = 0x92F3
    GL_TRANSFORM_FEEDBACK_VARYING = 0x92F4
    GL_ACTIVE_RESOURCES = 0x92F5
    GL_MAX_NAME_LENGTH = 0x92F6
    GL_MAX_NUM_ACTIVE_VARIABLES = 0x92F7
    GL_MAX_NUM_COMPATIBLE_SUBROUTINES = 0x92F8
    GL_NAME_LENGTH = 0x92F9
    GL_TYPE = 0x92FA
    GL_ARRAY_SIZE = 0x92FB
    GL_OFFSET = 0x92FC
    GL_BLOCK_INDEX = 0x92FD
    GL_ARRAY_STRIDE = 0x92FE
    GL_MATRIX_STRIDE = 0x92FF
    GL_IS_ROW_MAJOR = 0x9300
    GL_ATOMIC_COUNTER_BUFFER_INDEX = 0x9301
    GL_BUFFER_BINDING = 0x9302
    GL_BUFFER_DATA_SIZE = 0x9303
    GL_NUM_ACTIVE_VARIABLES = 0x9304
    GL_ACTIVE_VARIABLES = 0x9305
    GL_REFERENCED_BY_VERTEX_SHADER = 0x9306
    GL_REFERENCED_BY_TESS_CONTROL_SHADER = 0x9307
    GL_REFERENCED_BY_TESS_EVALUATION_SHADER = 0x9308
    GL_REFERENCED_BY_GEOMETRY_SHADER = 0x9309
    GL_REFERENCED_BY_FRAGMENT_SHADER = 0x930A
    GL_REFERENCED_BY_COMPUTE_SHADER = 0x930B
    GL_TOP_LEVEL_ARRAY_SIZE = 0x930C
    GL_TOP_LEVEL_ARRAY_STRIDE = 0x930D
    GL_LOCATION = 0x930E
    GL_LOCATION_INDEX = 0x930F
    GL_IS_PER_PATCH = 0x92E7
    GL_SHADER_STORAGE_BUFFER = 0x90D2
    GL_SHADER_STORAGE_BUFFER_BINDING = 0x90D3
    GL_SHADER_STORAGE_BUFFER_START = 0x90D4
    GL_SHADER_STORAGE_BUFFER_SIZE = 0x90D5
    GL_MAX_VERTEX_SHADER_STORAGE_BLOCKS = 0x90D6
    GL_MAX_GEOMETRY_SHADER_STORAGE_BLOCKS = 0x90D7
    GL_MAX_TESS_CONTROL_SHADER_STORAGE_BLOCKS = 0x90D8
    GL_MAX_TESS_EVALUATION_SHADER_STORAGE_BLOCKS = 0x90D9
    GL_MAX_FRAGMENT_SHADER_STORAGE_BLOCKS = 0x90DA
    GL_MAX_COMPUTE_SHADER_STORAGE_BLOCKS = 0x90DB
    GL_MAX_COMBINED_SHADER_STORAGE_BLOCKS = 0x90DC
    GL_MAX_SHADER_STORAGE_BUFFER_BINDINGS = 0x90DD
    GL_MAX_SHADER_STORAGE_BLOCK_SIZE = 0x90DE
    GL_SHADER_STORAGE_BUFFER_OFFSET_ALIGNMENT = 0x90DF
    GL_SHADER_STORAGE_BARRIER_BIT = 0x00002000
    GL_MAX_COMBINED_SHADER_OUTPUT_RESOURCES = 0x8F39
    GL_DEPTH_STENCIL_TEXTURE_MODE = 0x90EA
    GL_TEXTURE_BUFFER_OFFSET = 0x919D
    GL_TEXTURE_BUFFER_SIZE = 0x919E
    GL_TEXTURE_BUFFER_OFFSET_ALIGNMENT = 0x919F
    GL_TEXTURE_VIEW_MIN_LEVEL = 0x82DB
    GL_TEXTURE_VIEW_NUM_LEVELS = 0x82DC
    GL_TEXTURE_VIEW_MIN_LAYER = 0x82DD
    GL_TEXTURE_VIEW_NUM_LAYERS = 0x82DE
    GL_TEXTURE_IMMUTABLE_LEVELS = 0x82DF
    GL_VERTEX_ATTRIB_BINDING = 0x82D4
    GL_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x82D5
    GL_VERTEX_BINDING_DIVISOR = 0x82D6
    GL_VERTEX_BINDING_OFFSET = 0x82D7
    GL_VERTEX_BINDING_STRIDE = 0x82D8
    GL_MAX_VERTEX_ATTRIB_RELATIVE_OFFSET = 0x82D9
    GL_MAX_VERTEX_ATTRIB_BINDINGS = 0x82DA
    GL_VERTEX_BINDING_BUFFER = 0x8F4F
    GL_DISPLAY_LIST = 0x82E7
    GL_STACK_UNDERFLOW = 0x0504
    GL_STACK_OVERFLOW = 0x0503

    #
    # Function/Command definitions
    #

    @GLExtAPI.method(VOID, GLenum, GLenum, GLenum, GLenum, PTR(VOID))
    def glClearBufferData(target: int, internalformat: int, format: int, type: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLintptr, GLsizeiptr, GLenum, GLenum, PTR(VOID))
    def glClearBufferSubData(target: int, internalformat: int, offset: int, size: int, format: int, type: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLuint)
    def glDispatchCompute(num_groups_x: int, num_groups_y: int, num_groups_z: int) -> None: pass

    @GLExtAPI.method(VOID, GLintptr)
    def glDispatchComputeIndirect(indirect: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLint, GLint, GLint, GLint, GLuint, GLenum, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei)
    def glCopyImageSubData(srcName: int, srcTarget: int, srcLevel: int, srcX: int, srcY: int, srcZ: int, dstName: int, dstTarget: int, dstLevel: int, dstX: int, dstY: int, dstZ: int, srcWidth: int, srcHeight: int, srcDepth: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLint)
    def glFramebufferParameteri(target: int, pname: int, param: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, PTR(GLint))
    def glGetFramebufferParameteriv(target: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLenum, GLsizei, PTR(GLint64))
    def glGetInternalformati64v(target: int, internalformat: int, pname: int, count: int, params: IPointer[GLint64]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei)
    def glInvalidateTexSubImage(texture: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint)
    def glInvalidateTexImage(texture: int, level: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLintptr, GLsizeiptr)
    def glInvalidateBufferSubData(buffer: int, offset: int, length: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint)
    def glInvalidateBufferData(buffer: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLsizei, PTR(GLenum))
    def glInvalidateFramebuffer(target: int, numAttachments: int, attachments: IPointer[GLenum]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLsizei, PTR(GLenum), GLint, GLint, GLsizei, GLsizei)
    def glInvalidateSubFramebuffer(target: int, numAttachments: int, attachments: IPointer[GLenum], x: int, y: int, width: int, height: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(VOID), GLsizei, GLsizei)
    def glMultiDrawArraysIndirect(mode: int, indirect: IPointer[int], drawcount: int, stride: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, PTR(VOID), GLsizei, GLsizei)
    def glMultiDrawElementsIndirect(mode: int, type: int, indirect: IPointer[int], drawcount: int, stride: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLenum, PTR(GLint))
    def glGetProgramInterfaceiv(program: int, programInterface: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(GLuint, GLuint, GLenum, PTR(GLchar))
    def glGetProgramResourceIndex(program: int, programInterface: int, name: IPointer[GLchar]) -> int: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLuint, GLsizei, PTR(GLsizei), PTR(GLchar))
    def glGetProgramResourceName(program: int, programInterface: int, index: int, bufSize: int, length: IPointer[GLsizei], name: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLuint, GLsizei, PTR(GLenum), GLsizei, PTR(GLsizei), PTR(GLint))
    def glGetProgramResourceiv(program: int, programInterface: int, index: int, propCount: int, props: IPointer[GLenum], count: int, length: IPointer[GLsizei], params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(GLint, GLuint, GLenum, PTR(GLchar))
    def glGetProgramResourceLocation(program: int, programInterface: int, name: IPointer[GLchar]) -> int: pass

    @GLExtAPI.method(GLint, GLuint, GLenum, PTR(GLchar))
    def glGetProgramResourceLocationIndex(program: int, programInterface: int, name: IPointer[GLchar]) -> int: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLuint)
    def glShaderStorageBlockBinding(program: int, storageBlockIndex: int, storageBlockBinding: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLuint, GLintptr, GLsizeiptr)
    def glTexBufferRange(target: int, internalformat: int, buffer: int, offset: int, size: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLsizei, GLenum, GLsizei, GLsizei, GLboolean)
    def glTexStorage2DMultisample(target: int, samples: int, internalformat: int, width: int, height: int, fixedsamplelocations: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLsizei, GLenum, GLsizei, GLsizei, GLsizei, GLboolean)
    def glTexStorage3DMultisample(target: int, samples: int, internalformat: int, width: int, height: int, depth: int, fixedsamplelocations: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLuint, GLenum, GLuint, GLuint, GLuint, GLuint)
    def glTextureView(texture: int, target: int, origtexture: int, internalformat: int, minlevel: int, numlevels: int, minlayer: int, numlayers: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLintptr, GLsizei)
    def glBindVertexBuffer(bindingindex: int, buffer: int, offset: int, stride: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLenum, GLboolean, GLuint)
    def glVertexAttribFormat(attribindex: int, size: int, type: int, normalized: int, relativeoffset: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLenum, GLuint)
    def glVertexAttribIFormat(attribindex: int, size: int, type: int, relativeoffset: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLenum, GLuint)
    def glVertexAttribLFormat(attribindex: int, size: int, type: int, relativeoffset: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint)
    def glVertexAttribBinding(attribindex: int, bindingindex: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint)
    def glVertexBindingDivisor(bindingindex: int, divisor: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLenum, GLsizei, PTR(GLuint), GLboolean)
    def glDebugMessageControl(source: int, type: int, severity: int, count: int, ids: IPointer[GLuint], enabled: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, PTR(GLchar))
    def glDebugMessageInsert(source: int, type: int, id: int, severity: int, length: int, buf: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(VOID, GLDEBUGPROC, PTR(VOID))
    def glDebugMessageCallback(callback: FARPROC, userParam: IPointer[int]) -> None: pass

    @GLExtAPI.method(GLuint, GLuint, GLsizei, PTR(GLenum), PTR(GLenum), PTR(GLuint), PTR(GLenum), PTR(GLsizei), PTR(GLchar))
    def glGetDebugMessageLog(count: int, bufSize: int, sources: IPointer[GLenum], types: IPointer[GLenum], ids: IPointer[GLuint], severities: IPointer[GLenum], lengths: IPointer[GLsizei], messageLog: IPointer[GLchar]) -> int: pass

    @GLExtAPI.method(VOID, GLenum, GLuint, GLsizei, PTR(GLchar))
    def glPushDebugGroup(source: int, id: int, length: int, message: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(VOID, )
    def glPopDebugGroup() -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint, GLsizei, PTR(GLchar))
    def glObjectLabel(identifier: int, name: int, length: int, label: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint, GLsizei, PTR(GLsizei), PTR(GLchar))
    def glGetObjectLabel(identifier: int, name: int, bufSize: int, length: IPointer[GLsizei], label: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(VOID, PTR(VOID), GLsizei, PTR(GLchar))
    def glObjectPtrLabel(ptr: IPointer[int], length: int, label: IPointer[GLchar]) -> None: pass

    @GLExtAPI.method(VOID, PTR(VOID), GLsizei, PTR(GLsizei), PTR(GLchar))
    def glGetObjectPtrLabel(ptr: IPointer[int], bufSize: int, length: IPointer[GLsizei], label: IPointer[GLchar]) -> None: pass

    @opengl32.foreign(VOID, GLenum, PTR(PTR(VOID)))
    def glGetPointerv(pname: int, params: IPointer[IPointer[int]]) -> None: pass

