#
# This file generated by a Win.Tools.GLGen generator as a part of the Win project.
# Definitions for the OpenGL gl_4.4, do not change this file
# Date/Time of a generation: Thu Aug 27 21:13:35 2026
#

# OpenGL Imports
from win.gl.gl import *
from win.gl.glu import *
from win.abs.glext import *

# Basic OpenGL Types definitions
khronos_int8_t = GLbyte
khronos_uint8_t = GLubyte
khronos_int16_t = GLshort
khornos_uint16_t = GLushort
GLclampx = UINT32
GLeglClientBufferEXT = PVOID
GLeglImageOES = PVOID
GLchar = CHAR
GLcharARB = CHAR
GLhandleARB = UINT
GLhalf = UINT16
GLhalfARB = UINT16
GLfixed = INT32
GLintptr = INT_PTR
GLintptrARB = INT_PTR
GLsizeiptr = SSIZE_T
GLsizeiptrARB = SSIZE_T
GLint64 = INT64
GLint64EXT = INT64
GLuint64 = UINT64
GLuint64EXT = UINT64
GLsync = PVOID
GLDEBUGPROC = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCARB = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCKHR = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCAMD = APIENTRY(VOID, GLuint, GLenum, GLenum, GLsizei, LPSTR, PVOID)
GLhalfNV = USHORT
GLvdpauSurfaceNV = GLintptr
GLVULKANPROCNV = APIENTRY(VOID)

class GL44:
    #
    # Enum definitions
    #

    GL_MAX_VERTEX_ATTRIB_STRIDE = 0x82E5
    GL_PRIMITIVE_RESTART_FOR_PATCHES_SUPPORTED = 0x8221
    GL_TEXTURE_BUFFER_BINDING = 0x8C2A
    GL_MAP_READ_BIT = 0x0001
    GL_MAP_WRITE_BIT = 0x0002
    GL_MAP_PERSISTENT_BIT = 0x0040
    GL_MAP_COHERENT_BIT = 0x0080
    GL_DYNAMIC_STORAGE_BIT = 0x0100
    GL_CLIENT_STORAGE_BIT = 0x0200
    GL_CLIENT_MAPPED_BUFFER_BARRIER_BIT = 0x00004000
    GL_BUFFER_IMMUTABLE_STORAGE = 0x821F
    GL_BUFFER_STORAGE_FLAGS = 0x8220
    GL_CLEAR_TEXTURE = 0x9365
    GL_LOCATION_COMPONENT = 0x934A
    GL_TRANSFORM_FEEDBACK_BUFFER = 0x8C8E
    GL_TRANSFORM_FEEDBACK_BUFFER_INDEX = 0x934B
    GL_TRANSFORM_FEEDBACK_BUFFER_STRIDE = 0x934C
    GL_QUERY_BUFFER = 0x9192
    GL_QUERY_BUFFER_BARRIER_BIT = 0x00008000
    GL_QUERY_BUFFER_BINDING = 0x9193
    GL_QUERY_RESULT_NO_WAIT = 0x9194
    GL_MIRROR_CLAMP_TO_EDGE = 0x8743
    GL_STENCIL_INDEX = 0x1901
    GL_STENCIL_INDEX8 = 0x8D48
    GL_UNSIGNED_INT_10F_11F_11F_REV = 0x8C3B

    #
    # Function/Command definitions
    #

    @GLExtAPI.method(VOID, GLenum, GLsizeiptr, PTR(VOID), GLbitfield)
    def glBufferStorage(target: int, size: int, data: IPointer[int], flags: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLenum, GLenum, PTR(VOID))
    def glClearTexImage(texture: int, level: int, format: int, type: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, PTR(VOID))
    def glClearTexSubImage(texture: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, format: int, type: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint, GLsizei, PTR(GLuint))
    def glBindBuffersBase(target: int, first: int, count: int, buffers: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLuint, GLsizei, PTR(GLuint), PTR(GLintptr), PTR(GLsizeiptr))
    def glBindBuffersRange(target: int, first: int, count: int, buffers: IPointer[GLuint], offsets: IPointer[GLintptr], sizes: IPointer[GLsizeiptr]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(GLuint))
    def glBindTextures(first: int, count: int, textures: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(GLuint))
    def glBindSamplers(first: int, count: int, samplers: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(GLuint))
    def glBindImageTextures(first: int, count: int, textures: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(GLuint), PTR(GLintptr), PTR(GLsizei))
    def glBindVertexBuffers(first: int, count: int, buffers: IPointer[GLuint], offsets: IPointer[GLintptr], strides: IPointer[GLsizei]) -> None: pass

