#
# This file generated by a Win.Tools.GLGen generator as a part of the Win project.
# Definitions for the OpenGL gl_4.5, do not change this file
# Date/Time of a generation: Thu Aug 27 21:13:35 2026
#

# OpenGL Imports
from win.gl.gl import *
from win.gl.glu import *
from win.abs.glext import *

# Basic OpenGL Types definitions
khronos_int8_t = GLbyte
khronos_uint8_t = GLubyte
khronos_int16_t = GLshort
khornos_uint16_t = GLushort
GLclampx = UINT32
GLeglClientBufferEXT = PVOID
GLeglImageOES = PVOID
GLchar = CHAR
GLcharARB = CHAR
GLhandleARB = UINT
GLhalf = UINT16
GLhalfARB = UINT16
GLfixed = INT32
GLintptr = INT_PTR
GLintptrARB = INT_PTR
GLsizeiptr = SSIZE_T
GLsizeiptrARB = SSIZE_T
GLint64 = INT64
GLint64EXT = INT64
GLuint64 = UINT64
GLuint64EXT = UINT64
GLsync = PVOID
GLDEBUGPROC = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCARB = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCKHR = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCAMD = APIENTRY(VOID, GLuint, GLenum, GLenum, GLsizei, LPSTR, PVOID)
GLhalfNV = USHORT
GLvdpauSurfaceNV = GLintptr
GLVULKANPROCNV = APIENTRY(VOID)

class GL45:
    #
    # Enum definitions
    #

    GL_CONTEXT_LOST = 0x0507
    GL_LOWER_LEFT = 0x8CA1
    GL_UPPER_LEFT = 0x8CA2
    GL_NEGATIVE_ONE_TO_ONE = 0x935E
    GL_ZERO_TO_ONE = 0x935F
    GL_CLIP_ORIGIN = 0x935C
    GL_CLIP_DEPTH_MODE = 0x935D
    GL_QUERY_WAIT_INVERTED = 0x8E17
    GL_QUERY_NO_WAIT_INVERTED = 0x8E18
    GL_QUERY_BY_REGION_WAIT_INVERTED = 0x8E19
    GL_QUERY_BY_REGION_NO_WAIT_INVERTED = 0x8E1A
    GL_MAX_CULL_DISTANCES = 0x82F9
    GL_MAX_COMBINED_CLIP_AND_CULL_DISTANCES = 0x82FA
    GL_TEXTURE_TARGET = 0x1006
    GL_QUERY_TARGET = 0x82EA
    GL_TEXTURE_BINDING_1D = 0x8068
    GL_TEXTURE_BINDING_1D_ARRAY = 0x8C1C
    GL_TEXTURE_BINDING_2D = 0x8069
    GL_TEXTURE_BINDING_2D_ARRAY = 0x8C1D
    GL_TEXTURE_BINDING_2D_MULTISAMPLE = 0x9104
    GL_TEXTURE_BINDING_2D_MULTISAMPLE_ARRAY = 0x9105
    GL_TEXTURE_BINDING_3D = 0x806A
    GL_TEXTURE_BINDING_BUFFER = 0x8C2C
    GL_TEXTURE_BINDING_CUBE_MAP = 0x8514
    GL_TEXTURE_BINDING_CUBE_MAP_ARRAY = 0x900A
    GL_TEXTURE_BINDING_RECTANGLE = 0x84F6
    GL_BACK = 0x0405
    GL_NO_ERROR = 0
    GL_GUILTY_CONTEXT_RESET = 0x8253
    GL_INNOCENT_CONTEXT_RESET = 0x8254
    GL_UNKNOWN_CONTEXT_RESET = 0x8255
    GL_RESET_NOTIFICATION_STRATEGY = 0x8256
    GL_LOSE_CONTEXT_ON_RESET = 0x8252
    GL_NO_RESET_NOTIFICATION = 0x8261
    GL_CONTEXT_FLAG_ROBUST_ACCESS_BIT = 0x00000004
    GL_CONTEXT_LOST = 0x0507
    GL_COLOR_TABLE = 0x80D0
    GL_POST_CONVOLUTION_COLOR_TABLE = 0x80D1
    GL_POST_COLOR_MATRIX_COLOR_TABLE = 0x80D2
    GL_PROXY_COLOR_TABLE = 0x80D3
    GL_PROXY_POST_CONVOLUTION_COLOR_TABLE = 0x80D4
    GL_PROXY_POST_COLOR_MATRIX_COLOR_TABLE = 0x80D5
    GL_CONVOLUTION_1D = 0x8010
    GL_CONVOLUTION_2D = 0x8011
    GL_SEPARABLE_2D = 0x8012
    GL_HISTOGRAM = 0x8024
    GL_PROXY_HISTOGRAM = 0x8025
    GL_MINMAX = 0x802E
    GL_CONTEXT_RELEASE_BEHAVIOR = 0x82FB
    GL_NONE = 0
    GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH = 0x82FC

    #
    # Function/Command definitions
    #

    @GLExtAPI.method(VOID, GLenum, GLenum)
    def glClipControl(origin: int, depth: int) -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint))
    def glCreateTransformFeedbacks(n: int, ids: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLuint)
    def glTransformFeedbackBufferBase(xfb: int, index: int, buffer: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLuint, GLintptr, GLsizeiptr)
    def glTransformFeedbackBufferRange(xfb: int, index: int, buffer: int, offset: int, size: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glGetTransformFeedbackiv(xfb: int, pname: int, param: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLuint, PTR(GLint))
    def glGetTransformFeedbacki_v(xfb: int, pname: int, index: int, param: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLuint, PTR(GLint64))
    def glGetTransformFeedbacki64_v(xfb: int, pname: int, index: int, param: IPointer[GLint64]) -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint))
    def glCreateBuffers(n: int, buffers: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizeiptr, PTR(VOID), GLbitfield)
    def glNamedBufferStorage(buffer: int, size: int, data: IPointer[int], flags: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizeiptr, PTR(VOID), GLenum)
    def glNamedBufferData(buffer: int, size: int, data: IPointer[int], usage: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLintptr, GLsizeiptr, PTR(VOID))
    def glNamedBufferSubData(buffer: int, offset: int, size: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLintptr, GLintptr, GLsizeiptr)
    def glCopyNamedBufferSubData(readBuffer: int, writeBuffer: int, readOffset: int, writeOffset: int, size: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLenum, GLenum, PTR(VOID))
    def glClearNamedBufferData(buffer: int, internalformat: int, format: int, type: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLintptr, GLsizeiptr, GLenum, GLenum, PTR(VOID))
    def glClearNamedBufferSubData(buffer: int, internalformat: int, offset: int, size: int, format: int, type: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(PTR(VOID), GLuint, GLenum)
    def glMapNamedBuffer(buffer: int, access: int) -> IPointer[int]: pass

    @GLExtAPI.method(PTR(VOID), GLuint, GLintptr, GLsizeiptr, GLbitfield)
    def glMapNamedBufferRange(buffer: int, offset: int, length: int, access: int) -> IPointer[int]: pass

    @GLExtAPI.method(GLboolean, GLuint)
    def glUnmapNamedBuffer(buffer: int) -> int: pass

    @GLExtAPI.method(VOID, GLuint, GLintptr, GLsizeiptr)
    def glFlushMappedNamedBufferRange(buffer: int, offset: int, length: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glGetNamedBufferParameteriv(buffer: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint64))
    def glGetNamedBufferParameteri64v(buffer: int, pname: int, params: IPointer[GLint64]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(PTR(VOID)))
    def glGetNamedBufferPointerv(buffer: int, pname: int, params: IPointer[IPointer[int]]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLintptr, GLsizeiptr, PTR(VOID))
    def glGetNamedBufferSubData(buffer: int, offset: int, size: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint))
    def glCreateFramebuffers(n: int, framebuffers: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLenum, GLuint)
    def glNamedFramebufferRenderbuffer(framebuffer: int, attachment: int, renderbuffertarget: int, renderbuffer: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLint)
    def glNamedFramebufferParameteri(framebuffer: int, pname: int, param: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLuint, GLint)
    def glNamedFramebufferTexture(framebuffer: int, attachment: int, texture: int, level: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLuint, GLint, GLint)
    def glNamedFramebufferTextureLayer(framebuffer: int, attachment: int, texture: int, level: int, layer: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum)
    def glNamedFramebufferDrawBuffer(framebuffer: int, buf: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(GLenum))
    def glNamedFramebufferDrawBuffers(framebuffer: int, n: int, bufs: IPointer[GLenum]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum)
    def glNamedFramebufferReadBuffer(framebuffer: int, src: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(GLenum))
    def glInvalidateNamedFramebufferData(framebuffer: int, numAttachments: int, attachments: IPointer[GLenum]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, PTR(GLenum), GLint, GLint, GLsizei, GLsizei)
    def glInvalidateNamedFramebufferSubData(framebuffer: int, numAttachments: int, attachments: IPointer[GLenum], x: int, y: int, width: int, height: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLint, PTR(GLint))
    def glClearNamedFramebufferiv(framebuffer: int, buffer: int, drawbuffer: int, value: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLint, PTR(GLuint))
    def glClearNamedFramebufferuiv(framebuffer: int, buffer: int, drawbuffer: int, value: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLint, PTR(GLfloat))
    def glClearNamedFramebufferfv(framebuffer: int, buffer: int, drawbuffer: int, value: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLint, GLfloat, GLint)
    def glClearNamedFramebufferfi(framebuffer: int, buffer: int, drawbuffer: int, depth: float, stencil: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLint, GLbitfield, GLenum)
    def glBlitNamedFramebuffer(readFramebuffer: int, drawFramebuffer: int, srcX0: int, srcY0: int, srcX1: int, srcY1: int, dstX0: int, dstY0: int, dstX1: int, dstY1: int, mask: int, filter: int) -> None: pass

    @GLExtAPI.method(GLenum, GLuint, GLenum)
    def glCheckNamedFramebufferStatus(framebuffer: int, target: int) -> int: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glGetNamedFramebufferParameteriv(framebuffer: int, pname: int, param: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLenum, PTR(GLint))
    def glGetNamedFramebufferAttachmentParameteriv(framebuffer: int, attachment: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint))
    def glCreateRenderbuffers(n: int, renderbuffers: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLsizei, GLsizei)
    def glNamedRenderbufferStorage(renderbuffer: int, internalformat: int, width: int, height: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, GLenum, GLsizei, GLsizei)
    def glNamedRenderbufferStorageMultisample(renderbuffer: int, samples: int, internalformat: int, width: int, height: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glGetNamedRenderbufferParameteriv(renderbuffer: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLsizei, PTR(GLuint))
    def glCreateTextures(target: int, n: int, textures: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLuint)
    def glTextureBuffer(texture: int, internalformat: int, buffer: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLuint, GLintptr, GLsizeiptr)
    def glTextureBufferRange(texture: int, internalformat: int, buffer: int, offset: int, size: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, GLenum, GLsizei)
    def glTextureStorage1D(texture: int, levels: int, internalformat: int, width: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, GLenum, GLsizei, GLsizei)
    def glTextureStorage2D(texture: int, levels: int, internalformat: int, width: int, height: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, GLenum, GLsizei, GLsizei, GLsizei)
    def glTextureStorage3D(texture: int, levels: int, internalformat: int, width: int, height: int, depth: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, GLenum, GLsizei, GLsizei, GLboolean)
    def glTextureStorage2DMultisample(texture: int, samples: int, internalformat: int, width: int, height: int, fixedsamplelocations: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLsizei, GLenum, GLsizei, GLsizei, GLsizei, GLboolean)
    def glTextureStorage3DMultisample(texture: int, samples: int, internalformat: int, width: int, height: int, depth: int, fixedsamplelocations: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint, GLsizei, GLenum, GLenum, PTR(VOID))
    def glTextureSubImage1D(texture: int, level: int, xoffset: int, width: int, format: int, type: int, pixels: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, PTR(VOID))
    def glTextureSubImage2D(texture: int, level: int, xoffset: int, yoffset: int, width: int, height: int, format: int, type: int, pixels: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, PTR(VOID))
    def glTextureSubImage3D(texture: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, format: int, type: int, pixels: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint, GLsizei, GLenum, GLsizei, PTR(VOID))
    def glCompressedTextureSubImage1D(texture: int, level: int, xoffset: int, width: int, format: int, imageSize: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint, GLint, GLsizei, GLsizei, GLenum, GLsizei, PTR(VOID))
    def glCompressedTextureSubImage2D(texture: int, level: int, xoffset: int, yoffset: int, width: int, height: int, format: int, imageSize: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLsizei, PTR(VOID))
    def glCompressedTextureSubImage3D(texture: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, format: int, imageSize: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint, GLint, GLint, GLsizei)
    def glCopyTextureSubImage1D(texture: int, level: int, xoffset: int, x: int, y: int, width: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei)
    def glCopyTextureSubImage2D(texture: int, level: int, xoffset: int, yoffset: int, x: int, y: int, width: int, height: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint, GLint, GLint, GLint, GLint, GLsizei, GLsizei)
    def glCopyTextureSubImage3D(texture: int, level: int, xoffset: int, yoffset: int, zoffset: int, x: int, y: int, width: int, height: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLfloat)
    def glTextureParameterf(texture: int, pname: int, param: float) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLfloat))
    def glTextureParameterfv(texture: int, pname: int, param: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, GLint)
    def glTextureParameteri(texture: int, pname: int, param: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glTextureParameterIiv(texture: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLuint))
    def glTextureParameterIuiv(texture: int, pname: int, params: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glTextureParameteriv(texture: int, pname: int, param: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint)
    def glGenerateTextureMipmap(texture: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint)
    def glBindTextureUnit(unit: int, texture: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLenum, GLenum, GLsizei, PTR(VOID))
    def glGetTextureImage(texture: int, level: int, format: int, type: int, bufSize: int, pixels: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(VOID))
    def glGetCompressedTextureImage(texture: int, level: int, bufSize: int, pixels: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLenum, PTR(GLfloat))
    def glGetTextureLevelParameterfv(texture: int, level: int, pname: int, params: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLenum, PTR(GLint))
    def glGetTextureLevelParameteriv(texture: int, level: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLfloat))
    def glGetTextureParameterfv(texture: int, pname: int, params: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glGetTextureParameterIiv(texture: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLuint))
    def glGetTextureParameterIuiv(texture: int, pname: int, params: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glGetTextureParameteriv(texture: int, pname: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint))
    def glCreateVertexArrays(n: int, arrays: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint)
    def glDisableVertexArrayAttrib(vaobj: int, index: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint)
    def glEnableVertexArrayAttrib(vaobj: int, index: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint)
    def glVertexArrayElementBuffer(vaobj: int, buffer: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLuint, GLintptr, GLsizei)
    def glVertexArrayVertexBuffer(vaobj: int, bindingindex: int, buffer: int, offset: int, stride: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLsizei, PTR(GLuint), PTR(GLintptr), PTR(GLsizei))
    def glVertexArrayVertexBuffers(vaobj: int, first: int, count: int, buffers: IPointer[GLuint], offsets: IPointer[GLintptr], strides: IPointer[GLsizei]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLuint)
    def glVertexArrayAttribBinding(vaobj: int, attribindex: int, bindingindex: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLint, GLenum, GLboolean, GLuint)
    def glVertexArrayAttribFormat(vaobj: int, attribindex: int, size: int, type: int, normalized: int, relativeoffset: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLint, GLenum, GLuint)
    def glVertexArrayAttribIFormat(vaobj: int, attribindex: int, size: int, type: int, relativeoffset: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLint, GLenum, GLuint)
    def glVertexArrayAttribLFormat(vaobj: int, attribindex: int, size: int, type: int, relativeoffset: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLuint)
    def glVertexArrayBindingDivisor(vaobj: int, bindingindex: int, divisor: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLenum, PTR(GLint))
    def glGetVertexArrayiv(vaobj: int, pname: int, param: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLenum, PTR(GLint))
    def glGetVertexArrayIndexediv(vaobj: int, index: int, pname: int, param: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLenum, PTR(GLint64))
    def glGetVertexArrayIndexed64iv(vaobj: int, index: int, pname: int, param: IPointer[GLint64]) -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint))
    def glCreateSamplers(n: int, samplers: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLuint))
    def glCreateProgramPipelines(n: int, pipelines: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLsizei, PTR(GLuint))
    def glCreateQueries(target: int, n: int, ids: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLenum, GLintptr)
    def glGetQueryBufferObjecti64v(id: int, buffer: int, pname: int, offset: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLenum, GLintptr)
    def glGetQueryBufferObjectiv(id: int, buffer: int, pname: int, offset: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLenum, GLintptr)
    def glGetQueryBufferObjectui64v(id: int, buffer: int, pname: int, offset: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLuint, GLenum, GLintptr)
    def glGetQueryBufferObjectuiv(id: int, buffer: int, pname: int, offset: int) -> None: pass

    @GLExtAPI.method(VOID, GLbitfield)
    def glMemoryBarrierByRegion(barriers: int) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLenum, GLenum, GLsizei, PTR(VOID))
    def glGetTextureSubImage(texture: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, format: int, type: int, bufSize: int, pixels: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLint, GLint, GLint, GLsizei, GLsizei, GLsizei, GLsizei, PTR(VOID))
    def glGetCompressedTextureSubImage(texture: int, level: int, xoffset: int, yoffset: int, zoffset: int, width: int, height: int, depth: int, bufSize: int, pixels: IPointer[int]) -> None: pass

    @GLExtAPI.method(GLenum, )
    def glGetGraphicsResetStatus() -> int: pass

    @GLExtAPI.method(VOID, GLenum, GLint, GLsizei, PTR(VOID))
    def glGetnCompressedTexImage(target: int, lod: int, bufSize: int, pixels: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLint, GLenum, GLenum, GLsizei, PTR(VOID))
    def glGetnTexImage(target: int, level: int, format: int, type: int, bufSize: int, pixels: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLdouble))
    def glGetnUniformdv(program: int, location: int, bufSize: int, params: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLfloat))
    def glGetnUniformfv(program: int, location: int, bufSize: int, params: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLint))
    def glGetnUniformiv(program: int, location: int, bufSize: int, params: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLuint, GLint, GLsizei, PTR(GLuint))
    def glGetnUniformuiv(program: int, location: int, bufSize: int, params: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLint, GLint, GLsizei, GLsizei, GLenum, GLenum, GLsizei, PTR(VOID))
    def glReadnPixels(x: int, y: int, width: int, height: int, format: int, type: int, bufSize: int, data: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLsizei, PTR(GLdouble))
    def glGetnMapdv(target: int, query: int, bufSize: int, v: IPointer[GLdouble]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLsizei, PTR(GLfloat))
    def glGetnMapfv(target: int, query: int, bufSize: int, v: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLsizei, PTR(GLint))
    def glGetnMapiv(target: int, query: int, bufSize: int, v: IPointer[GLint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLsizei, PTR(GLfloat))
    def glGetnPixelMapfv(map: int, bufSize: int, values: IPointer[GLfloat]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLsizei, PTR(GLuint))
    def glGetnPixelMapuiv(map: int, bufSize: int, values: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLsizei, PTR(GLushort))
    def glGetnPixelMapusv(map: int, bufSize: int, values: IPointer[GLushort]) -> None: pass

    @GLExtAPI.method(VOID, GLsizei, PTR(GLubyte))
    def glGetnPolygonStipple(bufSize: int, pattern: IPointer[GLubyte]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLenum, GLsizei, PTR(VOID))
    def glGetnColorTable(target: int, format: int, type: int, bufSize: int, table: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLenum, GLsizei, PTR(VOID))
    def glGetnConvolutionFilter(target: int, format: int, type: int, bufSize: int, image: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, GLenum, GLsizei, PTR(VOID), GLsizei, PTR(VOID), PTR(VOID))
    def glGetnSeparableFilter(target: int, format: int, type: int, rowBufSize: int, row: IPointer[int], columnBufSize: int, column: IPointer[int], span: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLboolean, GLenum, GLenum, GLsizei, PTR(VOID))
    def glGetnHistogram(target: int, reset: int, format: int, type: int, bufSize: int, values: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLboolean, GLenum, GLenum, GLsizei, PTR(VOID))
    def glGetnMinmax(target: int, reset: int, format: int, type: int, bufSize: int, values: IPointer[int]) -> None: pass

    @GLExtAPI.method(VOID, )
    def glTextureBarrier() -> None: pass

