#
# This file generated by a Win.Tools.GLGen generator as a part of the Win project.
# Definitions for the OpenGL gl_4.6, do not change this file
# Date/Time of a generation: Thu Aug 27 21:13:35 2026
#

# OpenGL Imports
from win.gl.gl import *
from win.gl.glu import *
from win.abs.glext import *

# Basic OpenGL Types definitions
khronos_int8_t = GLbyte
khronos_uint8_t = GLubyte
khronos_int16_t = GLshort
khornos_uint16_t = GLushort
GLclampx = UINT32
GLeglClientBufferEXT = PVOID
GLeglImageOES = PVOID
GLchar = CHAR
GLcharARB = CHAR
GLhandleARB = UINT
GLhalf = UINT16
GLhalfARB = UINT16
GLfixed = INT32
GLintptr = INT_PTR
GLintptrARB = INT_PTR
GLsizeiptr = SSIZE_T
GLsizeiptrARB = SSIZE_T
GLint64 = INT64
GLint64EXT = INT64
GLuint64 = UINT64
GLuint64EXT = UINT64
GLsync = PVOID
GLDEBUGPROC = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCARB = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCKHR = APIENTRY(VOID, GLenum, GLenum, GLuint, GLenum, GLsizei, LPSTR, PVOID)
GLDEBUGPROCAMD = APIENTRY(VOID, GLuint, GLenum, GLenum, GLsizei, LPSTR, PVOID)
GLhalfNV = USHORT
GLvdpauSurfaceNV = GLintptr
GLVULKANPROCNV = APIENTRY(VOID)

class GL46:
    #
    # Enum definitions
    #

    GL_CONTEXT_RELEASE_BEHAVIOR = 0x82FB
    GL_NONE = 0
    GL_CONTEXT_RELEASE_BEHAVIOR_FLUSH = 0x82FC
    GL_SHADER_BINARY_FORMAT_SPIR_V = 0x9551
    GL_SPIR_V_BINARY = 0x9552
    GL_PARAMETER_BUFFER = 0x80EE
    GL_PARAMETER_BUFFER_BINDING = 0x80EF
    GL_CONTEXT_FLAG_NO_ERROR_BIT = 0x00000008
    GL_VERTICES_SUBMITTED = 0x82EE
    GL_PRIMITIVES_SUBMITTED = 0x82EF
    GL_VERTEX_SHADER_INVOCATIONS = 0x82F0
    GL_TESS_CONTROL_SHADER_PATCHES = 0x82F1
    GL_TESS_EVALUATION_SHADER_INVOCATIONS = 0x82F2
    GL_GEOMETRY_SHADER_INVOCATIONS = 0x887F
    GL_GEOMETRY_SHADER_PRIMITIVES_EMITTED = 0x82F3
    GL_FRAGMENT_SHADER_INVOCATIONS = 0x82F4
    GL_COMPUTE_SHADER_INVOCATIONS = 0x82F5
    GL_CLIPPING_INPUT_PRIMITIVES = 0x82F6
    GL_CLIPPING_OUTPUT_PRIMITIVES = 0x82F7
    GL_POLYGON_OFFSET_CLAMP = 0x8E1B
    GL_SPIR_V_EXTENSIONS = 0x9553
    GL_NUM_SPIR_V_EXTENSIONS = 0x9554
    GL_TEXTURE_MAX_ANISOTROPY = 0x84FE
    GL_MAX_TEXTURE_MAX_ANISOTROPY = 0x84FF
    GL_TRANSFORM_FEEDBACK_OVERFLOW = 0x82EC
    GL_TRANSFORM_FEEDBACK_STREAM_OVERFLOW = 0x82ED

    #
    # Function/Command definitions
    #

    @GLExtAPI.method(VOID, GLuint, PTR(GLchar), GLuint, PTR(GLuint), PTR(GLuint))
    def glSpecializeShader(shader: int, pEntryPoint: IPointer[GLchar], numSpecializationConstants: int, pConstantIndex: IPointer[GLuint], pConstantValue: IPointer[GLuint]) -> None: pass

    @GLExtAPI.method(VOID, GLenum, PTR(VOID), GLintptr, GLsizei, GLsizei)
    def glMultiDrawArraysIndirectCount(mode: int, indirect: IPointer[int], drawcount: int, maxdrawcount: int, stride: int) -> None: pass

    @GLExtAPI.method(VOID, GLenum, GLenum, PTR(VOID), GLintptr, GLsizei, GLsizei)
    def glMultiDrawElementsIndirectCount(mode: int, type: int, indirect: IPointer[int], drawcount: int, maxdrawcount: int, stride: int) -> None: pass

    @GLExtAPI.method(VOID, GLfloat, GLfloat, GLfloat)
    def glPolygonOffsetClamp(factor: float, units: float, clamp: float) -> None: pass

