from .interop import (_Type, _FieldInfo, _MemberInfo, 
                      _PropertyInfo, _MethodInfo, 
                      _ParameterInfo)
from ..com.icl.wicl.codegen import *
from .ntlext import *

# shut up ntdll heap corruption exception
from ..com.icl.tlb2icl import parser

provider = WET_PROVIDER('NTL-Gen')

class NtlCode(Code):
    def add_import(self, storage_import: str, import_type: str = '*'):
        assert self.file and not self.file.closed
        
        if import_type is not None:
            self.file.write(f'from {storage_import} import {import_type}\n')
        else:
            if storage_import.startswith('.'):
                self.file.write(f'from . import {storage_import[1:]}\n')
            else:
                self.file.write(f'import {storage_import}\n')
    
    def append_indented(self, string: str):
        assert self.file and not self.file.closed
            
        self.file.write(self.make_indents() + string + '\n')

def NtlGenInit():
    global MSCORLIB, ATTR, METHINFO, PARAINFO
    if not NtlIsRunning():
        if NtlExtGetInitState() == NtlInitState.Failure:
            raise RuntimeError('Previously CLR initialization failed, the CLR will not initialized again.')
        NtlInitCLR()
        MSCORLIB = NtlLoadMscorlib()
    else:
        MSCORLIB = NtlExtGetMscorlib()
    METHINFO = MSCORLIB.System.Reflection.MethodInfo._type
    PARAINFO = MSCORLIB.System.Reflection.ParameterInfo._type
    ATTR = MSCORLIB.System.Attribute
            
def NtlGenPureCode(isPureCode: bool):
    global PURE_CODE, NPURE_CODE
    PURE_CODE = isPureCode
    NPURE_CODE = not isPureCode
            
BF_PUB_STAT = BindingFlags.Public | BindingFlags.Static
BF_PUB_INST = BindingFlags.Public | BindingFlags.Instance

PURE_CODE = False
NPURE_CODE = True
PARAINFO = None
ATTR = None

MSCORLIB = None
LIST_EMPTY = []
SELF_ENTRY = ('self', '')
SELF_LIST = [SELF_ENTRY]

class NtlGen:
    assembly: Assembly
    code: NtlCode
    
    def __init__(self, file_path: str, assembly: Assembly):
        self.code = NtlCode(file_path)
        self.assembly = assembly
    
    def generate(self):
        if NPURE_CODE:
            self.code.append_comment()
            self.code.append_comment('Generated by NTLGen Version 1.00')
            self.code.append_comment(f'Generated from assembly: {self.assembly._assembly}')
            self.code.append_comment(f'Output file: {self.code.file.name}')
            self.code.append_comment()
            self.code.append_newline()
        
            self.code.add_import('win.net.ntlext')
            self.code.append_newline()
        else:
            self.code.add_import('win.net.ntlext')
        
        self.generate_namespaces(self.assembly)
        
    def generate_namespaces(self, storage: Any):
        attributes = dir(storage)
        
        for attribute in attributes:
            value = getattr(storage, attribute)
            
            if isinstance(value, type):
                if issubclass(value, INamespace):
                    self.code.append_class(attribute, 'INamespace')
                    self.code.indent()
                    self.generate_namespaces(value)
                    self.code.unindent()
                elif issubclass(value, Object):
                    self.generate_metadata_comment(value)
                    self.code.append_class(attribute, 'Object')
                    self.code.indent()
                    self.generate_object(value)
                    self.code.unindent()
        
    def generate_metadata_comment(self, object_type: type[Object]):
        if PURE_CODE: return
        self.code.append_comment()
        itf = object_type._type
        
        self.generate_attributes_metadata_comment(itf)
        
        self.code.append_comment('- .NET Type description:')
        description = []
        
        description.append('public')
        
        if itf.IsSealed:
            description.append('sealed')
        
        if itf.IsAbstract and not itf.IsInterface:
            description.append('abstract')
        
        if itf.IsInterface:
            description.append('interface')
        elif itf.IsEnum:
            description.append('enum')
        elif itf.IsPrimitive:
            pass
        elif itf.IsValueType:
            description.append('struct')
        elif itf.IsClass:
            description.append('class')
            
        description.append(TlAccessOAStringAndFree(itf.name).split('`')[0])
        description.append(':')
        baseType = itf.BaseType
        if baseType:
            try:
                description.append(TlAccessOAStringAndFree(baseType.FullName) + ',')
            except:
                description.append('@FailedToGetTypeName')
#             baseType.Release()
        
        interfacesSA = itf.GetInterfaces()
        interfaces: list[_Type] = interfacesSA.value
        
        for interface in interfaces:
            interfaceName = TlAccessOAStringAndFree(interface.FullName)
            if interfaceName is None: continue
            components = interfaceName.split('`')
        
            if len(components) != 1: 
                interfaceName, generic = components
            
                generic = generic.split('[')[-1]
                generic = generic[:-1].replace(',', ', ')
            
                interfaceName = f'{interfaceName}<{generic}>'
            
            description.append(interfaceName + ',')
            
        description[-1] = description[-1][:-1]
        
        SafeArrayDestroy(interfacesSA.ref())
        
        self.code.append_comment(' '.join(description))
        
        self.code.append_comment()
        
    def get_attribute_name(self, attribute_data: Object):
        attribute_name: str = attribute_data.AttributeType.Name
        if attribute_name.endswith('Attribute'):
            attribute_name = attribute_name[:-9]
        return attribute_name
    
    def generate_attributes_metadata_comment(self, itf: _MemberInfo):
        self.code.append_comment('- Attribute metadata:')
        attributesSA = itf.GetCustomAttributes_2(False)
        attributes: list[Object] = attributesSA.value
        
        for attribute in attributes:
            if isinstance(attribute, ATTR):
                data = attribute.GetCustomAttributesData()
                name = self.get_attribute_name(data)
                attribute_string = f'[{name}('
                have_arguments = False
                
                for argument in data.ConstructorArguments:
                    if not have_arguments: have_arguments = True
                    attribute_string += f'{argument.Value}, '
                
                for argument in data.NamedArguments:
                    if not have_arguments: have_arguments = True
                    attribute_string += f'{argument.MemberName}={argument.TypedValue.Value}, '
                
                if have_arguments:
                    attribute_string = attribute_string[:-2] + ')]'
                else:
                    attribute_string = attribute_string[:-1] + ']'
                    
                self.code.append_comment(attribute_string)
                
#                 attribute.Release()
            
        SafeArrayDestroy(attributesSA.ref())
    
    def generate_object(self, obj: Object):
        itf = obj._type
        
        static = self.get_fields(itf, BF_PUB_STAT)
        instance = self.get_fields(itf, BF_PUB_INST)
        gencommst = static and NPURE_CODE
        gencommin = instance and NPURE_CODE
        
        if gencommst:
            self.code.append_comment('Static fields')
            
        for static_field in static:
            name = TlAccessOAStringAndFree(static_field.name)
            field_type = static_field.FieldType
            python_type = self.NET_type_to_python(field_type)
#             field_type.Release()
            self.code.append_field(name, f'ClassVar[{python_type}]')
#             static_field.Release()
        
        if gencommst:
            self.code.append_newline()
        
        if gencommin:
            self.code.append_comment('Instance fields')
        
        for field in instance:
            name = TlAccessOAStringAndFree(field.name)
            field_type = field.FieldType
            python_type = self.NET_type_to_python(field_type)
#             field_type.Release()
            self.code.append_field(name, f'{python_type}')
#             field.Release()
        
        if gencommin:
            self.code.append_newline()
        
        static = self.get_properties(itf, BF_PUB_STAT)
        instance = self.get_properties(itf, BF_PUB_INST)
        gencommst = static and NPURE_CODE
        gencommin = instance and NPURE_CODE
        
        if gencommst:
            self.code.append_comment('Static properties')
            
        for static_property in static:
            name = TlAccessOAStringAndFree(static_property.name)
            if name in obj._indexers:
                continue
            property_type = static_property.PropertyType
            python_type = self.NET_type_to_python(property_type)
#             property_type.Release()
            
            self.code.append_field(name, f'ClassVar[{python_type}]')
#             static_property.Release()
        
        if gencommst:
            self.code.append_newline()
            
        if gencommin:
            self.code.append_comment('Instance properties')
        
        for property in instance:
            name = TlAccessOAStringAndFree(property.name)
            property_type = property.PropertyType
            python_type = self.NET_type_to_python(property_type)
#             property_type.Release()
            
            if name in obj._indexers:
                if property.CanWrite:
                    self.code.append_field(name, f'SupportsGetSet[{python_type}]')
                else:
                    self.code.append_field(name, f'SupportsGet[{python_type}]')
            else:
                self.code.append_decorator('property', LIST_EMPTY, LIST_EMPTY)
                self.code.append_function(name, python_type, SELF_LIST, LIST_EMPTY)
                
                if property.CanWrite:
                    self.code.append_decorator(name + '.setter', LIST_EMPTY, LIST_EMPTY)
                    self.code.append_function(name, '', [SELF_ENTRY, ('value', python_type)], LIST_EMPTY)
            
#             property.Release()
        
        if gencommin:
            self.code.append_newline()
        
        static = self.get_methods(itf, BF_PUB_STAT)
        instance = self.get_methods(itf, BF_PUB_INST)
        gencommst = static and NPURE_CODE
        gencommin = instance and NPURE_CODE
        static_count: dict[str, int] = {}
        instance_count: dict[str, int] = {}
        
        for static_method in static:
            name = TlAccessOAStringAndFree(static_method.name)
            
            if name not in static_count:
                static_count[name] = 1
            else:
                static_count[name] += 1
        
        for method in instance:
            name = TlAccessOAStringAndFree(method.name)
            
            if name not in instance_count:
                instance_count[name] = 1
            else:
                instance_count[name] += 1
        
        if gencommst:
            self.code.append_comment('Static methods')
        
        for static_method in static:
            name = TlAccessOAStringAndFree(static_method.name)
            return_type = static_method.returnType
            arguments = []
            parameters = self.get_parameters(static_method)
            
            for parameter in parameters:
                parameter_obj = Object.construct(PARAINFO).from_object(parameter)
                parameter_name = parameter_obj.Name
                parameter_type = parameter_obj.ParameterType
                parameter_python_type = self.NET_type_to_python(i_cast_structure(parameter_type._object, _Type))
#                 parameter_type.Release()
                arguments.append((parameter_name, parameter_python_type))
#                 parameter_obj.Release()
                
            self.code.append_decorator('staticmethod', LIST_EMPTY, LIST_EMPTY)
            if static_count[name] != 1:
                self.code.append_decorator('overload', LIST_EMPTY, LIST_EMPTY)
            if method.IsConstructor:
                name = '__init__'
            self.code.append_function(name, self.NET_type_to_python(return_type),
                                      arguments, LIST_EMPTY)
#             static_method.Release()
        
        if gencommin:
            self.code.append_comment('Instance methods')
        
        for method in instance:
            name = TlAccessOAStringAndFree(method.name)
            return_type = method.returnType
            arguments = [SELF_ENTRY]
            parameters = self.get_parameters(method)
            # print(name, 'bavariya')
            for parameter in parameters:
                parameter_obj = Object.construct(PARAINFO).from_object(parameter)
                parameter_name = parameter_obj.Name
                parameter_type = parameter_obj.ParameterType
                # print(parameter_name, parameter_type, 'pivnoylarek')
                if parameter_type:
                    # print('okayanniy')
                    parameter_python_type = self.NET_type_to_python(TlQueryInterface(parameter_type._object, _Type))
#                     parameter_type.Release()
                # print('obzhora')
                arguments.append((parameter_name, parameter_python_type))
#                 parameter_obj.Release()
            if instance_count[name] != 1:
                self.code.append_decorator('overload', LIST_EMPTY, LIST_EMPTY)
            if method.IsConstructor:
                name = '__init__'
            self.code.append_function(name, self.NET_type_to_python(return_type),
                                      arguments, LIST_EMPTY)
#             method.Release()
        
    def get_fields(self, itf: _Type, flags: int) -> list[_FieldInfo]:
        fieldsSA = itf.GetFields(flags)
        fields = fieldsSA.value
        
        SafeArrayDestroy(fieldsSA.ref())
        return fields
        
    def get_properties(self, itf: _Type, flags: int) -> list[_PropertyInfo]:
        propertiesSA = itf.GetProperties(flags)
        properties = propertiesSA.value
        
        SafeArrayDestroy(propertiesSA.ref())
        return properties
        
    def get_methods(self, itf: _Type, flags: int) -> list[_MethodInfo]:
        methodsSA = itf.GetMethods(flags)
        methods = methodsSA.value
        
        SafeArrayDestroy(methodsSA.ref())
        return methods
    
    def get_parameters(self, itf: _MethodInfo) -> list[_ParameterInfo]:
        parametersSA = itf.GetParameters()
        parameters = parametersSA.value
        
        SafeArrayDestroy(parametersSA.ref())
        return parameters
    
    def NET_type_to_python(self, itf: _Type) -> str:
        # print('komarov', itf)
        if not itf: 
            return ''
        try:
            # print('zinaida')
            # print(format_hex(PtrUtil.get_address(itf.FullName), 8))
            # print(itf.name.value)
            fullname = itf.FullName
            # print('petarda')
            # print(fullname.value)
            # print('hokkey')
            name = TlAccessOAStringAndFree(fullname)
            # print('kimono')
            is_array = itf.IsArray
        except:
            return ''
        
        # print('herovo')
        
        if name is None:
            # print('zadneprivodniy')
            return ''
        
        py_type = NET_T_TO_PY.get(name, None)
        if py_type is None:
            if is_array:
                return f'list[{name.rstrip("[]")}]'
            return f"'{name.replace('`', '_P')}'"
        if is_array:
            return f'list[{py_type}]'
        return py_type
    
NET_T_TO_PY = {
    'System.SByte': 'int', 'System.Byte': 'int', 
    'System.Int16': 'int', 'System.UInt16': 'int',
    'System.Int32': 'int', 'System.UInt32': 'int',
    'System.Int64': 'int', 'System.UInt64': 'int',
    'System.IntPtr': 'int', 'System.UIntPtr': 'int',
    'System.Boolean': 'bool', 'System.String': 'str',
    'System.Void': ''
}